### ISSUE TITLE
HIGHT cipher troubles with FileSource (CTR mode only)

### ISSUE THREAD

**Issue by clementmartin971** [weidai11/cryptopp#1010]
Using the code provided as `HIGHT` example in Wiki and replacing `CBC_Mode` by `CTR_Mode` is working...  but next switching from `StringSource` to `FileSource` doesn't work anymore.

* the first ciphered block has 0 content (with 0 Key and Iv) instead of correct values
* ciphered content with StringSource : 7f 9f 0c 1c c1 9f c4 33 82 3f ee 8f dc
* ciphered content with FileSource : 00 00 00 00 00 00 00 00 82 3F EE 8F DC

The source code to reproduce:

```c++
int main(int argc, char* argv[])
{
   AutoSeededRandomPool prng;
   SecByteBlock key(HIGHT::DEFAULT_KEYLENGTH);
   SecByteBlock iv(HIGHT::BLOCKSIZE);

   prng.GenerateBlock(key, key.size());
   prng.GenerateBlock(iv, iv.size());
   // set key to 0 to better see error
   memset(key.BytePtr(),0,key.size());
   memset(iv.BytePtr(),0,iv.size());
   std::string plain = "CTR Mode Test";
   std::string cipher, encoded, recovered;

   /*********************************\
   \*********************************/

   try
   {
      std::cout << "plain text: " << plain << std::endl;

      CTR_Mode< HIGHT >::Encryption e;
      e.SetKeyWithIV(key, key.size(), iv);

      #if 0 
      // string source is working well
      StringSource s(plain, true, 
         new StreamTransformationFilter(e,
            new StringSink(cipher)
         ) // StreamTransformationFilter
      ); // StringSource
      #endif

      // file source doesn't work :(
      FileSource f("ansi_text_file_with_content_CTR Mode Test_.txt", true, 
         new CryptoPP::StreamTransformationFilter(e,
            new CryptoPP::StringSink(cipher)
         ) // StreamTransformationFilter
      ); // StringSource
      // at this point cipher differ from StringSource and FileSource
   }
   catch(const CryptoPP::Exception& e)
   {
      std::cerr << e.what() << std::endl;
      exit(1);
   }

   /*********************************\
   \*********************************/

   Print("key", std::string((const char*)key.begin(), key.size()));
   Print("iv", std::string((const char*)iv.begin(), iv.size()));
   Print("cipher text", cipher);

   /*********************************\
   \*********************************/

   try
   {
      CTR_Mode< HIGHT >::Decryption d;
      d.SetKeyWithIV(key, key.size(), iv);

      // The StreamTransformationFilter removes
      //  padding as required.
      StringSource s(cipher, true, 
         new StreamTransformationFilter(d,
            new StringSink(recovered)
         ) // StreamTransformationFilter
      ); // StringSource

      std::cout << "recovered text: " << recovered << std::endl;
   }
   catch(const CryptoPP::Exception& e)
   {
      std::cerr << e.what() << std::endl;
      exit(1);
   }
   return 0;
}
```

**Comment by noloader** [comment]
Yeah, something is going sideways here.

We also lack a good set of test vectors for HIGHT in https://github.com/weidai11/cryptopp/blob/master/TestVectors/hight.txt. I don't think the missing test vectors had something to do with this problem, however. Test vectors are run through a `StringSource`.

**Comment by noloader** [comment]
So I've got this tracked down to a function called [AdditiveCipherTemplate::ProcessData](https://github.com/weidai11/cryptopp/blob/master/strciphr.cpp#L94) around line 94. This class has caused us a lot of trouble in the past. Scroll down to around 200 and read the comments for CFB mode.

I _think_ the problem is `inString == outString`. They are the same pointers, and it violates aliasing rules.

Let me see what I can do to get this fixed.

**Comment by clementmartin971** [comment]
I can understand that it's not easy to fix. 
I have tried a little to see what was wrong and didn't success (else I would have post the patch :) )
That surprised me was that it works for StringSource but not for FileSource; like FileStore::TransferTo2 / FileStore::CopyRangeTo2 where doing more processing
Thank you for working on it
Regards

**Comment by clementmartin971** [comment]
I was asking me if the trouble didn't comes from file is eof test
Eof test is calling peek which calls ChannelPut which calls ProcessData
May a workaround could be to provided directly an IsEof virtual method for all Sources providers aka SourceTemplate ?

**Comment by clementmartin971** [comment]
You were right in analysis troubles occurred when inString == outString
for string source inString != outString because StreamTransformationFilter::NextPutMultiple is called (and calls m_cipher.ProcessString(space, inString, len); )
while for file source StreamTransformationFilter::NextPutModifiable is called providing m_cipher.ProcessString(inString, len);

A patch can be done in strciphr.cpp AdditiveCipherTemplate<S>::ProcessData by allocating a temporary output buffer if  inString == outString.
I have done the following but I'm not sure to use correct allocation functions and if wiping is necessary (I didn't know enough cryptopp internals functions and way of protecting data)

template <class S>
void AdditiveCipherTemplate<S>::ProcessData(byte *outString, const byte *inString, size_t length)
{
	byte *outStringBack = outString;
	byte *outStringAlloc = NULLPTR;
	size_t FullLength = length;
	if (outString == inString)
	{
		outStringAlloc = static_cast<byte*>(AlignedAllocate(FullLength));
		if (outStringAlloc == NULLPTR)
			throw std::bad_alloc();
        
		// fill outStringAlloc with inString, in case of error or early break (for copy back at the end of the function)
		memcpy(outStringAlloc,inString,FullLength);

		// make outString point to new allocated buffer
		outString = outStringAlloc;
	}

	if (m_leftOver > 0)
	{
		const size_t len = STDMIN(m_leftOver, length);
		xorbuf(outString, inString, PtrSub(KeystreamBufferEnd(), m_leftOver), len);

		length -= len; m_leftOver -= len;
		inString = PtrAdd(inString, len);
		outString = PtrAdd(outString, len);

		// if (!length) {return;}
		if (!length) {goto CleanUp;}
	}

	PolicyInterface &policy = this->AccessPolicy();
	unsigned int bytesPerIteration = policy.GetBytesPerIteration();

	if (policy.CanOperateKeystream() && length >= bytesPerIteration)
	{
		const size_t iterations = length / bytesPerIteration;
		unsigned int alignment = policy.GetAlignment();
		volatile int inAligned = IsAlignedOn(inString, alignment) << 1;
		volatile int outAligned = IsAlignedOn(outString, alignment) << 0;

		KeystreamOperation operation = KeystreamOperation(inAligned | outAligned);
		policy.OperateKeystream(operation, outString, inString, iterations);

		inString = PtrAdd(inString, iterations * bytesPerIteration);
		outString = PtrAdd(outString, iterations * bytesPerIteration);
		length -= iterations * bytesPerIteration;

		// if (!length) {return;}
		if (!length) {goto CleanUp;}
	}

	size_t bufferByteSize = m_buffer.size();
	size_t bufferIterations = bufferByteSize / bytesPerIteration;

	while (length >= bufferByteSize)
	{
		policy.WriteKeystream(m_buffer, bufferIterations);
		xorbuf(outString, inString, KeystreamBufferBegin(), bufferByteSize);

		length -= bufferByteSize;
		inString = PtrAdd(inString, bufferByteSize);
		outString = PtrAdd(outString, bufferByteSize);
	}

	if (length > 0)
	{
		bufferByteSize = RoundUpToMultipleOf(length, bytesPerIteration);
		bufferIterations = bufferByteSize / bytesPerIteration;

		policy.WriteKeystream(PtrSub(KeystreamBufferEnd(), bufferByteSize), bufferIterations);
		xorbuf(outString, inString, PtrSub(KeystreamBufferEnd(), bufferByteSize), length);
		m_leftOver = bufferByteSize - length;
	}
    
CleanUp:
	if (outStringAlloc)
	{
		memcpy(outStringBack,outStringAlloc,FullLength);
		SecureWipeBuffer(outStringAlloc,FullLength); // Is this required ???
		AlignedDeallocate(outStringAlloc);
	}
}

**Comment by noloader** [comment]
> by allocating a temporary output buffer if inString = = outString.

That will crush performance. We need to find another fix.

**Comment by noloader** [comment]
@clementmartin971,

I **_think_** the way to fix this is, move `AdditiveCipherTemplate::ProcessData` into is own `*.cpp` file **_and_** avoid inlining it. Currently `strcipher.cpp` is inlined by including it at the bottom of `strcipher.h`.

Now, to accomplish it takes some re-jiggering. I think we need to add non-template `AdditiveCipherTemplateBase` that provides `ProcessData`. `AdditiveCipherTemplateBase::ProcessData` would live in a `*.cpp` file, and non-inlined to avoid compiler optimizations and GCC aliasing rules.

`AdditiveCipherTemplateBase::ProcessData` would also need a couple of pure virtuals that get the cipher and policy from a derived class. The derived class would provide the [ugly] template class and implement the pure virtuals.

Something like this (with lots of details removed):

`strcipher.h`:

```
class AdditiveCipherTemplateBase
{
    virtual SymmetricCipher& AccessSymmetricCipher() = 0;
    virtual Policy& AccessSymmetricPolicy() = 0;

    void ProcessData(byte *outString, const byte *inString, size_t length);
    // Other needed stuff
}

template <class BASE = AbstractPolicyHolder<AdditiveCipherAbstractPolicy, SymmetricCipher> >
struct AdditiveCipherTemplate : public BASE, public RandomNumberGenerator, public AdditiveCipherTemplateBase
{
    virtual SymmetricCipher & AccessSymmetricCipher() {
        return dynamic_cast<SymmetricCipher&>(this);
    }
    // Other needed stuff
};
```

Then, `strcipher.cpp` would provide the non-template, non-inlined implementation that _should_ survive optimizations and GCC aliasing rules:

`strcipher.cpp`:
```
// Formerly AdditiveCipherTemplate<S>::ProcessData
void AdditiveCipherTemplateBase::ProcessData(byte *outString, const byte *inString, size_t length)
{
	if (m_leftOver > 0)
	{
		const size_t len = STDMIN(m_leftOver, length);
		xorbuf(outString, inString, PtrSub(KeystreamBufferEnd(), m_leftOver), len);

		length -= len; m_leftOver -= len;
		inString = PtrAdd(inString, len);
		outString = PtrAdd(outString, len);

		if (!length) {return;}
	}

	PolicyInterface &policy = this->AccessPolicy();
	unsigned int bytesPerIteration = policy.GetBytesPerIteration();

	if (policy.CanOperateKeystream() && length >= bytesPerIteration)
	{
		const size_t iterations = length / bytesPerIteration;
		unsigned int alignment = policy.GetAlignment();
		volatile int inAligned = IsAlignedOn(inString, alignment) << 1;
		volatile int outAligned = IsAlignedOn(outString, alignment) << 0;

		KeystreamOperation operation = KeystreamOperation(inAligned | outAligned);
		policy.OperateKeystream(operation, outString, inString, iterations);

		inString = PtrAdd(inString, iterations * bytesPerIteration);
		outString = PtrAdd(outString, iterations * bytesPerIteration);
		length -= iterations * bytesPerIteration;

		if (!length) {return;}
	}

	size_t bufferByteSize = m_buffer.size();
	size_t bufferIterations = bufferByteSize / bytesPerIteration;

	while (length >= bufferByteSize)
	{
		policy.WriteKeystream(m_buffer, bufferIterations);
		xorbuf(outString, inString, KeystreamBufferBegin(), bufferByteSize);

		length -= bufferByteSize;
		inString = PtrAdd(inString, bufferByteSize);
		outString = PtrAdd(outString, bufferByteSize);
	}

	if (length > 0)
	{
		bufferByteSize = RoundUpToMultipleOf(length, bytesPerIteration);
		bufferIterations = bufferByteSize / bytesPerIteration;

		policy.WriteKeystream(PtrSub(KeystreamBufferEnd(), bufferByteSize), bufferIterations);
		xorbuf(outString, inString, PtrSub(KeystreamBufferEnd(), bufferByteSize), length);
		m_leftOver = bufferByteSize - length;
	}
}
```

So all we did was, add a base class without template arguments that allows us to compile `ProcessData` into a `*.cpp` file rather than having it inlined. `AdditiveCipherTemplateBase::ProcessData` needs the cipher object from the derived class, so it provides a couple of pure virtuals.

Let me get some test code together to try it out.

**Comment by noloader** [comment]
@clementmartin971,

I think it was too much trouble to create both a `AdditiveCipherTemplateBase::ProcessData` and a flat `AdditiveCipherTemplate_ProcessData`. I've tried both and they required a lot of changes. I was not able to get `AdditiveCipherTemplate_ProcessData` to work correctly.

The next step is to try to perform explicit instantiations using the existing code. I'm working on that now. It is a major pain because of shoddy compiler support modulo the library complexity.

I may need to go back to `AdditiveCipherTemplate_ProcessData`. It requires both a Policy base interface and a Cipher base interface. It is very messy, but it may be our only choice if explicit instantiations don't work for us.

**Comment by noloader** [comment]
@clementmartin971,

I cleaned up the sources from the previous workaround in [PR #1019](https://github.com/weidai11/cryptopp/pull/1019). I think we are at the point we can move forward with this problem.

**Comment by noloader** [comment]
@clementmartin971,

No joy yet. [PR #1019](https://github.com/weidai11/cryptopp/pull/1019) cleaned up `strciphr.cpp`. [Commit 4eac79fad8e4](https://github.com/weidai11/cryptopp/commit/4eac79fad8e4) cleaned up some shady casts in `xorbuf`.

I also tried your patch with no joy. It failed to decrypt HIGHT ciphertext properly. It also broke OFB mode.

I'm scratching my head...

**Comment by noloader** [comment]
Thanks again @clementmartin971,

This issue was cleared at [Commit 71a812ed9e7c](https://github.com/weidai11/cryptopp/commit/71a812ed9e7c).

Re: this workaround + the `xorbuf` cleanup... It looks like AES/CTR lost about 0.03-0.05 cpb with both changes. That is acceptable. In general, due to `xorbuf` cleanup, most ciphers gained 0.1-0.6 cpb. And RC6 gained 4.8 cpb due to `xorbuf` cleanup.

> I also tried your patch with no joy...

This was incorrect. My implementation was bad. I revisited it this morning and fixed my mistake.

**Comment by noloader** [comment]
Thanks again @clementmartin971,

This issue was cleared at [Commit 71a812ed9e7c](https://github.com/weidai11/cryptopp/commit/71a812ed9e7c) and [Commit bbc45ddfd7fc](https://github.com/weidai11/cryptopp/commit/bbc45ddfd7fc). (The first commit failed to check-in the updated header file).

Re: this workaround + the `xorbuf` cleanup... It looks like AES/CTR lost about 0.03-0.05 cpb with both changes. That is acceptable. In general, most ciphers gained 0.1-0.6 cpb. And RC6 gained 4.4 cpb.

> I also tried your patch with no joy...

This was incorrect. My implementation was bad. I revisited it this morning and fixed my mistake.

Thanks again for your help.

**Comment by noloader** [comment]
@clementmartin971,

I'd like to get more HIGHT test vectors added but that is a problem, too. Sigh...

I used KISA's reference implementation to generate some CTR mode vectors, but we are not arriving at the same result. You can find the KISA implementation at [Noloader | cryptopp-test | HIGHT](https://github.com/noloader/cryptopp-test/tree/master/HIGHT/KISA_HIGHT_ECB_CBC_CTR/%5B01%5D%20C-C%2B%2B/%5B03%5D%20CTR). I'm pretty sure the KISA implementation is bad.

I wrote to the HIGHT team but I have not heard back (yet).

**Comment by expnkx** [comment]
> Thanks again @clementmartin971,
> 
> This issue was cleared at [Commit 71a812ed9e7c](https://github.com/weidai11/cryptopp/commit/71a812ed9e7c) and [Commit bbc45ddfd7fc](https://github.com/weidai11/cryptopp/commit/bbc45ddfd7fc). (The first commit failed to check-in the updated header file).
> 
> Re: this workaround + the `xorbuf` cleanup... It looks like AES/CTR lost about 0.03-0.05 cpb on x86_64 with both changes. That is acceptable. In general, most ciphers gained 0.1-0.6 cpb. And RC6 gained 4.4 cpb.
> 
> > I also tried your patch with no joy...
> 
> This was incorrect. My implementation was bad. I revisited it this morning and fixed my mistake.
> 
> Thanks again for your help.

Hello noloader. Do you think [[gnu::may_alias]] can solve the strict aliasing issues you have here?

**Comment by noloader** [comment]
@clementmartin971,

We now have some self tests that use `FileSource` in addition to `StringSource`. The new tests were mostly copy/paste of existing `StringSource` tests. We should be able to detect a problem like this in the future.

Also see [Commit 07951c11e5d1](https://github.com/weidai11/cryptopp/commit/07951c11e5d1) and [Commit 07951c11e5d1](https://github.com/weidai11/cryptopp/commit/07951c11e5d1).

**Comment by noloader** [comment]
@PassMark, @dgm3333, @clementmartin971

I checked in some code to avoid the extra buffer and memcpy's. It is sitting on the `strciphr` branch.

The code tested Ok for me on x86_64. That's where HIGHT bock cipher had problems. ARMv7 had problems on Linux, and I am testing it now. Can you guys test it on your platforms, please?

You can fetch the code with:

```
$ git fetch origin
$ git checkout strciphr -f && git pull
```

We announced the testing branch on the mailing list at [strciphr.cpp updates](https://groups.google.com/g/cryptopp-users/c/ypt7larHsVc/m/pCkaxuMYBAAJ). If I don't get any complaints over the next week or so, I will merge the changes.

Thanks in advance.

**Comment by clementmartin971** [comment]
Hello,
Sorry for being late... but I'm also on x86_64

**Comment by dgm3333** [comment]
Thanks for this. I've been a bit swamped with another coding push but I should have a chance to rewrite the encryption routines to test impact of multithreading on timing later in the week. However for what it's worth an initial "single thread" (ie any multithreaded processing would be automatic compiler/operating system initiated) encryption/decryption loop of ~150GB / 15k files of data completed without triggering any warnings. (Test PC is running Win 10 pro 64 running on an AMD Ryzen 9 = 12 cores).

**Comment by noloader** [comment]
@dgm3333,

I merged the changes into master last night. You should test master now.

Jeff
