### ISSUE TITLE
setsockopt EINVAL with cryptopp ft 9109 example.com 80

### ISSUE THREAD

**Issue by TierraDelFuego** [weidai11/cryptopp#104]
Is there a better way to send patches? I don't have a github clone of your repo.

```
index a6a2700..a39df88 100644
--- a/test.cpp
+++ b/test.cpp
@@ -796,8 +796,9 @@ void ForwardTcpPort(const char *sourcePortName, const char *destinationHost, con
 
 	sockListen.Create();
 	sockListen.Bind(sourcePort);
-	
-	int err = setsockopt(sockListen, IPPROTO_TCP, TCP_NODELAY, "\x01", 1);
+
+	int one  = 1;
+	int err = setsockopt(sockListen, IPPROTO_TCP, TCP_NODELAY, &one, sizeof(one));
 	assert(err == 0);
 	if(err != 0)
 		throw Socket::Err(sockListen, "setsockopt", sockListen.GetLastError());
```

**Comment by noloader** [comment]
```
+   int one  = 1;
+   int err = setsockopt(sockListen, IPPROTO_TCP, TCP_NODELAY, &one, sizeof(one));
```

I don't believe that is quite correct. On a big-endian system, the leading byte will be 0.

What problem are you trying to solve?

-----

> Is there a better way to send patches? I don't have a github clone of your repo.

Posting like above is fine since its small. Formatting the diff using [GitHub's markdown](http://help.github.com/articles/github-flavored-markdown/) would be helpful. It took me some time to parse it because of the formatting.

We'd prefer a pull request, but that's because we like folks who help to be listed at [Contributors](http://github.com/weidai11/cryptopp/graphs/contributors). If you are indifferent to it, then that's fine too.

**Comment by TierraDelFuego** [comment]
Platform = linux
problem = read the subject

Seems no less portable than existing but I could be wrong, but I don't think so.

**Comment by noloader** [comment]
@Tierra -

> Seems no less portable than existing but I could be wrong, but I don't think so.
Checkout [setsockopt function](http://msdn.microsoft.com/en-us/library/windows/desktop/ms740476%28v=vs.85%29.aspx) on MSDN.

**Comment by noloader** [comment]
I think we're going to pass on this until we can learn more about the problem and platform. Thanks for the time, though.

**Comment by TierraDelFuego** [comment]
I don't understand the point of the link to setsockopt on MSDN. Unless you're being generous and wanted to solidify my point about portability. Was that what you meant?

Your current implementation is wrong on linux and windows and the fix I proposed is valid and portable for linux and windows.
