### ISSUE TITLE
Issue with running ECDH example

### ISSUE THREAD

**Issue by Patrik-ai** [weidai11/cryptopp#1047]
I download recently Crypto++ 8.5. I think its the latest version. Library was build on Linux Ubuntu 20.04 via `make`.

I was trying to build [Elliptic Curve DH example](https://www.cryptopp.com/wiki/Elliptic_Curve_Diffie-Hellman) from the website like this:

```
g++ -DNDEBUG -g3 -O2 -Wall -Wextra -o ecdh-agree.exe ecdh-agree.cpp -l:libcryptopp.a (static lib)
```
or 
```
g++ -g -O2 -DNDEBUG ecdh-agree.cpp -o ecdh-agree.exe -lcryptopp -lpthread
```
but when i tried to run output exe, i get this issue:

![image](https://user-images.githubusercontent.com/79135565/121909941-b55ea300-cd2e-11eb-9b27-624a992a6bdf.png)
 
can you help me with this ?

Thank you for your time

**Comment by noloader** [comment]
@Patrik-ai,

Yeah, it looks like something is sideways. I can duplicate the issue, too.

Give me some time to look at it.

**Comment by noloader** [comment]
@Patrik-ai,

What I found was, the problem surfaced due to mixing and matching versions of the Crypto++ library. The first version was installed by the distro in `/usr`. The second was the local copy.

To fix it you should be able to use:

```
sed -i 's|cryptopp/||g' ecdh-agree.cpp
g++ -DNDEBUG -g3 -O2 -Wall -Wextra -I ./ -o ecdh-agree.exe ecdh-agree.cpp ./libcryptopp.a
```

The `sed` changes `#include "cryptopp/foo.h"` to `#include "foo.h"`. The `-I ./` says use the headers located here (in the `cryptopp` folder).  The `./libcryptopp.a` says use the library located here (in the `cryptopp` folder).

**Comment by Patrik-ai** [comment]
@noloader 
Thanks for your help, removing libcrypto++6 solved my problem :)
