### ISSUE TITLE
Add support for C++ Builder

### ISSUE THREAD

**Issue by tracer1808** [weidai11/cryptopp#1050]
Please add support for C++ Builder (Static Library and Dynamic Link Library projects), as it is supported for Visual Studio.

**Comment by noloader** [comment]
> Please add support for C++ Builder ...

We don't have access to the compiler or IDE. Several years ago I wrote to Embarcadero and asked for a free license for testing and support of their tools. The company did not provide one.

At this point in time we have to wait for Borland users to provide the patches.

**Comment by tracer1808** [comment]
Now there is a free Community Edition of C++ Builder (10.3.3):
https://www.embarcadero.com/products/cbuilder/starter

This is the same as professional version (no technical limitations). Only the license terms are different. Although this is not the latest version, most people use it because its free.  

Also, I am Embarcadero MVP for C++ Builder and can ask product manager (David) to give you access to GetIt repository if you could provide automatic installation in the IDE. So far only LockBox is provided there that supports C++ Builder. Even better, if you would later provide non-visual components for the algorithms it would definitely win against all competition, but for now LIB/DLL would be enough.

**Comment by noloader** [comment]
If you want to move forward with testing Borland project files, take a look at bds10.zip. They were the Borland project files from 2015 or so. The project files are old, and probably need to be updated to for a semi-modern IDE.

Nowadays the Borland project will be missing Crypto++ source files, and the settings on some of the source files will need to be tweaked. For example, `rijndael_simd.cpp` will need to be added to the Borland project files, and the source file will need whatever Borland compiler option enables AES-NI.

When I update the Visual Studio solution files I use a plain old text editor. I find it works best to keep the cruft to a minimum. (Visual Studio uses XML files, and the project files suffer awful bloat when using the IDE to make changes).

Also see [BASE+SIMD](https://cryptopp.com/wiki/BASE%2BSIMD) on the Crypto++ wiki.

**Comment by tracer1808** [comment]
I tried but it seams project files are too old and need to be recreated:
"The project can not be loaded because the required personality CPlusPlusBuilder.Personality is not available."

**Comment by noloader** [comment]
Sorry to hear that @tracer1808,

Here is what I recommend. It will probably take you about 10 minutes. I'll help you with it.

1. Clone Wei's repo so you can make a pull request. That's this repo.

2. Create a Borland project. Try to use an older version that can be converted to any newer version. In Visual Studio, we use Visual Studio 2010 because that converts to any other modern version of Visual Studio.

3. Create two subprojects. Name the first "cryptest" and name the second "cryptlib". "cryptest" has the test suite, while "cryptlib" is the library. Make "cryptlib" a static lib. Don't worry about a DLL because the DLL is really a [FIPS DLL](https://www.cryptopp.com/wiki/FIPS_DLL) and that portion of the library is going away. The FIPS DLL is not a true DLL like most people think. It causes a lot of trouble because of they way it must be used. The FIPS DLL does not exist on Linux, Autotools, CMake, etc.

4. Add source files to "cryptest" and "cryptlib" subprojects. The list of source files and header files are shown below. You can get the list by running `make sources` on a Unix or Linux machine. In fact, I use it for [cryptest.nmake](https://www.cryptopp.com/wiki/Nmake) file.

5. Make "cryptest" depend upon "cryptlib". Make "cryptest" import the lib from "cryptlib".

6. Add Debug and Release to builds to the "cryptest" and "cryptlib" subprojects.

7. Debug builds get typical debug settings, including max symbols, no optimizations and preprocessor symbol `DEBUG`. Release builds get typical release settings, including typical symbols, max optimizations and preprocessor symbol `NDEBUG`.

**Comment by tracer1808** [comment]
I already tried creating a new project (static library) and adding all the files, but upon compiling there are errors in *SIMD.cpp files about "tmmintrin.h" and similar *mmintrin.h headers missing. I will try creating separate "cryptest" and "cryptlib" subproject and will let you know what happens.

Still, I would also recommend you to install C++ Builder Community Edition, at least in a virtual machine. I'm sure you know this library the best and would be much faster to sort any problems out.

**Comment by noloader** [comment]
`<tmmintrin.h>` is the header required for SSSE3 intrinsics. See the the [Intel Intrinsics Guide](https://software.intel.com/sites/landingpage/IntrinsicsGuide).

Once the header is available, you may need a compiler option to enable the Instruction Set Architecture (ISA). I cannot find compiler options for the compiler at docwiki.embarcadero.com/RADStudio/Sydney/ .

Do you know if a compiler option is needed for SSE2, SSSE3, SSE4.1, SSE4.2, AVX, AVX2, AESNI, SHA, RDRAND and RDSEED?

**Comment by tracer1808** [comment]
First, I was unable to find the following files: lsh256.cpp lsh256_avx.cpp lsh256_sse.cpp lsh512.cpp lsh512_avx.cpp lsh512_sse.cpp luc.cpp 

As I already specified, trying to compile static library project results in **[bcc32c Fatal Error] aria_simd.cpp(14): 'tmmintrin.h' file not found**

Embarcadero bought RAD Studio and now its in the ownership of Idera. They abandoned classic Borland compiler (it did not support C++11) and switched to Clang which now supports C++17.

I tried adding _-msse_, _-msse2_ and _-msse3_ parameters to compiler for SSE(2,3) support, but it reports that those arguments are not recognized. Are *simd.cpp" files really necessary? Can I remove them from the project and try without them?

**Comment by noloader** [comment]
You can remove the `*_simd.cpp` files (and related files like `*_sse.cpp`). The Borland project will be severely crippled. To the point I would advise you not to use the toolchain.

If you yank the SIMD files then add `CRYPTOPP_DISABLE_ASM` to preprocessor macros.

**Comment by tracer1808** [comment]
I have succeeded in creating static library without *_simd.cpp" files, but the test project using it fails with 5 errors:

[ilink32 Error] Error: Unresolved external '__ZTh-1144_CryptoPP@Weak@%PanamaHash$47CryptoPP@%EnumToType$18CryptoPP@ByteOrderi$i0$%%@TruncatedFinal$qpucui' referenced from D:\CRYPTOPP-CRYPTOPP_8_5_0\WIN32\DEBUG\REGTEST1.OBJ
[ilink32 Error] Error: Unresolved external '__ZTh-1144_CryptoPP@Weak@%PanamaHash$47CryptoPP@%EnumToType$18CryptoPP@ByteOrderi$i0$%%@HashMultipleBlocks$qpxuiui' referenced from D:\CRYPTOPP-CRYPTOPP_8_5_0\WIN32\DEBUG\REGTEST1.OBJ
[ilink32 Error] Error: Unresolved external '__ZTh-1144_CryptoPP@Weak@%PanamaHash$47CryptoPP@%EnumToType$18CryptoPP@ByteOrderi$i1$%%@TruncatedFinal$qpucui' referenced from D:\CRYPTOPP-CRYPTOPP_8_5_0\WIN32\DEBUG\REGTEST1.OBJ
[ilink32 Error] Error: Unresolved external '__ZTh-1144_CryptoPP@Weak@%PanamaHash$47CryptoPP@%EnumToType$18CryptoPP@ByteOrderi$i1$%%@HashMultipleBlocks$qpxuiui' referenced from D:\CRYPTOPP-CRYPTOPP_8_5_0\WIN32\DEBUG\REGTEST1.OBJ

Panama.cpp is already included in the static library. Am I missing some other file?

**Comment by noloader** [comment]
If I am parsing things correctly.... the functions:

* `CryptoPP::Weak::PanamaHash<LittleEndian>::HashMultipleBlocks`
* `CryptoPP::Weak::PanamaHash<BigEndian>::HashMultipleBlocks`
* `CryptoPP::Weak::PanamaHash<LittleEndian>::TruncatedFinal`
* `CryptoPP::Weak::PanamaHash<BigEndian>::TruncatedFinal`

are explicitly instantiated from [panama.cpp](https://github.com/weidai11/cryptopp/blob/master/panama.cpp#L522) : 520 or so:

```c++
template class Panama<BigEndian>;
template class Panama<LittleEndian>;

template class Weak::PanamaHash<BigEndian>;
template class Weak::PanamaHash<LittleEndian>;

template class PanamaCipherPolicy<BigEndian>;
template class PanamaCipherPolicy<LittleEndian>;
```

So the first thing to check for is, does the object file include the member. I don't know how to check that using the Borland toolchain.

Here's how to check it on Linux using [`nm`](https://sourceware.org/binutils/docs/binutils/nm.html):

```
$ nm -g panama.o | c++filt | grep -E 'HashMultipleBlocks|TruncatedFinal' | grep ' W '
0000000000000000 W CryptoPP::Weak::PanamaHash<CryptoPP::EnumToType<CryptoPP::ByteOrder, 0> >::TruncatedFinal(unsigned char*, unsigned long)
0000000000000000 W CryptoPP::Weak::PanamaHash<CryptoPP::EnumToType<CryptoPP::ByteOrder, 0> >::HashMultipleBlocks(unsigned int const*, unsigned long)
0000000000000000 W CryptoPP::Weak::PanamaHash<CryptoPP::EnumToType<CryptoPP::ByteOrder, 1> >::TruncatedFinal(unsigned char*, unsigned long)
0000000000000000 W CryptoPP::Weak::PanamaHash<CryptoPP::EnumToType<CryptoPP::ByteOrder, 1> >::HashMultipleBlocks(unsigned int const*, unsigned long)
00000000000000e0 W non-virtual thunk to CryptoPP::Weak::PanamaHash<CryptoPP::EnumToType<CryptoPP::ByteOrder, 0> >::TruncatedFinal(unsigned char*, unsigned long)
0000000000000030 W non-virtual thunk to CryptoPP::Weak::PanamaHash<CryptoPP::EnumToType<CryptoPP::ByteOrder, 0> >::HashMultipleBlocks(unsigned int const*, unsigned long)
00000000000000e0 W non-virtual thunk to CryptoPP::Weak::PanamaHash<CryptoPP::EnumToType<CryptoPP::ByteOrder, 1> >::TruncatedFinal(unsigned char*, unsigned long)
0000000000000030 W non-virtual thunk to CryptoPP::Weak::PanamaHash<CryptoPP::EnumToType<CryptoPP::ByteOrder, 1> >::HashMultipleBlocks(unsigned int const*, unsigned long)
```

I believe the `W` means it is a weak symbol. That's the `ld` linker's way of allowing a symbol to be external reference. If the linker does not find a non-weak reference, it will use the reference from `panama.o`. It is kind of a hack to call it weak since we expect it to be emitted in `panama.o`, but it is what it is.

If you can't figure out how to inspect archive members... One thing you may try... add the preprocessor macro `CRYPTOPP_ENABLE_NAMESPACE_WEAK=1` to the project files.

**Comment by tracer1808** [comment]
Adding `CRYPTOPP_ENABLE_NAMESPACE_WEAK=1` didn't help..

**Comment by noloader** [comment]
Well, you need to determine if the symbols are being emitted in `panama.o`, and if `panama.o` is present in the archive. If the symbols are present, you also need to determine if the symbols are public or private.

I don't know how to check these things with the Borland toolchain. Can you ask one of your contacts at Embarcadero?

What I suspect is, there's a bug in the toolchain. The symbols are present in `panama.o` and `libcryptopp.a`, but they are either (1) marked as private symbols or (2) there's a discrepancy in the mangled names used by the compiler and linker.

If you don't want to deal with the mangled names, just remove Panama source files from the library. The Panama based ciphers are included for historical purposes, but they are considered weak and wounded nowadays. You don't need them.

**Comment by tracer1808** [comment]
Yes, it seams too much work just for "historical purposes", so I removed `panama.cpp.`I am sending you [cryptlib_bds.zip](https://github.com/weidai11/cryptopp/files/6701578/cryptlib_bds.zip) with `cryptlib_bds.cbproj`file (C++ Builder static library project file). Just put the file in the same location where all other `.h` and `.cpp` files are located. Compile and that's it.

I tested this with C++ Builder 10.3.3 (Community Edition), and with the latest C++ Builder 10.4.2 and there were no errors compiling the code.

**Comment by noloader** [comment]
It sounds like things are working for you. I'm closing this ticket.

**Comment by roddypratt** [comment]
Resurrecting this, as I'm attempting to get cryptopp built with C++Builder 11 for Win 64-bit, and have just met the same template instantiation issues for PanamaHash.  I'll dig deeper and see what I can work out re SIMD, etc.  Also, because this is X64, the CPUID code will need a tweak. Hopefully will be able to provide a PR at some point!

**Comment by gzgius** [comment]
Finally I built Crypto++ version 8.8 - TBD with c++Builder 11.2.
All the tests are passed for WIN32. Here are the project files and the tests results.

[cryptopp-bds-11.2.zip](https://github.com/weidai11/cryptopp/files/9673559/cryptopp-bds-11.2.zip)

Hope it helps.

**Comment by tony2u** [comment]
Hi guys,
I found this website through Google: 
[https://github.com/abdes/cryptopp-cmake](https://github.com/abdes/cryptopp-cmake)

Using bcc32c or bcc64 as compiler, and then using cmake:
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=bcc32c.exe -DCMAKE_CXX_COMPILER=bcc32c.exe -DCMAKE_C_FLAGS="-q -tM" -DCMAKE_CXX_FLAGS="-q -tM" -DCMAKE_EXE_LINKER_FLAGS_RELEASE="-q -tC -Tpe import32.lib cw32mt.lib" -DCMAKE_SHARED_LINKER_FLAGS_RELEASE="-q -tWD -D_WINDLL -D_DLL -x -w-dup import32.lib cw32mt.lib" -G "Borland Makefiles" ..
then you can finally obtain static library and cryptest.exe.

Hope some helps.

**Comment by gzgius** [comment]
Hi there! 
You can try this new way also:
https://blogs.embarcadero.com/introducing-amazing-cmake-support-in-cbuilder-12-2/

**Comment by funkvps** [comment]
> Finally I built Crypto++ version 8.8 - TBD with c++Builder 11.2. All the tests are passed for WIN32. Here are the project files and the tests results.
> 
> [cryptopp-bds-11.2.zip](https://github.com/weidai11/cryptopp/files/9673559/cryptopp-bds-11.2.zip)
> 
> Hope it helps.

Hello, gzgius, after digging alot regarding buding cryptopp for c++ builder, I got this thread. Do you have any work version of configuration for cryptopp 8.9 + c++ builder? for both win32 and x64

Thanks

**Comment by gzgius** [comment]
> > Finally I built Crypto++ version 8.8 - TBD with c++Builder 11.2. All the tests are passed for WIN32. Here are the project files and the tests results.
> > [cryptopp-bds-11.2.zip](https://github.com/weidai11/cryptopp/files/9673559/cryptopp-bds-11.2.zip)
> > Hope it helps.
> 
> Hello, gzgius, after digging alot regarding buding cryptopp for c++ builder, I got this thread. Do you have any work version of configuration for cryptopp 8.9 + c++ builder? for both win32 and x64
> 
> Thanks

Hi funkvps!
Purtroppo ho abbandonato il progetto più di tre anni fa. Ma ora potrei provare a rilanciarlo; lo aggiungerò al mio ramo RadStudioExample here
https://github.com/gzgius/RADStudio12Demos/tree/main/CPP/CMake
and build it with cmake 
https://github.com/gzgius/RADStudio12Demos/tree/main/CPP/CMake
Thank you for your interest
