### ISSUE TITLE
Message recovery vulnerability in ElGamal

### ISSUE THREAD

**Issue by defeo** [weidai11/cryptopp#1059]
https://eprint.iacr.org/2021/923 illustrates a message recovery attack in a scenario where Crypto++ encrypts a message to ElGamal public keys generated according to different conventions than those used in Crypto++. This is an issue in interoperable scenarios, such as OpenPGP.

Concretely, ElGamal ciphertexts generated by Crypto++ have the form (g^y, h^y·M) where the bitlength of y is much shorter than that of the ElGamal modulus (see https://github.com/weidai11/cryptopp/blob/434e3189/nbtheory.cpp#L1045-L1050). The attack recovers y in cases where g generates a group of composite order N, where N = q·f₁·f₂··· with f_i small.

The fix is to change the way y is sampled during encryption: sampling y with as many bits as the modulus p prevents all attacks, and is the only safe option.

**Comment by carnil** [comment]
This issue has been assigned CVE-2021-40530

**Comment by noloader** [comment]
@mouse07410,

It looks like the suggested change is from:

```
// gfpcrypt.cpp
Integer DL_GroupParameters_IntegerBased::GetMaxExponent() const
{
	return STDMIN(GetSubgroupOrder()-1, Integer::Power2(2*DiscreteLogWorkFactor(GetFieldType()*GetModulus().BitCount())));
}
```

to:

```
// gfpcrypt.cpp
Integer DL_GroupParameters_IntegerBased::GetMaxExponent() const
{
	return GetFieldType() * (GetModulus() - 1);
}
```

What I am less clear about... Should this only apply to ElGamal, or should it apply to all ElGamal-like schemes?

Do you have any thoughts?

**Comment by mouse07410** [comment]
Offhand, I don't know. And would like to catch some of my colleagues to discuss this.

Offhand, your proposed new class looks reasonable.

**Comment by noloader** [comment]
Thanks @mouse07410.

From the paper [On the (in)security of ElGamal in OpenPGP](https://eprint.iacr.org/2021/923.pdf) that raised this issue, four configurations are analyzed. Configuration A and Configuration B are insecure due to the attack. I believe Crypto++ is using Configuration B.

Configuration C uses safe primes, and Configuration D uses Lim-Lee primes. The paper considers these configurations secure.

I don't like Lim-Lee primes because keys cannot be validated without additional information, so that strikes Configuration D. Lets go with Configuration C and the safe primes.

**Comment by noloader** [comment]
This issue should be cleared at [Commit bee8e8ca6658](https://github.com/weidai11/cryptopp/commit/bee8e8ca6658).
