### ISSUE TITLE
Need extensible way to handle Clang Integrated Assembler/LLVM Issues 18916 and 24200

### ISSUE THREAD

**Issue by noloader** [weidai11/cryptopp#11]
Issue 18916: https://llvm.org/bugs/show_bug.cgi?id=18916
Issue 24200: https://llvm.org/bugs/show_bug.cgi?id=24200

LLVM will eventually fix the 18916 issue (".intel_syntax noprefix;" and ".att_syntax prefix;"). If they fix it in a forward compatible way, then we can just leave `WORKAROUND_LLVM_BUG_18916` in effect and things will "just work". If its not a forward fix, then we can guard with a define like `CRYPTOPP_CLANG_41_OR_EARLIER` once we know when its available. So it should not be a problem either way.

The 24200 issue is going to be trickier because we need to know when to switch to fixes for Clang Integrated Assembler *in the source code* (and not the GNUmakefile). The source code is guarded with `CRYPTOPP_USING_CLANG_INTEGRATED_ASSEMBLER`, but we won't know when to activate it. 

The first problem with 24200 is the only way I am aware to determine when Clang's assembler is being used is through the compiler driver. If we get the `clang: error...` string, then its the integrated assembler.

    $ clang++ -xc -c /dev/null -Wa,-v -o/dev/null 2>&1
    clang: error: unsupported argument '-v' to option 'Wa,'

The second issue with 24200 is the Integrated Assembler can be switched off (https://stackoverflow.com/questions/11118887/how-to-switch-off-llvms-integrated-assembler), but we don't know how to test for it. Ideally, there would be a #define available, but it appears there is none. Confer, "Determine Clang Assembler versus System Assembler at compile time?", http://lists.cs.uiuc.edu/pipermail/cfe-users/2015-July/000719.html.

Maybe we will be able to test in the makefile, and then define/undefine `CRYPTOPP_USING_CLANG_INTEGRATED_ASSEMBLER` using `sed`. This way, `config.h` stays in sync with the actual build tools and settings.

**Comment by noloader** [comment]
Issue 18916: https://llvm.org/bugs/show_bug.cgi?id=18916
Issue 24200: https://llvm.org/bugs/show_bug.cgi?id=24200

LLVM will eventually fix the 18916 issue (".intel_syntax noprefix;" and ".att_syntax prefix;"). If they fix it in a forward compatible way, then we can just leave WORKAROUND_LLVM_BUG_18916 in effect and things "just work". If its not a forward fix, then we can guard with a define like CRYPTOPP_CLANG_41_OR_EARLIER once we know when its available. So it should not be a problem either way.

The 24200 issue is going to be trickier because we need to know when to switch to fixes for Clang Integrated Assembler *in the source code* (and not the GNUmakefile). The source code is guarded with CRYPTOPP_USING_CLANG_INTEGRATED_ASSEMBLER, but we won't know when to activate it. 

The first problem with 24200 is the only way I am aware to determine when Clang's assembler is being used is through the compiler driver:

    $ clang++ -xc -c /dev/null -Wa,-v -o/dev/null 2>&1
    clang: error: unsupported argument '-v' to option 'Wa,'

The second issue is the Integrated Assembler can be switched off (https://stackoverflow.com/questions/11118887/how-to-switch-off-llvms-integrated-assembler), but we don't know how to test for it. Ideally, there would be a #define available, but it appears there is none. Confer, "Determine Clang Assembler versus System Assembler at compile time?", http://lists.cs.uiuc.edu/pipermail/cfe-users/2015-July/000719.html.

Maybe we will be able to test in the makefile, and then define/undefine CRYPTOPP_USING_CLANG_INTEGRATED_ASSEMBLER using sed. This way, config.h stays in sync with the actual build settings.

**Comment by mouse07410** [comment]
FWIW, I think on Mac OS X clang always uses integrated assembler. And I'd avoid GAS in the source code as much as possible, as it has not been updated in decades.

Sent from my iPad

On Jul 22, 2015, at 04:36, Jeffrey Walton <notifications@github.com<mailto:notifications@github.com>> wrote:


Issue 18916: https://llvm.org/bugs/show_bug.cgi?id=18916
Issue 24200: https://llvm.org/bugs/show_bug.cgi?id=24200

LLVM will eventually fix the 18916 issue (".intel_syntax noprefix;" and ".att_syntax prefix;"). If they fix it in a forward compatible way, then we can just leave WORKAROUND_LLVM_BUG_18916 in effect and things "just work". If its not a forward fix, then we can guard with a define like CRYPTOPP_CLANG_41_OR_EARLIER once we know when its available. So it should not be a problem either way.

The 24200 issue is going to be trickier because we need to know when to switch to fixes for Clang Integrated Assembler in the source code (and not the GNUmakefile). The source code is guarded with CRYPTOPP_USING_CLANG_INTEGRATED_ASSEMBLER, but we won't know when to activate it.

The first problem with 24200 is the only way I am aware to determine when Clang's assembler is being used is through the compiler driver:

$ clang++ -xc -c /dev/null -Wa,-v -o/dev/null 2>&1
clang: error: unsupported argument '-v' to option 'Wa,'


The second issue is the Integrated Assembler can be switched off (https://stackoverflow.com/questions/11118887/how-to-switch-off-llvms-integrated-assembler), but we don't know how to test for it. Ideally, there would be a #define available, but it appears there is none. Confer, "Determine Clang Assembler versus System Assembler at compile time?", http://lists.cs.uiuc.edu/pipermail/cfe-users/2015-July/000719.html.

Maybe we will be able to test in the makefile, and then define/undefine CRYPTOPP_USING_CLANG_INTEGRATED_ASSEMBLER using sed. This way, config.h stays in sync with the actual build settings.

**Comment by noloader** [comment]
How does this patch look:

    $ cat GNUmakefile.diff
    diff --git a/GNUmakefile b/GNUmakefile
    index 3f48cc5..a34dcbf 100644
    --- a/GNUmakefile
    +++ b/GNUmakefile
    @@ -32,13 +32,25 @@ ifneq ($(CLANG_COMPILER),0)
     CXXFLAGS += -Wall
     endif
     
    +# Also see LLVM Bug 24200 (https://llvm.org/bugs/show_bug.cgi?id=24200)
    +CLANG_ASSEMBLER ?= $(shell $(CXX) -xc -c /dev/null -Wa,-v -o/dev/null 2>&1 | $(EGREP) -i -c "^clang")
    +
     ifeq ($(IS_X86),1)
     
     GCC42_OR_LATER = $(shell $(CXX) -v 2>&1 | $(EGREP) -i -c "^gcc version (4.[2-9]|[5-9])")
 ICC111_OR_LATER = $(shell $(CXX) --version 2>&1 | $(EGREP) -c "\(ICC\) ([2-9][0-9]|1[2-9]|11\.[1-9])")
    +
    +ifeq ($(CLANG_ASSEMBLER),0)
    +# Using system provided assembler. It may be GNU AS (GAS).
     GAS210_OR_LATER ?= $(shell $(CXX) -xc -c /dev/null -Wa,-v -o/dev/null 2>&1 | $(EGREP) -c "GNU assembler version (2\.[1-9][0-9]|[3-9])")
     GAS217_OR_LATER ?= $(shell $(CXX) -xc -c /dev/null -Wa,-v -o/dev/null 2>&1 | $(EGREP) -c "GNU assembler version (2\.1[7-9]|2\.[2-9]|[3-9])")
     GAS219_OR_LATER ?= $(shell $(CXX) -xc -c /dev/null -Wa,-v -o/dev/null 2>&1 | $(EGREP) -c "GNU assembler version (2\.19|2\.[2-9]|[3-9])")
    +else
    +# Using Clang integrated assembler
    +GAS210_OR_LATER ?= 1
    +GAS217_OR_LATER ?= 1
    +GAS219_OR_LATER ?= 1
    +endif
     
     # Enable PIC for x86_64 targets
     ifneq ($(IS_X86_64),0)

**Comment by noloader** [comment]
Also see discussion at https://groups.google.com/d/msg/cryptopp-users/NoSZc1Lz0Vs/HKSLP7cHOFAJ.

**Comment by noloader** [comment]
Cleared at check-in d2fda9b
