### ISSUE TITLE
SHA256 not working on x86_64 iPhone Simulator 

### ISSUE THREAD

**Issue by JiriHoffmann** [weidai11/cryptopp#1113]
### State the operating system and version (Ubutnu 17 x86_64, Windows 7 Professional x64, etc)
`iPhone Simulator x86_64`

Compiled on: 
`Intel Mac Pro and Intel MacBook Pro, macOS BigSur 11.6`

### State the version of the Crypto++ library (Crypto++ 7.0, Master, etc)
Crypto++ 8.6, also tried master

### State how you built the library (Makefile, Cmake, distro, etc)

```bash
IOS_SDK="iPhoneSimulator" IOS_CPU="x86_64" source setenv-ios.sh
make -f GNUmakefile-cross static
make install -f GNUmakefile-cross PREFIX="$TEMP_IOS"
```
When compiled with `iPhoneOS arm64` or even "x86_64" on Android, everything runs fine. It is just the simulator having issues.

### Clearly state the undesired behavior (and state the expected behavior)

Whenever I use SHA256 anywhere the app instantly crashes due to a bad memory access error.

```cpp
byte derived[SHA256::DIGESTSIZE];
std::string password = "password";
std::string salt = "salt";
int iterations = 1024;
std::string hashResult;
byte unused = 0;

PKCS12_PBKDF<SHA256> pbkdf;
pbkdf.DeriveKey(derived, sizeof(derived), unused,
                   reinterpret_cast<const byte *>(password.data()), password.size(),
                   reinterpret_cast<const byte *>(salt.data()), salt.size(),
                iterations, 0.0f);
```

Here is a screenshot of stack trace from Xcode
![Screen Shot 2022-03-24 at 4 29 23 PM](https://user-images.githubusercontent.com/37304278/160004881-6469b99b-546a-4d85-9155-d8e2eaebf00c.png)

#### Another example: 
Simply creating `AutoSeededRandomPool` causes the same error.

![Screen Shot 2022-03-24 at 4 33 26 PM](https://user-images.githubusercontent.com/37304278/160005473-4a5be761-18dc-44c1-8471-adb24fdeb33d.png)

Please let me know if you need more info, or you can try running the example from [react-native-cryptopp](https://github.com/JiriHoffmann/react-native-cryptopp).

**Comment by noloader** [comment]
Thanks @Jiri.

This is kind of interesting in a morbid sort of way... There should not be an error in that `memcpy` since both the source and destination exist and are fixed size.

The unexplained memory errors usually come from mixing and matching library. For example, you have one copy of the library installed at `$TEMP_IOS`, but your project is using headers from another location. Can you verify you only have one copy of the library installed on your machine?

Another problem can arise when two different components in the same app use Crypto++ _and_ each performs static linking. In this case it is best if the components link to a shared object rather than a static archive. Can you verify only one component is using Crypto++?

You might want to try opening `setenv-ios.sh` and setting `-DCRYPTOPP_DISABLE_ASM` for the simulators. I've had hit or miss luck with getting them to build correctly.

**Comment by noloader** [comment]
> You might want to try opening setenv-ios.sh and setting -DCRYPTOPP_DISABLE_ASM for the simulators. I've had hit or miss luck with getting them to build correctly.

It looks like `-DCRYPTOPP_DISABLE_ASM` is set for the simulators: https://github.com/weidai11/cryptopp/blob/master/TestScripts/setenv-ios.sh#L291. Something else is causing the issue.

**Comment by JiriHoffmann** [comment]
Thanks for the quick reply! I am trying to investigate a little bit more, but I've had luck adding the .dylib to the Xcode project so far.

> The unexplained memory errors usually come from mixing and matching library. For example, you have one copy of the library installed at `$TEMP_IOS`, but your project is using headers from another location. Can you verify you only have one copy of the library installed on your machine?

The way I have my library set up is that I use the `$TEMP_IOS` folder for compilation and then move the headers into `cpp/cryptopp` and the static lib into `cpp/ios`. After that, I add the static lib and headers into Xcode via a podspec file. I was doing it this way because originally I thought I would ship the package with pre-compiled Crypto++. This way everything would be organized neatly. That's not the case anymore, so you are right that there are some unnecessary steps but as far as I am aware it should only be linked once.

> This is kind of interesting in a morbid sort of way... There should not be an error in that `memcpy` since both the source and destination exist and are fixed size.

Right, since those hashes have fixed sizes that should not be an issue. What's interesting is that only errors out with SHA256. SHA1 works fine, SHA3 works fine, even SHA512 runs without any issues. Also it runs on a physical device perfectly fine.

> It looks like `-DCRYPTOPP_DISABLE_ASM` is set for the simulators:

Just right now as I was writing this, I figured I would take a look at the flag, the comment above it references this issue [https://github.com/weidai11/cryptopp/issues/635](https://github.com/weidai11/cryptopp/issues/635) which seems to use `-DCRYPTOPP_DISABLE_SSSE3` instead of `-DCRYPTOPP_DISABLE_ASM` so I tried swapping them out and voila... it started working! Also just removing it fixes the issue as well. You will probably have a better idea what each one of them does.

**Comment by noloader** [comment]
> issue https://github.com/weidai11/cryptopp/issues/635 which seems to use -DCRYPTOPP_DISABLE_SSSE3 instead of -DCRYPTOPP_DISABLE_ASM so I tried swapping them out and voila

Ok, so the makefile now uses `-DCRYPTOPP_DISABLE_ASM`. `-DCRYPTOPP_DISABLE_SSSE3` is part of an old strategy.

Nowadays you should use `-DCRYPTOPP_DISABLE_ASM` for simulators when building the library with the makefile and building apps with other build systems.

We switch to "no ISA" because the simulators do not need them (like SSE2, SSSE3, SSE4, AVX). Real Apple hardware does not use them, so there's no sense in testing them. In fact, a compile will usually fail if you try to enable ISAs for the simulators. I believe Apple removed most ISA support from their simulator toolchains.

**Comment by jiri** [comment]
Please be careful about using mentions in the future.

**Comment by noloader** [comment]
@Jiri,

Sorry about that. I think that's happened to me in the past, too.

**Comment by jiri** [comment]
I appreciate the sentiment, but you just mentioned me again requiring me to unsubscribe again 😅

**Comment by JiriHoffmann** [comment]
In that case, if they are not used, I don't understand why it errors out with the flag but not without it

**Comment by JiriHoffmann** [comment]
Originally I was using 8.6, then I updated to master (which is now 3 commits behind) and I just recompiled and double-checked everything. You can also see yourself.
