### ISSUE TITLE
Optimizing the test script

### ISSUE THREAD

**Issue by DevJPM** [weidai11/cryptopp#117]
According to [the wiki](https://cryptopp.com/wiki/Release_process#Executing_the_Script),

> The script takes between 3 hours to 3 days to run.

which is quite a long time-span.
I've had a quick look into the script (I'm not a script wizard :( ) and it looked like everything was executed linearly. Now most modern machines have at least 2 cores.

Can the (cryptest) script be adapted to (automatically) scale with the number of cores?

-----

Another (smaller) issue: Given an empty (recent) debian / ubuntu / fedora setup, what packages are needed to run the script? 

-----

Last question: Is the output the same, if you look at the console output versus `> file.txt`-'ing it?

**Comment by noloader** [comment]
> Can the (cryptest) script be adapted to (automatically) scale with the number of cores?

Modifying the script alone will not achieve it. That's because Bash does not have threads; see [Threads in bash?](http://stackoverflow.com/q/6156541).

If you run multiple instances of the script, then you will need to have multiple ***`cryptopp`*** directories because each script needs to build the library.

Another issue is some devices are resource constrained. They may not have enough disk space to allow multiple ***`cryptopp`*** directories. I was continually running out of space on a BeagleBoard that only had about 250 MB of storage available. The device eventually required flashing a console image.

A final issue is some devices don't have the RAM to allow multiple instances. They also lack a pagefile, so everything must remain in RAM. If it can't fit in RAM, then a process is killed by the OOM.

**Comment by DevJPM** [comment]
> If you run multiple instances of the script, then you will need to have multiple cryptopp directories because each script needs to build the library.

So the solution is to make copy and adapt the scripts by copying the config part (first 180 lines) and then splitting the build and test part over multiple directories? Fine, I'll do that one then.

-----

Just out of curiorisity, why is the script a 1.5k lines monster when it appears that everything that is different between each build is the `CXXFLAGS`, the `echo`'ed text and the enclosing condition (e.g. if "HAS-C++03" and if "HAS-C++11"). Wouldn't it be possible to put the flags, the echo texts and the conditions into a three nice arrays and be happy with ~300 lines?

**Comment by noloader** [comment]
> Another (smaller) issue: Given an empty (recent) debian / ubuntu / fedora setup, what packages are needed to run the script? 

Bash and developer tools. Bash should be present. If you are on OpenBSD, then you will probably need to install it and then change your profile to use it.

I usually install the following packages after an install on Debian or Fedora:

* build-essential
* gcc
* g++
* gdb
* make
* subversion
* git
* curl
* wget
* zip
* unzip
* emacs-nox

I think Fedora calls it ***`gcc-c++`*** rather than just ***`g++`***. If I get a package error, I just bounce between package names I have a recollection of.

**Comment by noloader** [comment]
This may help things along. Also see [“make -j 4: command not found” when invoking make from a script](http://stackoverflow.com/q/34867900) on Stack Overflow.

```
if [ "$IS_LINUX" -ne "0" ]; then
CPU=$(cat /proc/cpuinfo | grep -c '^processor')
if [ "$CPU" -gt "1" ]; then
    echo "$CPU processors, using \"$MAKE -j $CPU\""
    MAKE="$MAKE -j $CPU"
fi
fi
```

Do you want to make a Pull Request?

**Comment by noloader** [comment]
@JPM, do you want to submit a Pull Request for this?

**Comment by DevJPM** [comment]
@noloader I just tried the proposed change (I also added a check for Is_X86) on ubuntu 14.04.3 LTS (EC2).
It gave me the same error.

When removing the "" around all $MAKE 's it worked again.

**Comment by jpm** [comment]
@noloader Hey, not a big deal here, but do you mind using @DevJPM instead of @jpm when you send these messages? It's adding me to these tickets, and I have nothing to do with @DevJPM :)

**Comment by noloader** [comment]
@JPM, Sorry about that. Yes, will do.

**Comment by DevJPM** [comment]
using the modified make file yielded a correct build, taking only 1h 10min on a c4.large EC2 instance running Ubuntu 14.04.3 LTS.
[Ubuntu Build Results.zip](https://github.com/weidai11/cryptopp/files/97665/Ubuntu.Build.Results.zip)

**Comment by noloader** [comment]
> I just tried the proposed change (I also added a check for Is_X86) on ubuntu 14.04.3 LTS (EC2).
> It gave me the same error.

I wonder if we should use ***`"$MAKE"`*** with the quote, but also use ***`MAKEARGS`*** as suggested by Chepner. It seems we can't avoid touching everything.

I also thing we need the quotes on ***`"$MAKE"`*** for some platforms. I can envision some folks installing things where there's a space in the pathname, especially on MinGW or Cygwin.

If it looks like ***`"$MAKE"`*** and ***`$MAKEARGS`*** work well, then you can cancel the old PR and create a new one? Also see [How to cancel a pull request on github?](http://stackoverflow.com/q/5385567)

**Comment by noloader** [comment]
> using the modified make file yielded a correct build, taking only 1h 10min on a c4.large EC2 instance running Ubuntu 14.04.3 LTS.

Yeah, that sounds like a good improvement. It sounds like it cuts the cumulative build time to about 30% of the original.

**Comment by noloader** [comment]
Cleared at Commit a7e08c7e](http://github.com/weidai11/cryptopp/commit/a7e08c7e840eef6269f6ef190f0aadf0573448db)

**Comment by noloader** [comment]
This does produce good results on some systems. For example, a Core-i5 5th gen quad-core:

```
************************************************
************************************************
Testing started: Sat Jan 23 20:56:57 EST 2016
Testing finished: Sat Jan 23 21:53:56 EST 2016

25 configurations tested

No failures detected
No warnings detected
************************************************
************************************************
```
