### ISSUE TITLE
Support for CPU instructions for hardware-accelerated SHA

### ISSUE THREAD

**Issue by GamePad64** [weidai11/cryptopp#139]
I haven't found this in issue list. Two years ago [Intel announced new assembler instructions, that could assist computing SHA-1 and SHA-256](https://software.intel.com/en-us/articles/intel-sha-extensions). There are not much Skylake CPU's on the market, but all new Intel processors will support these instructions as well. Is there any way to support such hardware acceleration? (I am not an assembler guy, so I can't make a PR)

**Comment by DevJPM** [comment]
Skylake doesn't support the Intel SHA-Extensions.

This article[0] and Wikipedia[1] confirm this.

[0]:
http://wccftech.com/mainstream-intel-core-processors-support-avx-512-skylake-xeon/
[1]: https://en.wikipedia.org/wiki/Skylake_%28microarchitecture%29

Am 21.02.2016 um 05:24 schrieb Alexander Shishenko:

**Comment by GamePad64** [comment]
Oh, I see, thanks! So, this is not really urgent for now. Maybe, it is worth leaving this feature in a wishlist?

**Comment by noloader** [comment]
What are you guys seeing in the field?

I see a lot of ARM Neon in mobile, so I know there's a [relatively] strong case for AES and SHA on devices.

I was recently talking to Wei about VIA Padlock RNG, AES and SHA instructions. I'm almost afraid to make non-trivial changes to Rijndael because its so complicated. I'm kind of afraid of knocking something loose. The SHA files are quickly getting to the same state as Rijndael/AES.

**Comment by pavel-odintsov** [comment]
What about Intel Quick Assist acceleration cards? They has SHA instructions enabled.

**Comment by noloader** [comment]
@pavel-odintsov - For the [QuickAssist 8920 Adapter](http://www.google.com/search?q=QuickAssist+8920+Adapter), I *think* we would need engine support. We don't have that at the moment, but its on my radar. If we did have engine support, then I can't really say what else we would need since I've never worked with one.

**Comment by noloader** [comment]
@DevJPM, @denisbider, @GamePad64, @pavel-odintsov,

I added a new branch called [arm-neon](http://github.com/weidai11/cryptopp/tree/arm-neon), and tested the waters with ARMv8-a `__crc32` intrinsics. This should allow us to provided better ARM IoT devices.

I don't plan on hand tuned ARM assembly. Its challenging to say the least (more challenging than X86/X32/X64 ASM IMHO).However, I am happy to work with the intrinsics when available.

I think ARM intrinsics is a good investment of man hours because mobile phones and tablets overtook desktops and servers a few years ago based on sales numbers. We get a good ROI for the effort we put in because these devices need the help the most and they are more prevalent.

Denis, is your company building any mobile apps that would benefit?

**Comment by noloader** [comment]
I think [Intel CPUs with SHA extensions](https://en.wikipedia.org/wiki/Intel_SHA_extensions) hit the market recently. It looks like processors which support it are [Goldmont microarchitecture](http://en.wikipedia.org/wiki/Goldmont):

* Pentium J4205 (desktop)
* Pentium N4200 (mobile)
* Celeron J3455 (desktop)
* Celeron J3355 (desktop)
* Celeron N3450 (mobile)
* Celeron N3350 (mobile)

We added runtime CPU feature detection at [Commit ac01277d93636cd7](http://github.com/weidai11/cryptopp/commit/ac01277d93636cd7cb9163555e2d929c39849371).

I looked through offerings at Amazon for machines with the architecture or the processor numbers, but I did not find any available (yet). I believe HP had one laptop expected to be available in November that would meet testing needs.

**Comment by noloader** [comment]
We picked up a Celeron J3455. The commits of interest are:

* [Commit 6970ef702d8615ad, Add Intel SHA1 code generation tests](http://github.com/weidai11/cryptopp/commit/6970ef702d8615ad3a5a79b391036caf08a2de95)
* [Commit 7ab9b00f909b823f, Add Intel SHA1 extension support](http://github.com/weidai11/cryptopp/commit/7ab9b00f909b823f41abed023f40f4957e4cb20a)

**Comment by noloader** [comment]
We picked up a Celeron J3455. The commits of interest are:

* [Commit 6970ef702d8615ad, Add Intel SHA1 code generation tests](http://github.com/weidai11/cryptopp/commit/6970ef702d8615ad3a5a79b391036caf08a2de95)
* [Commit 7ab9b00f909b823f, Add Intel SHA1 extension support](http://github.com/weidai11/cryptopp/commit/7ab9b00f909b823f41abed023f40f4957e4cb20a)

SHA1 was clocking around 9.5 cycles per byte (cpb) for the straight CXX implementation. Using the SHA1 extensions, its running around 2.7 cpb.

**Comment by noloader** [comment]
We picked up a Celeron J3455. The commits of interest are:

* [Commit 6970ef702d8615ad, Add Intel SHA1 code generation tests](http://github.com/weidai11/cryptopp/commit/6970ef702d8615ad3a5a79b391036caf08a2de95)
* [Commit 7ab9b00f909b823f, Add Intel SHA1 extension support](http://github.com/weidai11/cryptopp/commit/7ab9b00f909b823f41abed023f40f4957e4cb20a)
* [Commit 315b4b0b3e7b50af, Add Intel SHA256 code generation tests](http://github.com/weidai11/cryptopp/commit/315b4b0b3e7b50afa1184a7c490a284abf2c39c1)
* [Commit cce56d3f79f73933, Add Intel SHA256 extension support](http://github.com/weidai11/cryptopp/commit/cce56d3f79f739339e17746c3c4cdcba7297483b)

SHA1 was clocking around 9.5 cycles per byte (cpb) for the straight CXX implementation. Using the SHA1 extensions, its running around 2.7 cpb. SHA256 was running around 19.5 cpb using SSE2 ASM. Using the SHA256 extensions, its running around 3.9 cpb.

I suspect the results are skewed because the Celerons use TurboBoost. However, all the measurements were taken from the same machine, so the skewing among results should be consistent.

**Comment by noloader** [comment]
Closing the report. e noWw utilize SHA acceleration for the platforms we support (Intel and ARM).

If I can get my hands on some of the other boards, like the Intel one discussed earlier, then I'd be happy to revisit.

**Comment by Katharsas** [comment]
Do you support AMD Zen SHA acceleration too?

**Comment by noloader** [comment]
> Do you support AMD Zen SHA acceleration too?

Yes. From [`cpu.cpp : 270`](https://github.com/weidai11/cryptopp/blob/master/cpu.cpp#L269):

```
else if (IsAMD(cpuid0))
{
    CRYPTOPP_CONSTANT(RDRAND_FLAG = (1 << 30))
    CRYPTOPP_CONSTANT(RDSEED_FLAG = (1 << 18))
    CRYPTOPP_CONSTANT(   ADX_FLAG = (1 << 19))
    CRYPTOPP_CONSTANT(   SHA_FLAG = (1 << 29))

    CpuId(0x80000005, 0, cpuid2);
    g_cacheLineSize = GETBYTE(cpuid2[2], 0);
    g_hasRDRAND = (cpuid1[2] /*ECX*/ & RDRAND_FLAG) != 0;

    if (cpuid0[0] /*EAX*/ >= 7)
    {
        if (CpuId(7, 0, cpuid2))
        {
            g_hasRDSEED = (cpuid2[1] /*EBX*/ & RDSEED_FLAG) != 0;
            g_hasADX = (cpuid2[1] /*EBX*/ & ADX_FLAG) != 0;
            g_hasSHA = (cpuid2[1] /*EBX*/ & SHA_FLAG) != 0;
        }
    }
}
```
