### ISSUE TITLE
SHA-3 test vector results

### ISSUE THREAD

**Issue by AndrewWPhillips** [weidai11/cryptopp#158]
I have implemented SHA-3 digest in my hex editor (https://github.com/AndrewWPhillips/HexEdit) and test vectors return the correct results according to Crypto++/TestVectors/sha3.txt. However, these results differ from others I have seen (eg  http://www.di-mgt.com.au/sha_testvectors.html) and even the result for the empty test vector on the wikipedia page (https://en.wikipedia.org/wiki/SHA-3). Am I missing something?

Also is SHA-3 to be added to the DLL? Surely if SHA-1 is FIPS 140-2 compliant then SHA-3 should be!

**Comment by noloader** [comment]
> However, these results differ from others I have seen (eg http://www.di-mgt.com.au/sha_testvectors.html) and even the result for the empty test vector on the wikipedia page (http://en.wikipedia.org/wiki/SHA-3). Am I missing something?

My guess is (and its purely a guess) is that the extended output function has something to do with it. I know Crypto++ does not use it at the moment. Also see [Pull Request 41: Updated SHA3 padding to NIST final FIPS 202 spec](http://github.com/weidai11/cryptopp/pull/41).

Looking at the test vectors, I don't see provenance for the test vectors. That's kind of unusual as there's usually a `Source` field for the provenance and a `Comment` field for the particular test.

```
$ cat TestVectors/sha3.txt 
AlgorithmType: MessageDigest
Name: SHA-3-224
Message: ""
Digest: f71837502ba8e108 37bdd8d365adb855 91895602fc552b48 b7390abd
Test: Verify
Message: "The quick brown fox jumps over the lazy dog"
Digest: 310aee6b30c47350576ac2873fa89fd190cdc488442f3ef654cf23fe
Test: Verify
Message: "The quick brown fox jumps over the lazy dog."
Digest: c59d4eaeac728671c635ff645014e2afa935bebffdb5fbd207ffdeab
Test: Verify
...
```

One of the first hits for those vectors is SuperCop, so I'm guessing its an early implementation of Keccak.

-----

> Also is SHA-3 to be added to the DLL? Surely if SHA-1 is FIPS 140-2 compliant then SHA-3 should be!

The [FIPS DLL](http://www.cryptopp.com/wiki/FIPS_DLL) is special purpose. We can only add validated algorithms to it. SHA-3 is not validated, so it can't be added at the moment.

-----

Maybe we need to add a full featured Keccak, and then a particular SHA-3 that conforms to FIPS 202.

We can't just change SHA-3 to arrive at new results because it may break existing users. Existing users need a migration path. Hence the reason we may need Keccak and an improved SHA-3.

**Comment by kinap** [comment]
The difference between the Crypto++ SHA3 implementation and FIPS 202 is how padding is handled. Crypto++ uses the original padding that was submitted, prior to finalization.

The pull request I submitted results in correct digests based on conversations I've had with the guys at NIST (a year or two ago), internal models where I work, and published test vectors. So I believe this is stable and correct, though I'd be very interested to know for sure. @AndrewWPhillips , can you try recompiling with my one line change and see if that helps?

**Comment by kinap** [comment]
This of course would be a quick fix. Moving to a Keccak based implementation would clearer and enable support for things like SHAKE.

**Comment by AndrewWPhillips** [comment]
noloader: thanks for your reply in which you said:
> We can't just change SHA-3 ...
Of course, I was thinking a defaulted c'tor parameter to control the behaviour.

kinap: Thanks, I will try it.

**Comment by AndrewWPhillips** [comment]
kinap: I found your (1 character) fix and rebuilt cryptlib.lib and I now get the expected results - great! However, I don't like using an unofficial version - so am hoping your fix is merged in somehow.

**Comment by kinap** [comment]
Great news, thanks for checking that out. @noloader Any chance this could be merged in short term until the Keccak base gets sorted out? As you mention, it could break existing users, but it does look like they would be relying on invalid digests.

**Comment by noloader** [comment]
@AndrewWPhillips, @kinap - let me fast track something since the bottom line here is we are arriving at incorrect results for new and future users.

We should not sacrifice any users, so we are still going to need to provide a migration path for existing users.

**Comment by noloader** [comment]
Also see [SHA-3 and Keccak](http://groups.google.com/forum/#!topic/cryptopp-users/miVG4k741d4) on the user list, [Commit df1c94a38a971191: Initial cut-in of CRYPTOPP_USE_FIPS_202_SHA3 macro](http://github.com/weidai11/cryptopp/commit/df1c94a38a97119198aa3ae92e82ab9e46d4e9b5) and [Issue 158: SHA-3 test vector results](http://github.com/weidai11/cryptopp/issues/158).

**Comment by noloader** [comment]
@AndrewWPhillips, @kinap - We performed three check-ins that mostly puts us where we need to be:

* Daniel's patch [Pull Request #41](http://github.com/weidai11/cryptopp/commit/62a72f9dfa986726d73541b0ee3420e3ebd0dc8b)
* [Initial cut-in of CRYPTOPP_USE_FIPS_202_SHA3 macro](https://github.com/weidai11/cryptopp/commit/df1c94a38a97119198aa3ae92e82ab9e46d4e9b5)
* [Add SHA3/FIPS 202 test vectors](http://github.com/weidai11/cryptopp/commit/01d137155ccbed6045a0ae5eb8eb02cbcaadbdca)

-----

***IF*** you want old behavior, then do nothing. Everything works as it previously worked.

***IF*** you want new behavior, then:

* Uncomment `CRYPTOPP_USE_FIPS_202_SHA3` in `config.h`
* Comment `sha3.txt` in `TestVectors/all.txt`
* Uncomment `sha3_fips_202.txt` in `TestVectors/all.txt`

**Comment by AndrewWPhillips** [comment]
Hi noloader, it's great that the fix was made. However, I would have preferred a run-time rather than compile-time fix so that I could get either value. (My original suggestion was a defaulted c'tor argument.)  I believe that checking a run-time flag (once, at the end) would have negligible performance effect.

**Comment by noloader** [comment]
@AndrewWPhillips, @kinap, @DevJPM, @mouse07410,

We are getting ready to make some changes in this area. First, we added a `Keccak` class that provides the former NIST behavior, before FIPS 202 was finalized. Second, we changed SHA3 to conform to FIPS 202. Both changes are sitting in the [Keccak dev-branch](http://github.com/weidai11/cryptopp/tree/keccak).

Related to (2), we also changed the Algorithm Name of SHA3 from the string `SHA-3-NNN` to `SHA3-NNN`. There was an extra hyphen that was less conforming.

We are still up in the air with respect to sponge functions (other than F1600) and XOFs. We don't really have an idea of how they should look at the design and implementation level for software. (I have some ideas in the back of my head). However, perfection should not be the enemy of the good, so we pulled the trigger and provided Keccak.

Nothing has changed with respect to your request for HMAC or KMAC. However, some hurdles have been cleared that should make it easier on folks.

**Comment by noloader** [comment]
@AndrewWPhillips, @kinap.

Also see [Issue 262: Need better design for Keccak](https://github.com/weidai11/cryptopp/issues/262). We're getting there slowly but surely.

**Comment by DevJPM** [comment]
@AndrewWPhillips do you _need_ to decide at run-time which padding (old or new) to use? Because if so, you should rather use good ol' pointers (with abstraction and the relevant underlying implementation as needed), because the library standard is that hash functions take _zero_ arguments. E.g. if at any point a library object instantiates a hash function (f.ex. because the class is a template parameter), it _will_ initialise without arguments and as such you'll have a hard time getting to use non-default padding, f.ex. with HMAC (there's probably other examples of this behavior as well).
