### ISSUE TITLE
Build break using MD mode under VS2015 with Update2

### ISSUE THREAD

**Issue by hcaihao** [weidai11/cryptopp#163]
Step:
1. Open cryptest.sln
2. Switch 4 projects option from MT to MD
3. Build

Get: Error LNK2005 __crt_debugger_hook already defined in MSVCRT.lib

**Comment by noloader** [comment]
Thanks @hcaihao. We have a Pull Request for the issue at [PR 154: Fixed linker error when using VS2015 /MD](http://github.com/weidai11/cryptopp/pull/151).

The PR makes me nervous because it has the propensity to disturb a lot of platforms. I want to ensure its well tested before cutting it in. We are working on a Windows test script for the PR so we can be mostly certain it does not have unwanted side effects.

**Comment by noloader** [comment]
@hcaihao,I believe this was cleared with [PR 151: Fixed linker error when using VS2015 /MD](https://github.com/weidai11/cryptopp/pull/151). Please let us know if there are any troubles.

**Comment by hcaihao** [comment]
When will new version release?
