### ISSUE TITLE
Should FileSInk::Put2 use streamsize blocks?

### ISSUE THREAD

**Issue by noloader** [weidai11/cryptopp#20]
`FileSink::Put2` (from files.cpp) uses the following. If `length` > `std::streamsize`, then only one iteration is performed and the user must retry manually.

    size_t FileSink::Put2(const byte *inString, size_t length, int messageEnd, bool blocking)
    {
	    if (!m_stream)
		    throw Err("FileSink: output stream not opened");

	    while (length > 0)
	    {
		    std::streamsize size;
		    bool safe = SafeConvert(length, size);
		    CRYPTOPP_ASSERT(safe);
		    if (!safe)
			    size = numeric_limits<std::streamsize>::max();
		    m_stream->write((const char *)inString, size);
		    inString += size;
		    length -= (size_t)size;
	    }
        ...
    }

**Comment by denisbider** [comment]
I believe this is by design. Put2 does not have to consume all bytes the user is trying to input.

**Comment by DevJPM** [comment]
The code is the new one or the old one?

Because I'd say that if length > streamsize an assert would be hit so
the user may notice it in debug builds...

Funfact: std::streamsize seems to be a signed size_t (-> 64 or 32 bit).

Anyways I'm not even sure if anyone would want to input more than 2GiB
in 32-bit as there are only 4GiB at maximum in RAM...

BR

JPM

Am 30.07.2015 um 08:32 schrieb Jeffrey Walton:

**Comment by noloader** [comment]
> I believe this is by design. Put2 does not have to consume all bytes the user is trying to input.

Yes, agreed. But I'm wondering if this is the best or optimal strategy.

**Comment by noloader** [comment]
> The code is the new one or the old one?
That's the existing code with one change: the assert was added.

> Anyways I'm not even sure if anyone would want to input more than 2GiB in 32-bit as there are only 4GiB at maximum in RAM...
Yeah, I used to feel that way. Then, a few years ago, I tried to fetch a Gentoo image that was 3.5 GB or so. I had a heck of a time finding tools to handle it.

**Comment by denisbider** [comment]
> Yes, agreed. But I'm wondering if this is the best or optimal strategy.

When you have a contract, best strategy is to follow it. If you're thinking it of not following it in a particular case, that means you want to change the contract.

There isn't much point in changing this behavior here, if the contract remains that the user must repeat Put2 until all data has been accepted.

As far as I know, the decision to not try to put all data through is informed by the observation that interweaving I/O (read/write/read/write/read/write) yields better performance than staggering it (read/read/read/write/write/write).

**Comment by noloader** [comment]
> As far as I know, the decision to not try to put all data through is informed by the observation that interweaving I/O (read/write/read/write/read/write) yields better performance than staggering it (read/read/read/write/write/write).

I think this is the crux of it: I would expect the user/caller to have a strategy; and when they say "write N", they expect N to be written.

**Comment by noloader** [comment]
> ... a few years ago, I tried to fetch a Gentoo image that was 3.5 GB or so. I had a heck of a time finding tools to handle it.

Here's one of those examples... [Index of /CentOS/5.11/isos/x86_64](http://mirrors.umflint.edu/CentOS/5.11/isos/x86_64/). I'm trying to fetch CentOS 5 for testing (it provides GCC 4.1, so it needs to be represented). The ISO is 4.4 GB.

**Comment by denisbider** [comment]
> I think this is the crux of it: I would expect the user/caller to have a strategy; and when they say "write N", they expect N to be written.

You're trying to change the contract. This involves rewriting the entire library.

**Comment by denisbider** [comment]
>  I'm trying to fetch CentOS 5 for testing (it provides GCC 4.1, so it needs to be represented). The ISO is 4.4 GB.

And you could use this class for this purpose, if you use it according to its contract.

**Comment by denisbider** [comment]
Actually, there is in fact a problem. When Put2 doesn't accept all data, one of the following must be true:

(1) More data is required. In this case, the caller can retry when they have more data. This is not the case here.

(2) The caller should use the Waitable interface, and must call GetWaitObjects() to collect one or more wait objects, in order to know when to call Put2 on the whole filter chain again.

In this case, a correct implementation of FileSink::Put2 that doesn't process all data should be either 

(A) causing its GetWaitObjects() implementation to add a wait object to WaitObjectContainer which will be signaled when more data can be accepted; or

(B) should be causing its GetWaitObjects() implementation to call WaitObjectContainer::SetNoWait().

Since none of these appear to be true, it in fact seems you are correct that there needs to be a loop to handle all data (the alternative being to implement infrastructure to trigger WaitObjectContainer::SetNoWait via a GetWaitObjects() call - which would appear to be unnecessary and a complication in this case).

**Comment by denisbider** [comment]
*Actually*... All this time I've been assuming in my replies that the following is true:

> If length > std::streamsize, then only one iteration is performed and the user must retry manually.

But after re-reading code, I cannot see why you believe this to be true. As far as I can tell, if length > numeric_limits<streamsize>::max(), then as long as SafeConvert works properly, the loop will be iterated as many times as necessary to write all input.

Can you point to the problem which would cause only one iteration to be performed?
