### ISSUE TITLE
Curve25519 support in Crypto++

### ISSUE THREAD

**Issue by lindevs** [weidai11/cryptopp#250]
Did Crypto++ library support Curve25519 ? If not, when would expected implementation?

**Comment by noloader** [comment]
This issue is roughly being tracked at [Issue 67: No safe curves are currently supported](https://github.com/weidai11/cryptopp/issues/67).

@DevJPM performed an initial assessment of the support required for additional curves like curve25519. We found there were more pain points then expected, and the changes would cut deeper than simply adding a few classes.

The "deeper cuts" is kind of par for the course with Crypto++ due to its design. When trade-offs are made, they often favor speed over simplicity or maintainability. The trade-off means its more costly in terms of development cycles to provide some implementations.

The earliest it will be available is probably Crypto++ 5.7, which is at least 6 months away. The constraining factor is spare developer cycles.

**Comment by lindevs** [comment]
Thanks for information.

**Comment by noloader** [comment]
Closing this issue. We are working it under [Issue 67](http://github.com/weidai11/cryptopp/issues/67).

JPM and I should have something in the next couple of weeks for testing.
