### ISSUE TITLE
SHA3 HMAC Support

### ISSUE THREAD

**Issue by kinap** [weidai11/cryptopp#257]
I know the Keccak [site ](http://keccak.noekeon.org/) says HMAC is not necessary for SHA3 MAC construction. However, we have an environment where SHA3 and HMAC may be combined so I hacked in support for an internally maintained fork, something I'm trying to get away from.

Before cleaning this up and submitting a PR I wanted to have a discussion on the desirability of this. I seem to remember some resistance to the idea, but can't find an Issue or a PR for it.

**Comment by noloader** [comment]
@kinap,

Email me off-list and I'll loop you in on some private emails. My email address is *noloader, gmail account*.

Also note HMAC for SHA-3 is relatively new. The idea has been around as long as the hash itself, but its been formalized recently (so things can interop). Also see [RFC 6979, Deterministic Signatures for DSA/ECDSA using SHA3?](http://www.ietf.org/mail-archive/web/saag/current/msg06894.html) on the SAAG mailing list.

**Comment by noloader** [comment]
@kinap,

We are getting ready to make some changes in this area. First, we added a `Keccak` class tht provides the former NIST behavior, before FIPS 202 was finalized. Second, we changed SHA3 to conform to FIPS 202. Both changes are sitting in the [Keccak dev-branch](http://github.com/weidai11/cryptopp/tree/keccak).

Related to (2), we also changed the Algorithm Name of SHA3 from the string `SHA-3-NNN` to `SHA3-NNN`. There was an extra hyphen that was less confirming.

We are still up in the air with respect to sponge functions (other than F1600) and XOFs. We don't really have an idea of how they should look at the design and implementation level for software. (I have some ideas in the back of my head). However, perfection should not be the enemy of the good, so we pulled the trigger and provided Keccak.

Nothing has changed with respect to your request for HMAC or KMAC. However, some hurdles have been cleared that should make it easier on folks.

**Comment by noloader** [comment]
@kinap, @AndrewWPhillips,

There's a thread on the mailing list at [Keccak dev-branch](http://groups.google.com/forum/#!topic/cryptopp-users/hhXiNXTQFEI). If you have feedback, then please provide it. There are plans to merge the Keccak branch shortly.

The imperativeness is due to the impending Crypto++ 5.6.4 release.

**Comment by noloader** [comment]
Also see [Issue 262: Need better design for Keccak](https://github.com/weidai11/cryptopp/issues/262).

**Comment by DevJPM** [comment]
Note sure if this is clear to everyone:

The issue with Keccak and HMAC is that HMAC _requires_ a block-size constant to be defined and our SHA-3 implementation can't / doesn't provide that. 
However for this sort of purpose we _could_ introduce (alongwith proper KMAC)

- the Keccak block-size to either be the size of the permutation (i.e. 1600-bits for F1600 = 200 bytes, which will slow HMAC down for the key setup significantly because it has to process one full block first) 

- or use the capacity (depends on the hash function digest-size to some degree) as the block size

- or just hard-code it to something like 32 or 64 bytes knowing that while this isn't true it doesn't hurt either and will fix all the library limitations regarding the block size

All of this of course assumes that we indeed strongly want to plug Keccak into HMAC.

**Comment by kinap** [comment]
@DevJPM I have a use case for SHA3 + HMAC and strongly request that this feature be included. 

My quick hack addressed the blocksize issue you mention and about nothing else. I'm looking at all the material @noloader sent me as well as the Keccak branch now to get up to speed.

I got the block sizes from the wiki page or the Keccak spec. I defined a CRYPTOPP_CONSTANT(BLOCKSIZE = n); where n is defined below based on hash size.

| Hash Size  | Blocksize (bytes) | Blocksize (bits) |
|------------ | :----------------: | :----------------: |
| SHA3-224 | 144                      | 1152                |
| SHA3-256 | 136                      | 1088                |
| SHA3-384 | 104                      | 832                  |
| SHA3-512 | 76                        | 576                  |

**Comment by DevJPM** [comment]
OK, after writing the above (and not modifying it because the email notifications wouldn't get an update),

I've done some further research and talked to some people and the general consensus was that @kinap 's values are right for a couple of reasons:

- they're the ones defined by the authors themselves (also notably in the submission paper, section 5.1.1, [PDF](http://keccak.noekeon.org/Keccak-submission-3.pdf)

> For the four SHA-3 candidates where the digest length is fixed, the input block length
>is assumed to be the bitrate _r_ and the output length is the digest length of the candidate

where the bitrate is the permutation size (1600 bits / 200 bytes) - capacity (2x digest size for SHA-3 / Keccak).

- The block size is intended to show how much data must be fed in, until a new compression is triggered, in this case a new permutation, which is _exactly_ the bitrate, as the other sub-part of the permutation is specified by the capacity in size. For Keccak, the capacity was generally chosen such that it is at least twice as large as the digest length

So my recommendation: Let's do 5.6.4 first (properly) and right after it, patch a 
```
CRYPTOPP_CONSTANT(BLOCKSIZE = 200 - 2 * DIGESTSIZE)
CRYPTOPP_COMPILE_ASSERT(BLOCKSIZE > DIGESTSIZE); // make sure a digest-sized key in HMAC actually doesn't trigger yet another hash call
CRYPTOPP_COMPILE_ASSERT(BLOCKSIZE < 200); // BLOCKSIZE is an unsigned int, it can't be <0, thus it'd wrap around and be waaaaay to big, if the digest size would be too large, use strict smaller than because 200 byte bitrate (=BLOCKSIZE) would make no sense, as this has quite literally zero security
```

Also see [CodesInChaos'](https://crypto.stackexchange.com/a/39887/23623) and [Thomas Pornins](https://crypto.stackexchange.com/a/39886/23623) answer over on Cryptography Stackexchange on the subject

**Comment by noloader** [comment]
@DevJPM,

So I'm clear... You want these added now, before the impending release. Is that correct?

> So my recommendation: Let's do 5.6.4 first (properly) ...
> 
> ```
> CRYPTOPP_CONSTANT(BLOCKSIZE = 200 - 2 * DIGESTSIZE)
> CRYPTOPP_COMPILE_ASSERT(BLOCKSIZE > DIGESTSIZE);
> CRYPTOPP_COMPILE_ASSERT(BLOCKSIZE < 200);
> ```
> 

I should be able to perform a quick testing pass. But before I do it, I want to ensure that's what you want.

**Comment by DevJPM** [comment]
@noloader NO! I strongly recommend against cutting such a change in, this shortly before a major release!

What I meant was: 1) do 5.6.4 first. 2) When 5.6.4 is out, then (as one of the first additions) add these lines.

(Good that you asked)

As for their location,
I'll do a quick PR after 5.6.4 is out (if you want me to) and I'm gonna put them into Keccak and SHA3 (people will expect both to run with HMAC), as for the visibility, I think the compile asserts are usually placed in `private:` visibility and the constant _needs_ to be placed in `public:` visibility.

**Comment by noloader** [comment]
@DevJPM,

> NO! I strongly recommend against cutting such a change in ...

ACK, thanks.

**Comment by noloader** [comment]
@DevJPM, @kinap 

This just made my radar: [SP 800-185, SHA-3 Derived Functions: cSHAKE, KMAC, TupleHash and ParallelHash](http://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-185.pdf). It looks like it published in December. Since its a final version, we should be able to get our hands on test vectors from the CAVP.

**Comment by verdult** [comment]
@Kinap 

Not sure if this is still relevant, but you made a small typo in your table. I'm almost sure you meant 576 / 8 = 72 (in stead of 76).

Hash Size | Blocksize (bytes) | Blocksize (bits)
-- | -- | --
SHA3-512 | **72** <== | 576

**Comment by kinap** [comment]
@verdult You're correct, thanks for catching that. I've updated my comment above.
