### ISSUE TITLE
Call for testers and spare cycles?

### ISSUE THREAD

**Issue by anonimal** [weidai11/cryptopp#317]
From https://github.com/weidai11/cryptopp/issues/178#issuecomment-227894209

>By the way, Crypto++ violates separation of concerns because it lacks a good separation between development, testing and release. We need more volunteers with more spare cycles.

I don't see anything in the readme nor in any open issue for a "community request" for testers or spare cycles. I also don't see any details noted in a contributing guide for any curious visitors wishing to contribute.

Is there a way to formalize a community request? Is there already such a request in place? As an open source project, is such a request inherently implied (if so, should this issue be closed)?

**Comment by noloader** [comment]
> I don't see anything in the readme

I'v read my share of README's and INSTALL's, and I don't think I've ever seen a *"call for testers"* in them.

-----

> nor in any open issue for a "community request"

Ditto...

-----

> I also don't see any details noted in a contributing guide for any curious visitors wishing to contribute.

Yeah, there's nothing formal, if I recall. The home page has a topic on ***Source Code and Contributions***, but it lacks the most used path: make a Pull Request.

I also seem to recall someone else asked about a contributing guide. Its low priority on my list, but its not obvious why. Its been my experience others use the contributing guides to place barriers and avoid contributions. I roll the other way: I'm happy to take anything useful, and I'm not going to squabble over petty or useless details. If you have something, then present it.

------

> Is there a way to formalize a community request? Is there already such a request in place? As an open source project, is such a request inherently implied?

What, exactly, do you want?

**Comment by anonimal** [comment]
>I don't see anything in the readme
>nor in any open issue for a "community request"
>What, exactly, do you want?

Two things:

1. To know if these are general complaints or actionable items:
>By the way, Crypto++ violates separation of concerns because it lacks a good separation between development, testing and release. We need more volunteers with more spare cycles.

2. If not general complaints, and though crypto++ has a list of supported systems, to know if there are specific systems that the crypto++ community can't easily or regularly get their hands on for testing, or if specific roles are sought from volunteers instead of "general purpose PR's". If so, then I think someone should somehow indicate this somewhere so that point 1. is resolved.

**Comment by noloader** [comment]
Violating *separation of concerns* is a big problem as far as processes and procedures go. Right now, I am active on both sides of the fence - I develop and I test. Its not by choice since I welcome some help. The problem seems to be there are no folks available with the spare cycles.

Ideally, (1) I would develop and someone else would test; or (2) someone else would develop and I would test. We don't really have that. Our other option is (3) halt development until personnel are available. Obviously, we don't entertain the third option.

Folks like Uri, Denis and JPM help when they can, but we need a more disciplined approach. We also have the occasional transient help, where someone files a bug report and sticks around long enough to test what they are concerned about.

To compensate for lack of personnel, I run thought experiments wearing a tester's hat. I try to clear my head of the dev and then ask, *"how would I break this library as a user"*. I then write test cases and add test scripts. Checkout `cryptest.nmake` and the `TestScripts/` directory.

-----

> specific systems ... can't easily or regularly get their hands on for testing ...

The two that give me the most problem at the moment:

* Solaris 10 and below; and non-Intel Solaris (like UltraSPARC)
* Windows Phone and Windows Store (both Windows 8 and Windows 10 versions)

You will also see posts to the User List as I need something commented or tested. Here's a few recent examples from the last two weeks. Nearly all of them will go unacknowledged.

* [Issue 318: Remove dependencies on WINVER and _WIN32_WINNT](https://groups.google.com/forum/#!topic/cryptopp-users/vmKIZi8FQH8)
* [Need Microsoft x64 code profiled](https://groups.google.com/forum/#!topic/cryptopp-users/YFduzOIePSc)
* [MSC compiler Memory Leaks](https://groups.google.com/forum/#!topic/cryptopp-users/6l_JKRNo-So)
* [Please test Master](https://groups.google.com/forum/#!topic/cryptopp-users/3YaomWyy_VE)
* [Please test the AES dev-branch](https://groups.google.com/forum/#!topic/cryptopp-users/GcXEPZCYPoA)

I've learned to *not* wait too long while {waiting|hoping} for responses. If there are no responses then I continue moving forward.

**Comment by MarcelRaad** [comment]
@noloader I'd love to help testing, and I can also test for Windows Store and Phone, but would need more time. I often see your "branch has been reintegrated" messages right before I could start testing it IIRC, you often write the "please test..." messages on Fridays and most of the time I don't have a stable development environment at home (at home I always use the latest Visual Studio pre-release and most of the time something is broken).

**Comment by anonimal** [comment]
@noloader thank you explaining, I think I completely understand now.

From a project management perspective, have you considered creating a channel on [OFTC](https://www.oftc.net/) and/or creating a [Slack](https://slack.com/) account? From a point-of-contact perspective, I've seen the benefits of doing both (or, at the very least, IRC). Personally, I know that I'll be able to idle an IRC channel and respond far quicker than by mailing list (and prefer IRC over mailing list, but that's just me).

Fortunately, for those branch-related requests, I'd be able to run 24x7 instances of [kovri](https://github.com/monero-project/kovri) - which relies heavily on cryptopp. Unfortunately, until I get the armv7/8 and win builds online, I'm stuck with only i686/amd64 (Solaris/SPARC is currently unsupported). As I'm not a windows developer, I'd have to wait until other issues and priorities are satisfied before testing with MSVC.

I agree with @MarcelRaad, now seeing the mailing list and wanting to test those branches, I don't know if they still need testing (and branch `aes` no longer exists, afaict).

As for the *discipline* side of things, I keep mentioning a contributing guide; but does no one like the idea? If *something* is codified, nearly any passer-by would see something tangible and possibly do-able within their realm of experience (e.g., not everyone needs to be a seasoned developer to test).

**Comment by noloader** [comment]
We added a top-level menu item for *Contributions* on the [home page](). It is [anchored to the following text](http://cryptopp.com/#contributions):

> Contributions of all types are welcomed. Contributions include the following.
> 
> * Bug fixes
> * Features and enhancements
> * Test scripts and test cases
> * Branch and release testing
> * Documentation and updates 
> 
> If you think you have found a bug in the library, then you should discuss it on the Users mailing list. Discussing it will help bring the issue to the attention of folks who can help resolve the issue. If you want to contribute a bug fix to the library, then make a Pull Request or make a Diff available somewhere. Also see Bug Reports on the wiki.
> 
> Features and enhancements are welcomend additions to the library. This category tends to be time consuming because algorithms and their test cases need to be reviewed and merged. Please be mindful of the test cases, and attempt to procure them from an independent source.
> 
> The library cherishes test scripts and test cases. They ensure the library is fit and they help uncover issues with the library before users experience them. If you have some time, then write some test cases, especially the ones that are intended to break things.
> 
> Branch and release testing is your chance to ensure Master (and planned merges) meets your expectations and perform as expected. If you have a few spare cycles, then please test Master on your favorite platform. We need more testing on MinGW, Windows Phone, Windows Store, Solaris 10 (and below), and modern iOS and OS X (including TV and Watch builds).
> 
> Documentation and updates includes both the inline source code annotations using Doxygen, and the online information providd in the wiki. Besides testing, documentation is one of the highest returns on investment.
> 
>

**Comment by anonimal** [comment]
Looks great, thanks.

My two cents: if this was *also* in the repo instead of just the bottom of the frontpage, it may garner more attention (and maybe the right kind of attention).

**Comment by noloader** [comment]
Also see [Commit c87d7bf2cd5af2b3, *Add "Source Code and Contributing" section to Readme.txt*](http://github.com/weidai11/cryptopp/commit/c87d7bf2cd5af2b3eaf26a6b24679d5156d20d9c).

**Comment by anonimal** [comment]
Ah, perfect, thank you @noloader.
