### ISSUE TITLE
CryptoPP::memcpy_s has not been declared

### ISSUE THREAD

**Issue by whitebarin** [weidai11/cryptopp#319]
Hello! I'm get last version from git. When compile (Qt 5.5.1 (mingw492_32)) there is next error
file: validat1.cpp CryptoPP::memcpy_s has not been declared.
When i change to (coment  //	using CryptoPP::memcpy_s;) ALL COMPILED OK!! ALL TESTES PASSED!!

my changes in file: validat1.cpp is

```
//#if defined(__MINGW32__)
//	using CryptoPP::memcpy_s;
//#endif 
```

See issue http://github.com/weidai11/cryptopp/issues/28

**Comment by noloader** [comment]
`CryptoPP::memcpy_s` is in `misc.h`. You might try including `misc.h` in `validat1.cpp`.

I don't believe we should perform the change suggested above for MinGW because its an abandoned platform. If we do that, then we will break a platform that's being actively maintained.

I hesitate to suggest it, but you might consider using something other than MinGW. I don't like telling folks what they should or should not do, so my apologies for bringing it up. But in this case there's not much we can do for you because the MinGW folks walked away.

**Comment by noloader** [comment]
We added the header `"misc.h"` to `validat1.cpp`. I hope that will clear it but I can't say for certain. I've had a heck of a time with MinGW. I had one working installation that eventually broke.

Also see [Commit c621ce053298fafc](http://github.com/weidai11/cryptopp/commit/c621ce053298fafc1e59191079c33acd76045c26).

**Comment by whitebarin** [comment]
Thanks, but it is not work. I am recomended )))
//#if defined(__MINGW32__)
//	using CryptoPP::memcpy_s;
//#endif

i made it an it's work
Thanks

**Comment by noloader** [comment]
@whitebarin,

We added `using CryptoPP::memcpy_s` for MinGW-64. Also see [Issue 28, Comment 154374956](http://github.com/weidai11/cryptopp/issues/28#issuecomment-154374956). I don't want to sacrifice MinGW-64 for MinGW-32 because MinGW-64 is actively maintained while MinGW-32 is abandoned.

According to [How can I detect g++ and MinGW in C++ preprocessor?](http://stackoverflow.com/a/17493828/608639), you may be able to perform the following. Can you try it?

```
// validat1.cpp

#if defined(__MINGW64__)
using CryptoPP::memcpy_s;
#endif
```

Notify folks who use MinGW-64 to ensure we don't break them: @Liberus , @IlyaBizyaev, @Zireael-N.

**Comment by noloader** [comment]
@whitebarin,

I'm closing the issue. Breaking an active platform for an abandoned one is not acceptable.

If you have time in the future to troubleshoot and test suggestions, then I'd b happy to revisit it.

**Comment by whitebarin** [comment]
offcource this is good idea,
i am try it - IT'S WORK!

// validat1.cpp

#if defined(__MINGW64__)
using CryptoPP::memcpy_s;
#endif

**Comment by whitebarin** [comment]
#if defined(__MINGW64__)
using CryptoPP::memcpy_s;
#endif

**Comment by noloader** [comment]
Also see [Need a potential changes tested on MinGW-64](http://groups.google.com/forum/#!topic/cryptopp-users/PRTVKTh0gRk) on the mailing list. if there are no objections, then we will merge Trungantran's suggestion.

**Comment by noloader** [comment]
Cleared at [Commit 51d3cc945fe388c7](http://github.com/weidai11/cryptopp/commit/51d3cc945fe388c776a1a20683ba8ff1c2f191e2).

**Comment by noloader** [comment]
Cleared at [Commit 51d3cc945fe388c7](http://github.com/weidai11/cryptopp/commit/51d3cc945fe388c776a1a20683ba8ff1c2f191e2).
