### ISSUE TITLE
Support split of build optional components and install optional components

### ISSUE THREAD

**Issue by alonbl** [weidai11/cryptopp#327]
Hi,

This applies to both the cmake and proprietary build systems.

When enabling tests the tests are both built and installed.
When enabling tests but disabling static library build fails.
When enabling tests and shared, which derived enabling static, installation install all while in many cases only the shared library is required.

The proprietary build system takes one step farther by auto detecting the file during installation, so if once built and not cleaned files are installed regardless of the options.

I suggest to have the following logic explicitly to what we want to be installed:
1. INSTALL_SHARED triggers BUILD_SHARED
2. INSTALL_STATIC triggers BUILD_STATIC
3. INSTALL_TESTS triggers BUILD_TESTS
4. BUILD_TESTS triggers BUILD_STATIC

This will allow installing only shared library but be able to execute make check, or install only shared and static and able to execute make check.

What do you think? I can probably arrange a patch if this is acceptable.

**Comment by alonbl** [comment]
BTW: if tests are going to be installed, it is probably wise to use shared library.

**Comment by noloader** [comment]
> BTW: if tests are going to be installed, it is probably wise to use shared library.

Please forgive my ignorance... Why is that?

**Comment by alonbl** [comment]
>> BTW: if tests are going to be installed, it is probably wise to use shared library.
> Please forgive my ignorance... Why is that?

Oh... just to avoid duplication? if one installs shared library why tests cannot use it and avoid bloat executable? Just an idea... :)

**Comment by noloader** [comment]
> When enabling tests the tests are both built and installed.

Yes, by design. But see the additional information from *"disabling static"* below.

-----

> When enabling tests but disabling static library build fails.

Expected, but maybe (un)expected. The recipe for `cryptest.exe` is (http://github.com/weidai11/cryptopp/blob/master/GNUmakefile#L642):

```
cryptest.exe: libcryptopp.a $(TESTOBJS)
    $(CXX) -o $@ $(CXXFLAGS) $(TESTOBJS) ./libcryptopp.a $(LDFLAGS) $(LDLIBS)
```

The recipe always builds static, and then links to static to avoid DLL/shared object injection attacks. It also avoids troubles from `-Wl,rpath`, `LD_LIBRARY_PATH`, `DYLD_LIBRARY_PATH` and friends.

Also see [Cheating the ELF](https://grugq.github.io/docs/subversiveld.pdf) and [Breaking the links: Exploiting the linker](https://www.nth-dimension.org.uk/pub/BTL.pdf). We avoid the risk out of the box. You are free to use the shared object, but you have to accept the risk.

-----

> When enabling tests and shared, which derived enabling static, installation install all while in many cases only the shared library is required.

Yes, the makefile's `make install` recipe installs the artifacts it finds. I'm not sure what CMake does.

Here's the list of artifacts it looks for:

* cryptest.exe
* libcryptopp.a
* libcryptopp.so
* libcryptopp.so.&lt;version&gt;
* libcryptopp.dylib

*IF* you want to avoid the static library, then delete `libcryptopp.a` before running `make install`.

**Comment by alonbl** [comment]
Hi,

I fail to understand the risks for testing I am more concerned about risks of actual programs, but let's assume these exists.
Static linkage introduce a different plain of risks - a fix in a library must trigger rebuild of all programs, this is much more severe issue in my opinion, and you will be able to see that no static libraries are actually used in any distribution these days.

In any case we allow building/installing both static and dynamic, so issue is void.

However, this bug is not about that... the bug is exactly about:
> IF you want to avoid the static library, then delete libcryptopp.a before running make install.

Downstream maintainer (or any developer) should not hack package build system to understand these what-ifs, the build system must cooperate with the use cases of what to install and what to build, just like any other well behaved packages you probably know.

If I ask not to build static but do wish to build tests, I should not care if you choose to linkage your tests as static or dynamic, build should work by enabling the specific options required. If I do not wish to install tests, I should not be surprised that static libraries are installed.

These concepts are important so that if upstream modifies build system the chance that it affect the downstream build is minimal.

In cmake it will be easier (in autotools even more), but also in your proprietary build it is possible, for example:

make INSTALL_TESTS=1 INSTALL_STATIC=0 INSTALL_SHARED=1
```
BUILD_STATIC ?= 0
BUILD_TESTS ?= 0
INSTALL_TESTS ?= 0
INSTALL_STATIC ?= 1
INSTALL_SHARED ?= 0

ifneq ($(INSTALL_STATIC),0)
BUILD_STATIC = 1
endif

ifneq ($(INSTALL_TESTS),0)
BUILD_TESTS = 1
endif

ifneq ($(BUILD_TESTS),0)
BUILD_STATIC = 1
endif

all:	\
	build-static \
	build-shared \
	build-tests \
	$(NULL)

.PHONY: build-static
build-static:
ifneq ($(BUILD_STATIC),0)
	@echo building static
endif

.PHONY: build-shared
build-shared:
ifneq ($(BUILD_SHARED),0)
	@echo building shared
endif

.PHONY: build-tests
build-tests:
ifneq ($(BUILD_TESTS),0)
	@echo bulding tests
endif

install:	all
ifneq ($(INSTALL_STATIC),0)
	@echo installing static
endif
ifneq ($(INSTALL_SHARED),0)
	@echo installing shared
endif
ifneq ($(INSTALL_TESTS),0)
	@echo installing tests
endif
```

Please consider to adopt as it is fairly trivial and removes the heuristics. As I wrote I can help farther, but I believe that adding a configure stage to the build system will make this set of issues much easier to solve.

Thanks!

**Comment by noloader** [comment]
> Downstream maintainer (or any developer) should not hack package build system to understand these what-ifs, the build system must cooperate with the use cases of what to install and what to build, just like any other well behaved packages you probably know.

Right. Crypto++ considers the two artifacts of interest the static library (`libcryptopp.a`) and the test harness (`cryptest.exe`).  They are the "core" and they should not be disgorged.

The dynamic library exists because distros were building it on their own. We don't really consider it part of the core. We create it and test it to help the distros.

You should install the static library in addition to the dynamic library. If you don't want to, then I guess that's OK too. Just delete in your scripts before you perform the `make install`.

**Comment by alonbl** [comment]
> You should install the static library in addition to the dynamic library. If you don't want to, then I guess that's OK too. Just delete in your scripts before you perform the make install.

I clearly showed you the security issue with static linkage, but let's ignore that for now.

I provided simple Makefile template to support this sequence without hacking the build, any reason why not to provide proper Makefile that logically do what requested as in most well behaved projects out there?

I have the feeling that crypto++ is re-inventing the wheel in many aspects of build and usage, I can help you to understand what are the best practices if you are opened for that.

**Comment by noloader** [comment]
@alonbl,

> I provided simple Makefile template to support this sequence without hacking the build ...

If you run `make sources`, then the recipe will provide the sources for the library and test program:

```
$ make sources
Library sources: cryptlib.cpp cpu.cpp integer.cpp wake.cpp shacal2.cpp md5.cpp g
f2n.cpp oaep.cpp polynomi.cpp default.cpp rijndael.cpp wait.cpp base32.cpp shark
.cpp marss.cpp safer.cpp iterhash.cpp adler32.cpp elgamal.cpp ecp.cpp fips140.cp
p esign.cpp crc.cpp algparam.cpp dessp.cpp luc.cpp eax.cpp blake2.cpp xtrcrypt.c
pp camellia.cpp emsa2.cpp md4.cpp socketft.cpp queue.cpp idea.cpp des.cpp xtr.cp
p authenc.cpp pkcspad.cpp cmac.cpp gf256.cpp mars.cpp rc5.cpp nbtheory.cpp hrtim
er.cpp hex.cpp tiger.cpp dsa.cpp eprecomp.cpp misc.cpp gzip.cpp seal.cpp files.c
pp blowfish.cpp sosemanuk.cpp randpool.cpp vmac.cpp hmac.cpp ida.cpp arc4.cpp sh
a.cpp zlib.cpp osrng.cpp skipjack.cpp sharkbox.cpp zdeflate.cpp seed.cpp sha3.cp
p rc2.cpp md2.cpp filters.cpp keccak.cpp panama.cpp network.cpp 3way.cpp twofish
.cpp rw.cpp rsa.cpp rdrand.cpp cbcmac.cpp rdtables.cpp rabin.cpp tftables.cpp mo
des.cpp whrlpool.cpp strciphr.cpp zinflate.cpp gost.cpp gfpcrypt.cpp casts.cpp d
ll.cpp ec2n.cpp tea.cpp blumshub.cpp rng.cpp gcm.cpp basecode.cpp rc6.cpp dh2.cp
p mqueue.cpp algebra.cpp square.cpp channels.cpp squaretb.cpp cast.cpp asn.cpp c
hacha.cpp bfinit.cpp pssr.cpp dh.cpp ccm.cpp mqv.cpp tigertab.cpp gf2_32.cpp sal
sa.cpp trdlocal.cpp pubkey.cpp ripemd.cpp eccrypto.cpp serpent.cpp base64.cpp tt
mac.cpp

Test sources: test.cpp bench1.cpp bench2.cpp validat1.cpp validat2.cpp validat3.
cpp adhoc.cpp datatest.cpp regtest.cpp fipsalgt.cpp dlltest.cpp
```

Perhpas you can use it as a starting point for what you need for Gentoo.

**Comment by alonbl** [comment]
> Perhpas you can use it as a starting point for what you need for Gentoo.

I do not understand, do you suggest Gentoo will fork the build system? How
can that make any sense?

We maintain so many packages imagine we had to do this for each.

Why can't this package use best practices like any other package? what so
special in crypto++ that it cannot deliver proper build system?

**Comment by noloader** [comment]
> I do not understand, do you suggest Gentoo will fork the build system?

No. I'm simply suggesting you should seek something more amicable since the GNUmakefile does not appear to suite your needs.

You are free to do whatever you like. If you want to fork the build system, then feel free to do so. If you want to replace `config.h`, then feel free to do so. We are not going to stop you.

> How can that make any sense?

If it meets your requirements, then I call it a win.

> Why can't this package use best practices like any other package?

I have no idea what the best practice you are referring to. We provide a GNUmakefile with standard targets and recipes. It honors your build environment and `CXXFLAGS`. Running the makefile builds the library and test program.

I've never heard anyone refer to a GNUmakefile that honors user flags and provides GNU targets as "non-standard" or "proprietary" until these threads came along.

> what so special in crypto++ that it cannot deliver proper build system?

I don't think Crypto++ is special, though I personally favor it. I don't know what proper and improper build system are, or how a GNUmakefile fails to meet the requirements. For completeness, you can find Stallman's book online at [GNU Make](http://www.gnu.org/software/make/manual/make.pdf).

**Comment by alonbl** [comment]
Hi,

I will not invest the resources in order to fix this package by forking it,
it does not seem you understand the role of the build system. A build
system is not a technology (aka make file) it is much more, unfortunately,
it seems that you have not use many packages to gain experience, I tried to
communicate the most trivial hints and even those were not received.

If there will be more issues like the build optimization / runtime
optimization break I will move this package to unmaintained state and
eventually drop it as we cannot replace upstream (vs work with).

Thanks!

**Comment by noloader** [comment]
Last call for CMake patches before removing it from the library and adding it to the patch page. If you have something to add, then now is the time to do it.

Also see [Remove CMake from GitHub; add it to Patch Page on wiki?](https://groups.google.com/forum/#!topic/cryptopp-users/PKlz8-ClXOU) and [Commit 1c740b0a097aecaa](https://github.com/weidai11/cryptopp/commit/1c740b0a097aecaa66044036c0d2c54220eda5d5).
