### ISSUE TITLE
Debian Hurd, cpu.cpp and "Error: character following name is not '#'"

### ISSUE THREAD

**Issue by noloader** [weidai11/cryptopp#330]
László Böszörményi  reports the following. Crypto++ 5.6.3 was compiled eight times on Hurd without any problem. Crypto++ 5.6.4 (maybe something else meanwhile) broke Hurd support. During the compilation of cpu.cpp, the following error arises:

```
/tmp/ccOaIF5V.s: Assembler messages:
/tmp/ccOaIF5V.s:820: Error: character following name is not '#'
```

**Comment by noloader** [comment]
I believe this was introduced with this change in `config.h`:

```
// The section attribute attempts to initialize CPU flags to avoid Valgrind findings above -O1
#if (defined(__MACH__) && ((CRYPTOPP_LLVM_CLANG_VERSION >= 30600) || (CRYPTOPP_APPLE_CLANG_VERSION >= 70100) || (CRYPTOPP_GCC_VERSION >= 40300)))
	#define CRYPTOPP_SECTION_INIT __attribute__((section ("__DATA,__data")))
#elif (defined(__ELF__) && (CRYPTOPP_GCC_VERSION >= 40300))
	#define CRYPTOPP_SECTION_INIT __attribute__((section ("nocommon")))
#else
	#define CRYPTOPP_SECTION_INIT
#endif
```

`CRYPTOPP_SECTION_INIT` is later used in `cpu.cpp`:

```
bool CRYPTOPP_SECTION_INIT g_x86DetectionDone = false;
bool CRYPTOPP_SECTION_INIT g_hasMMX = false, CRYPTOPP_SECTION_INIT g_hasISSE = false ...;
```

**Comment by noloader** [comment]
We believe the issue was cleared at [Commit 84b602cc7d9a3a56](http://github.com/weidai11/cryptopp/commit/84b602cc7d9a3a56e188aed595865b27c2f9f2fc).

We have not been able to duplicate the issue due to problems with missing Debian signing keys in GNU Hurd. We can't install the necessary software, like Git.

**Comment by gcsideal** [comment]
As noted in a private email, it seems you followed the first and now outdated link from https://www.debian.org/ports/hurd/hurd-cd ; but if you use the link under 'Newer snapshots', then you can find the more up-to-date image, cd-1.iso: https://people.debian.org/~sthibault/hurd-i386/installer/cdimage/ or the newly generated ones from the weekly-1 subdirectory.
Quick howto for Hurd virtualization:
 $ wget http://people.debian.org/~sthibault/hurd-i386/installer/cdimage/cd-1.iso
 # qemu-img create hurd-install.qemu 3G
 # kvm -m 1G -drive file=hurd-install.qemu,cache=writeback -cdrom cd-1.iso
I chose text install and after the restart I had to boot first with 'Advanced options...', but otherwise it's fine. Deleted the cdrom entries from /etc/apt/sources.list to force the use of network mirror. I could install anything I wanted.
I do confirm, the patch works and Hurd compilation on Crypto++ is OK again.
