### ISSUE TITLE
5.6.4 broke ABI of Integer::Integer()

### ISSUE THREAD

**Issue by wRAR** [weidai11/cryptopp#337]
The 5.6.4 release added a new argument of type CryptoPP::ByteOrder to several constructors of type CryptoPP::Integer. This broke the ABI of the class because adding an argument to a function, even with a defualt value, changes the function signature. See https://community.kde.org/Policies/Binary_Compatibility_Issues_With_C%2B%2B for a list of what you can and what you cannot do to keep the ABI.

**Comment by noloader** [comment]
Thanks @wRAR,

Yeah, it looks like the change had unwanted side effects. Below is from our [cryptest-symbols.sh](http://github.com/weidai11/cryptopp/blob/master/TestScripts/cryptest-symbols.sh) test script. We put it in place after we were bitten, but it was too late.

```
cp TestScripts/ cryptest-symbols.sh .
./cryptest-symbols.sh
...
cryptest.exe: symbol lookup error: /home/cryptopp/cryptest.exe: undefined symbol:
CryptoPP::Integer::Integer(unsigned char const*,unsigned long, CryptoPP::Integer::Signedness)
```

Also, see [Issue 283](http://github.com/weidai11/cryptopp/issues/283#issuecomment-258721959) and the ***Distros*** portion of the [Crypto++ 5.6.5 Release Notes](https://www.cryptopp.com/release565.html). There are at least two other subtle breaks that only distros experience.

My apologies for the troubles. As I said, we now have a process in place to actively hunt for these breaks rather than waiting for bug reports from user testing on a release candidate. These problems should not occur in the future.

Is there anything we can do to help you? Or is it OK to close this report?

**Comment by wRAR** [comment]
Assuming the problem was not fixed yet, we have three options:

1. You fix the code so the symbol is there again (by adding a bunch of overloads).
2. You bump the soname.
3. We fix the code with a Debian-specific patch.

**Comment by noloader** [comment]
@wRAR,

Email me off-list at *noloader, gmail account*.

This is the fourth or fifth subtle break for distros, so I want to put an end to it once and for all. For that, I want to email the distros and make sure everyone agrees with the path. I'll also loop-in a couple of folks from Crypto++ who help lead the project.

My gut instinct is to release 5.7. It won't have much in the way of new features, but it will clear these symbol problems. W can also get counsel on what to do with 5.6.x.

**Comment by wRAR** [comment]
@noloader I am not the maintainer of the Debian package, you should contact him instead at gcs@debian.org

**Comment by noloader** [comment]
@wRAR,

We know László Böszörményi well. So I am clear... You don't want to be on the off-list conversation. Is that correct?

**Comment by wRAR** [comment]
I don't want to discuss the package fate as I'm not the maintainer. Off-list or not.

**Comment by gcsideal** [comment]
@noloader, didn't get your email, please resend if you have any patch ready.

**Comment by noloader** [comment]
@wRAR, I contacted two of the distro maintainers who help us navigate the issues that are distro-centric. We should have some feedback in the next day or two. The short of it is, we are going to do what they tell us to do.

**Comment by noloader** [comment]
@wRAR, @gcsideal,

We have a tentative patch, and its attached below. It is based on a checkout of CRYPTOPP_5_6_4. It restores the original members without tainting them with new parameters and default initialization. It then re-adds the new members with separate function bodies.

[integer.zip](https://github.com/weidai11/cryptopp/files/627749/integer.zip)

**Comment by noloader** [comment]
Cleared at [Crypto++ 6.0 release](http://www.cryptopp.com/release600.html).
