### ISSUE TITLE
CMake does not set CRYPTOPP_EXPORTS for shared build (and errors during building)

### ISSUE THREAD

**Issue by egorpugin** [weidai11/cryptopp#358]
Hi, 

I'm trying to build cryptopp with cmake (win10, msvc14 upd.3 (2015), 32 bit, cmake 3.7.1) in shared config.
But cryptopp-shared target (cryptopp-shared.dll) does not have any exports.
When I'm adding CRYPTOPP_EXPORTS definition I see the following error:
```
1>ttmac.obj : error LNK2019: unresolved external symbol "protected: 
void __thiscall CryptoPP::IteratedHashBase
<unsigned int,class CryptoPP::MessageAuthenticationCode>::PadLastBlock(unsigned int,unsigned char)"
(?PadLastBlock@?$IteratedHashBase@IVMessageAuthenticationCode@CryptoPP@@@CryptoPP@@IAEXIE@Z) 
referenced in function "public: virtual void __thiscall CryptoPP::TTMAC_Base::TruncatedFinal(unsigned char *,unsigned int)" 
(?TruncatedFinal@TTMAC_Base@CryptoPP@@UAEXPAEI@Z)
```

Could you try to check it yourself or maybe you have a solution?

I've investigated it a bit and it seems the issue is somewhere in `iterhash.h`.
https://github.com/weidai11/cryptopp/blob/master/iterhash.h#L177
Maybe issue with definitions.

**Comment by egorpugin** [comment]
> On Windows, Crypto++ can be compiled into 3 forms: a static library including all algorithms, a DLL with only FIPS Approved algorithms, and a static library with only algorithms not in the DLL.

So, the static library by default has everything?

**Comment by noloader** [comment]
> So, the static library by default has everything?

Yes, absolutely.

**Comment by egorpugin** [comment]
But still... Maybe authors of cmake build could help.
@GamePad64 Did you try shared builds on windows?

**Comment by egorpugin** [comment]
Actually I found the solution right now. 
https://github.com/weidai11/cryptopp/blob/master/iterhash.h
Replace all `CRYPTOPP_NO_VTABLE` with `CRYPTOPP_DLL CRYPTOPP_NO_VTABLE` in this file.
@noloader, I could send a PR if you're ok with that (or fix it yourself).

**Comment by noloader** [comment]
@egorpugin,

> I could send a PR if you're ok with that (or fix it yourself).

Yes, make a PR. I'll announce it on the list and ask for feedback like at [Issue 335: CMake-based Xcode build fails to build any library](https://groups.google.com/forum/#!topic/cryptopp-users/DzHhTBbRboQ).

**Comment by egorpugin** [comment]
See https://github.com/weidai11/cryptopp/pull/359

**Comment by GamePad64** [comment]
@egorpugin I have tried making shared builds on Windows, but only strictly in MSYS2 environment with MINGW32 toolchain. I have not tried MSVC builds at all. CMake-built lib (in MSYS2, and, maybe, in MSVC) contains all the symbols available, so you could use it like a simple shared library.

**Comment by HeinrichJanzing** [comment]
I've just checked this with VS2015 update 2 and I get the same result - no exported symbols in the dll. We use the static library.

**Comment by noloader** [comment]
@HeinrichJanzing,

> I've just checked this with VS2015 update 2 and I get the same result - no exported symbols in the dll. We use the static library.

Typically what happens on Windows is, you write a wrapper DLL to export routines for your app. You might export a `MyLib_GenerateRandom`, `MyLib_EncryptAndAuthenticate`, `MyLib_VerifyAndDecrypt`, etc. Also, the exported functions are often `extern C` to avoid the name mangling of C++ objects. Then, you link against the static version of the library.

*If* you want to use the FIPS DLL, then you typically have to link against the static version of the library, anyways. That's because the FIPS DLL only provides AES, SHA, CMAC and other FIPS validated routines. You only get the core FIPS validated routines, and they are the ones decorated with `CRPYTOPP_DLL`. You have to link against the static version of the library for the rest of the stuff, like `Sources`, `Sinks`, `Filters`, `Encoders`, etc. The other stuff is *not* decorated with `CRPYTOPP_DLL`. Its an awful setup.

For completeness, there's nothing anyone can do to make the FIPS DLL less painful. We might be able to tune the defines so that Windows/Cmake strictly follows the Visual Studio defines, but its still going to be awful to use. Getting the defines right are not going to change it.

**Comment by HeinrichJanzing** [comment]
@noloader It is a bit of an odd setup but at least it's clear now. Thanks.

**Comment by egorpugin** [comment]
Yes, it's very odd setup.

From wiki:

> There is no Crypto++ 5.6 or 5.7 FIPS DLL, and there likely never will be because the process is too expensive.

But why then keep such limitations (FIPS DLL) in the upstream?

**Comment by noloader** [comment]
@egorpugin 

> But why then keep such limitations (FIPS DLL) in the upstream?

I wanted to yank it out some time ago, but some folks wanted to keep it. I don't recall the reason.

The more I think about it, I think we need to document a *"Regular DLL"* somewhere.
