### ISSUE TITLE
Intialization of base64 and other decoders are not threadsafe

### ISSUE THREAD

**Issue by MxSRF** [weidai11/cryptopp#376]
In base 64 decode you will find the following code:

```
const int *Base64Decoder::GetDecodingLookupArray()
{
	static volatile bool s_initialized = false;
	static int s_array[256];

	if (!s_initialized)
	{
		InitializeDecodingLookupArray(s_array, s_stdVec, 64, false);
		s_initialized = true;
	}
	return s_array;
}
```

The function `InitializeDecodingLookupArray` may run on more than one thread concurrently which may lead to fire `CRYPTOPP_ASSERT(lookup[alphabet[i]] == -1);` in `InitializeDecodingLookupArray` line 193 of basecode.cpp (based on commit  26e2e12b6a7d4c27832bd0cf522457012d5aa7a7)

**Comment by noloader** [comment]
Thanks @MxSRF. Yeah, there's a few other places like that as well, like `HexEncoder` and `Base32Encoder`.

We can make it thread safe with the `Singleton` class, but that brings some unwanted baggage. Windows platforms are trickiest because of thread local storage, and that's what drives the design and use of the `Singleton`.

**Comment by noloader** [comment]
@MxSRF,

I was looking at the requirements to clear this issue. It looks like its going to cut deeper than I expected due to the design of the decoders.

Originally, I thought we could define the 256-element table in an anonymous namespace and have `GetDefaultDecodingLookupArray` just return it. But it looks like `InitializeDecodingLookupArray` could be doing a little more than expected. I need to write some test code and see if its OK to avoid calling `InitializeDecodingLookupArray`.

I also want to investigate if this is a problem in practice. The array is a table of PODs, so the worse case is, it gets initialized twice (or more) with the same values, and `s_initialized` is set to `true` twice (or more) That each thread does the same work is inefficient, but it does not lead to incorrect results.

**Comment by MxSRF** [comment]
Thank you for response. What we observed by chance was the assertion in `InitializeDecodingLookupArray` firing and this happened because the function was run by two concurrent threads at the same time. Depending on project settings an assertion will stop the program flow (which was the case here) and lead to 'incorrect results' here. ;) 

For our project we fixed the problem with c++11 singleton construct. I agree that a singleton adds baggage but hopefully the dedicated compiler and standard libraries will implement it as good as possible.
If CryptoPP presumes only compilers that support this C++11 feature and you are interested in the solution I can try to set it up as a pull request.

**Comment by noloader** [comment]
> Depending on project settings an assertion will stop the program flow (which was the case here) and lead to 'incorrect results' here. 

Ah crud... We're going to need to address it.

I was testing some code last week, and I think there's a small design problem with the existing class, and that's leading to some implementation pain points like this. I think the table building should be unrolled so that we have an actual table available that does not require `InitializeDecodingLookupArray `.

If a user selects the default alphabet and decoding table, then simply return our prebuilt table. If a user calls `InitializeDecodingLookupArray`, then we return the table created by the user. The small design problem is the fact that the decoding table is static data. Its OK for the default alphabet, but it means all objects get the new alphabet if `InitializeDecodingLookupArray` is called by the user. I feel like that's wrong - someone may want two or three different Base64 decoders for different standards.

Let me get back in the code and come up with a proposal. Our next release is Crypto++ 6.0, so we can change things around quite a bit.

**Comment by noloader** [comment]
@MxSRF,

We unrolled the things and provided a prebuilt table of decoder lookups for the default alphabets. Please ensure it clears the issue for you. I can take things to the next step by providing the table in a `struct`, and then using a `Singleton` reference. But I'm trying to avoid it.

Also see [Commit 0dc97f1d3a801c33](https://github.com/weidai11/cryptopp/commit/0dc97f1d3a801c33b16e746c1515f0723cf23790).
