### ISSUE TITLE
Race condition in InitializeInteger::InitializeInteger

### ISSUE THREAD

**Issue by cleeus** [weidai11/cryptopp#389]
Hello everyone,

I'm seeing valid race conditions reported by valgrind (both helgrind and drd):
```
==11362== Conflicting load by thread 2 at 0x0113e540 size 8
==11362==    at 0xXXXXXXX: CryptoPP::InitializeInteger::InitializeInteger() (integer.cpp:2874)
==11362==    by 0xXXXXXX: CryptoPP::Integer::Integer() (integer.cpp:2897)
```

The offending code seems to be a singleton-like initialization:
```
InitializeInteger::InitializeInteger()
{
	if (!g_pAssignIntToInteger)
	{
		SetFunctionPointers();
		g_pAssignIntToInteger = (CryptoPP::PAssignIntToInteger)AssignIntToInteger;
	}
}
```

The g_pAssignIntToInteger pointer is also used at algparam.h:455:
```
void AssignValue(const char *name, const std::type_info &valueType, void *pValue) const
{
	// special case for retrieving an Integer parameter when an int was passed in
	if (!(g_pAssignIntToInteger != NULL && typeid(T) == typeid(int) && g_pAssignIntToInteger(valueType, pValue, &m_value)))
	{
///... *snip*
	}
}
```

That's obviously not thread safe. Stores can be reordered/and or partial unless they are explicitly atomic. Is there some reasoning behind the unprotected use of g_pAssignIntToInteger in AssignValue?

**Comment by noloader** [comment]
Thanks @cleeus.

As far as I know, the added complexity servers two purposes. First, it allows the linker to discard `Integer` related code if public key ops are not used (with the appropriate flags, like `-ffunction-sections`, `-fdata-sections` and `-Wl,--gc-sections`). Second, it allows Integer to select an implementation at runtime based on what we know about the system and runtime environment. The implementation is the one that provides a fast add with carry (IIRC).

I've never liked that code very much. It seems like a stretch to disgorge the Integer like that (to me). Maybe we should add a compile time option like `-DCRYPTOPP_NO_INTEGER`. If defined, then it would hide the code in algorithm parameters and `AssignValue`. The linker would still be responsible for removing the dead code, but the implicit use in algorithm parameters would no longer be present. The downside is it takes user action, but `-ffunction-sections`, `-fdata-sections` and `-Wl,--gc-sections` already requires user action.

We still need to set the function pointers. That's a trickier problem for two reasons. First, we want a fast integer. While the older cpu (P4) vs newer cpu (Core i5) use case does not seem applicable nowadays, there's a new use case: ADX. ADX supplements ADC, and it allows us to pipeline two additions with carry by using both the Overflow and Carry flags.

Second, initializing the pointer on some Windows systems is a pain point. The Windows systems are early XP and Server 2003, and the pain point is thread local storage (TLS). Sadly, C++11 did not fix the problem (confer, [Issue 372, Singleton::Ref() crashes on MSVC11/12](https://github.com/weidai11/cryptopp/issues/372) and [Issue 373, Loader lock on WinXP](https://github.com/weidai11/cryptopp/issues/373)).

The only thing that happened when Microsoft abandoned the platform was harming Microsoft users and making more work for us. Users are still using the OSes despite Microsoft's fiat, and I'm aware users in Automotive, Financial and Medical vertical markets. I think its imperative we provide the support for the platforms.

-----

With that said, what are your thoughts? For the first use case, discarding unused symbols, does `-DCRYPTOPP_NO_INTEGER` seems reasonable?

For the second use case, I have some tricks to help avoid [Static Initialization Order Fiasco](https://www.cryptopp.com/wiki/Static_Initialization_Order_Fiasco). I actually tested something for the Integer class last year because I've been waiting for this bug report :)

**Comment by cleeus** [comment]
For the mechanism to discard symbols - I have no real opinion, but if I had the requirement to discard code from the resulting binary, I would much more like a define that fully removes code instead of having to rely on the linker (which may fail silently to do the job).

I fully recognize the need for a dynamic dispatch mechanism and the function pointers. I'd suggest a std::call_once in InitializeInteger::InitializeInteger and AlgorithmParametersTemplate<T>::AssignValue. I'm well aware of the Static Initialization Order Fiasco (btw, I like the name). In my experience, the only thing you can rely on across platforms is for static POD types to be zero initialized. This is actually enough to bootstrap a safe initialization scheme:

1. implement a call_once mechanism with a flag that is zero initialized (for the locking, a spin-lock will be needed)
2. using call_once, implement a singleton that creates a single global mutex (or whatever other locking primitives are required)
3. using the single global mutex, implement a singleton pattern for every static object

Using singleton resolves the SIOF, as the instances are initialized when needed. Accessing the singleton instances will be a bit slower then accessing a raw pointer. You probably know more about the performance requirements of AssignValue.

I'm just worried about the thread safety problem.

**Comment by noloader** [comment]
@cleeus,

Thanks again for the report. I believe we cleared the issue at [Commit 0e55f5ac7d98f3c8](https://github.com/weidai11/cryptopp/commit/0e55f5ac7d98f3c852ace7b4622f40cfa60b629f).

The 0e55f5ac commit removes the pointer and uses `CRYPTOPP_NO_ASSIGN_TO_INTEGER` to obtain the same effect. The difference is a user will have to explicitly define `CRYPTOPP_NO_ASSIGN_TO_INTEGER` rather than depending on the linker to opportunistically remove Integer code.

We also fell-back to code that used *Construct On First Use* pattern ***if*** we did not have MSVC's `init_seg(lib)` or GCC's `init_priority`. Luckily, they have been around for about as long as C++, so most systems help us help ourselves. The holdouts are Apple and Sun, and they will suffer the memory leak in case of concurrent initialization.
