### ISSUE TITLE
API/ABI changes review for Crypto++

### ISSUE THREAD

**Issue by lvc** [weidai11/cryptopp#393]
The review of API/ABI changes for Crypto++ since 5_5_2 version: https://abi-laboratory.pro/tracker/timeline/cryptopp/

The report is updated 3 times a week. Hope it will be helpful for users and maintainers of the library.

Created with the help of open-source abi-tracker tool: https://github.com/lvc/abi-tracker

Thank you.

![cryptopp-1](https://cloud.githubusercontent.com/assets/1517837/24091807/e152151c-0d63-11e7-9e7a-bd8fac004e8d.png)

![cryptopp-2](https://cloud.githubusercontent.com/assets/1517837/24091813/e59cbeec-0d63-11e7-96b9-83c05996a01b.png)

**Comment by noloader** [comment]
Thanks @lvc.

Thank you for doing this leg-work for us. We had a few ABI breaks that caused folks some trouble. This has been on my TODO list for some time. I looked at a few tools, but I did not carve out the time to perform the setups or learn how to use the tools.

We now have a new test in place that attempts to vet them since we were doing a poor job of identifying them in the past: [cryptest-symbols.sh](https://github.com/weidai11/cryptopp/blob/master/TestScripts/cryptest-symbols.sh).

When testing versions 5.6.5 with 5.6.4, I recommend you perform a `cp config.compat config.h`. It attempts to preserve (as much as possible) behavior and interfaces. I'm guessing it will make the score improve a bit.

Crypto++ 6.0 is our next release, so there will be a fair amount of planned breakage.

In a month or so, I'll close the report out to give folks time to view this report. I'll also cut it into the relevant documentation pages, like out page on QA and testing.

Thank you again.

**Comment by lvc** [comment]
Hello Jeffrey,

Fixed report for 5.6.5: https://abi-laboratory.pro/tracker/timeline/cryptopp/

Also added report for master branch.

Thank you.

![cryptopp-3](https://cloud.githubusercontent.com/assets/1517837/24141367/a881b57e-0e3c-11e7-99eb-95bf007ed1f0.png)

**Comment by elthommy** [comment]
Hi @lvc 
I just came into this page and I wanted to aks you a question.
I am maintaining an old cryptopp package and I was trying to generate an ABI report to compare 5.6.0 and 5.6.1 (yes I know, old versions :-) and I ran into an issue with abi-compliance-checker:
It fails at compilation time because of dll.h: this header causer an error when it is not included first
#error To use the DLL version of Crypto++, this file must be included before any other Crypto++ header file
But it works only if I exclude dll.h from the checks.
Did you face similar issue? It seems dll.h is also not referenced in your ABI report.
I was wondering if we can ignore it
Cheers

**Comment by noloader** [comment]
ABI reset at [Crypto++ 6.0 release](http://www.cryptopp.com/release600.html).

**Comment by noloader** [comment]
@lvc, @mouse07410, @MarcelRaad,

We release Crypto++ 6.0 last month. We reset our former ABI breaks. The commit that became Crypto++ 6.0 was [b6c6684451f9](https://github.com/weidai11/cryptopp/commit/b6c6684451f9).

We are getting ready to release Crypto++ 6.1. It is a planned rollup of Crypto++ 6.0 fixes. We would like to ensure we did not break the ABI.

@Ivc, could you perform and ABI scan for us? Crypto++ will be out long term release since it has the minor bug fixes. This should be the last release for a while.
