### ISSUE TITLE
OpenBSD (egcc/eg++): Assembler error: no such instruction

### ISSUE THREAD

**Issue by anonimal** [weidai11/cryptopp#395]
System info:
- OpenBSD 6.0 (GENERIC)
- cpu0: Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz, 3500.59 MHz
- cpu0: FPU,VME,DE,PSE,TSC,MSR,PAE,MCE,CX8,APIC,SEP,MTRR,PGE,MCA,CMOV,PAT,PSE36,CFLUSH,MMX,FXSR,SSE,SSE2,SSE3,PCLMUL,MWAIT,SSSE3,CX16,SSE4.1,SSE4.2,POPCNT,AES,XSAVE,AVX,RDRAND,NXE,LONG,LAHF,ITSC

Notes:
- Only producible with egcc/eg++ 4.9.3 (no errors with other tested compilers: clang 3.8 or gcc 4.2.1)
- `-DDISABLE_ASM=ON` reduced number of errors but the issue still remains
- **`-DDISABLE_NATIVE_ARCH=ON` patches the issue** (I imagine env exporting from cli will also work)

Build:
- Built against f502ee9218c3a090920bc1584334a3a8e3fbb043
- [Cryptopp-f502ee9-OpenBSD-build-error.CMake.log.txt](https://github.com/weidai11/cryptopp/files/856184/Cryptopp-f502ee9-OpenBSD-build-error.CMake.log.txt)
- [cryptest-result.txt](https://github.com/weidai11/cryptopp/files/856211/cryptest-result.txt)

**Comment by noloader** [comment]
Thanks @anonimal. And sorry about that.

Let me get a VM fired up for it. I think I have one somewhere.

**Comment by noloader** [comment]
@anonimal,

The case I'm not sure about is tying `DISABLE_NATIVE_ARCH` to `CRYPTOPP_DISABLE_ASM`. `CRYPTOPP_DISABLE_ASM` is intended to be the fail safe if the library's ASM is not suitable for a platform.  Similar options, like `CRYPTOPP_DISABLE_SSSE3`, are a more surgical application of `CRYPTOPP_DISABLE_ASM` for old assemblers. Another use case we are now seeing is "new" compilers with "old" platform components like GAS 2.17, and that begs `DISABLE_NATIVE_ARCH` option.

On most platforms `CRYPTOPP_DISABLE_ASM` and `DISABLE_NATIVE_ARCH` can remain separate. However, on OpenBSD, they are intertwined because of the new compiler and old GAS version.

The issue does not seem unique. Instead, it seems like an emerging trend that affects corner cases. Some time in the future, someone may run GCC 10 on hardware SSE-7 on a Ubuntu 12 platform. Or maybe it might be Clang on Windows 7 because they don't want to upgrade to Windows 10 or Windows 12.

I think that leaves two choices:

* Couple `DISABLE_NATIVE_ARCH` to `CRYPTOPP_DISABLE_ASM` - it casts an overly wide net, and affects more platforms than OpenBSD. Things "just work" but performance may suffer.
* Leave `DISABLE_NATIVE_ARCH` to `CRYPTOPP_DISABLE_ASM` uncoupled - it allows better code generation, but breaks OpenBSD/EGCC and other similar use cases. Things no longer "just work" for everyone; and OpenBSD/EGCC users must do something special.

Another option is to detect these bad configurations and set the appropriate flags, but GNU makefile is not too accommodating. Its not easy to perform logical operations like AND and OR in GNU make's language and its the reason for some of the odd looking statements. The problem is only going to get worse as we detect more bad interactions. Its the reason for this post on the user list: [Default GNUmakefile and configure.py?](https://groups.google.com/forum/#!topic/cryptopp-users/MwvdydICbUk)

What do you think the best course of action is? Do we tie `DISABLE_NATIVE_ARCH` to `CRYPTOPP_DISABLE_ASM`, or do we leave them uncoupled?

**Comment by anonimal** [comment]
>Another option is to detect these bad configurations and set the appropriate flags

>Its the reason for this post on the user list

>What do you think the best course of action is? Do we tie DISABLE_NATIVE_ARCH to CRYPTOPP_DISABLE_ASM, or do we leave them uncoupled?

I would default to your final decision because of your experience with this codebase.

Personally, I would leave them uncoupled for now and apply any temporary patch and/or documentation note, and then move forward with `configure.py` (I completely understand the issues at hand and the stresses that come with them!).

If I have future thoughts/ideas on the matter, I'll be sure to drop a line.

**Comment by noloader** [comment]
@anonimal,

Ack, thanks. We held-off on adding `DISABLE_NATIVE_ARCH` to `CRYPTOPP_DISABLE_ASM` for the moment. We can monitor it and see how things go.

Also see [Commit d865cf9e62f2a9e](https://github.com/weidai11/cryptopp/commit/d865cf9e62f2a9ecd5d1ba69f64d4b715eba6e24)

**Comment by anonimal** [comment]
Could we extend this to CMake (it's still failing with CMake)? I know it's not "officially" supported but it's what we use. Is the solution simply detecting GAS version with CMake and adjusting flags as appropriate?

**Comment by noloader** [comment]
> I know it's not "officially" supported but it's what we use. Is the solution simply detecting GAS version

Oh, OK, yes. I thought the code was there.

Do you have a patch or do you want me to take a crack at it?

**Comment by anonimal** [comment]
I would be very grateful if you could get to this first. Otherwise, I'll have time to get to it within the next day or two.

**Comment by anonimal** [comment]
Hi @noloader. Are you working on this? Tomorrow is the Kovri meeting so I'll have to work on this next week if you're not already working on it.

**Comment by anonimal** [comment]
Ping @noloader. I've spent too much time dealing with the headache of CMake anti-patterns; especially shell idioms within `COMMAND` of `execute_process`. 

Before I continue, do you plan on supporting CMake in this capacity (of #395)?
