### ISSUE TITLE
CryptoPP library file much too large 

### ISSUE THREAD

**Issue by csaundry** [weidai11/cryptopp#436]
Hi, I'm trying to use Crypto++ 5.6.5 on an embedded system that can only fit a flash file of a few MBs on it. When I compile the libcryptopp.a, it is 40MB! If I try to only compile what I need, it is still 10MB. I also found that I cannot exclude dll.cpp or fips140.cpp, even though I'm not using the DLL or fips versions.
Is there any way to make the library a few hundred kBs? 
I've already tried using -ffunction-sections and -fdata-sections and --gc-sections when compiling the code and building the library - it had no effect.

I'm using Nios II Eclipse for compiling - part of the Altera Quartus 14.1 package.

**Comment by netheril96** [comment]
Why is the size of static library of your concern? The final executable size should be the only thing that matters.

**Comment by csaundry** [comment]
I need the final executable to be less than 2MB.

**Comment by netheril96** [comment]
And what is the size of your final executable?

**Comment by noloader** [comment]
@csaundry,

> I'm trying to use Crypto++ 5.6.5 on an embedded system that can only fit a flash file of a few MBs on it.

I hate to say it, but a C++ library may not be a good choice here. The problem is C++ and its overhead, and it would likely be present in other similar libraries like Botan.

Crypto++ may mildly aggravate the situation by *not* providing `CRYPTOPP_NO_XXX` macros to explicitly disable some algorithms and code paths. I say "mildly" because it not that bad since the linker will remove unused symbols.

The only one we have at the moment is `CRYPTOPP_NO_ASSIGN_TO_INTEGER`. It was checked-in recently at [Commit 0e55f5ac7d98](https://github.com/weidai11/cryptopp/commit/0e55f5ac7d98). It should make it easier for the linker to remove unused `Integer` related code.

-----

> I also found that I cannot exclude dll.cpp or fips140.cpp, even though I'm not using the DLL or fips versions.

Yeah, I don't like that the source files are required, but its more a philosophical objection. Where the symbols come from really does not matter; and we could put the symbols in `cryptlib.cpp` instead. The files would be gone but the symbols would remain.

-----

> I've already tried using `-ffunction-sections` and `-fdata-sections` and `--gc-sections` when compiling the code and building the library - it had no effect.

The stripping does not occur at compile time. Rather, it happens during link time.

Also note that if you are building a shared object, then no symbols can be discarded because there's no way for the linker to tell which are {not} needed. If this is your use case, then build a wrapper shared object that links to `libcryptopp.a`. The linker will discard symbols not used by your wrapper shared object.

We ran some experiments before cutting-in the `make lean` makefile recipe. You can find the results at ['make lean' target?](https://groups.google.com/d/msg/cryptopp-users/SaORS7dHSZ0/xBcCGs5cEQAJ) on the mailing list. The digest of the thread is:

> ```
>   int main( int, char** ) {
> 
>     Integer j("100000000000000000000000000000000");
>     j %= 1999;
> 
>     cout << "j: " << j << endl;
> 
>     return 0;
>   }
> ```
> Then we get a significant savings:
> 
> Lean:
> ```
>   $ ls -l integer.exe
>   -rwx------  1 jwalton  staff  162012 Jan  4 13:00 integer.exe
> ```
> Normal:
> ```
>   $ ls -l integer.exe
>   -rwx------  1 jwalton  staff  2636952 Jan  4 13:02 integer.exe
> ```

-----

Like @netheril96 suggested, we need more information, like your command lines for compile and link; and the size of your binary.

**Comment by csaundry** [comment]
I tried both -Os (slower isn't a problem because the code only runs at start up) and -W1,--gc-sections during linking with the executable, and my final executable size ended up at about 5MB, which is completely acceptable.
Thanks for the help!

For those who may be looking at this to reduce their own file sizes, I also did a custom build that involved only compiling the bare minimum of files that I needed as well as those required to make the code run (like dll.cpp and fips140.cpp and the files they depend on).
