### ISSUE TITLE
amd64: OpenBSD/Clang 3.8.0 with -march=native: error: needs target feature sha

### ISSUE THREAD

**Issue by anonimal** [weidai11/cryptopp#467]
[With `-march=native`](https://github.com/weidai11/cryptopp/files/1247912/OpenBSD_cryptopp_with-native.txt).

**Comment by noloader** [comment]
OK, the problem here is `-march=native` will only enable SHA if its actually available on the hardware. I'm guessing its not being run on a machine with SHA.

The fix for [Issue 468](https://github.com/weidai11/cryptopp/issues/468) will clear this one too.

I've got the changes checked-in on my testing branch. They should hit Master in a few hours.

**Comment by anonimal** [comment]
Fix confirmed in https://github.com/noloader/cryptopp/commit/d05c5089b8485e588405dc07d464b417151f90d6 😄 Thank you.

**Comment by noloader** [comment]
Cleared at [PR 469](https://github.com/weidai11/cryptopp/pull/469).
