### ISSUE TITLE
secblock.h fails to compile in VS2010 (because it doesn't support strongly typed enums)

### ISSUE THREAD

**Issue by wyattoday** [weidai11/cryptopp#475]
In the master branch of this project (current commit as of writing this), in VS2010 secblock.h fails to compile on line 530:

```
	enum : size_type {ELEMS_MAX = A::ELEMS_MAX};
```

The reason is that VS2010 only has partial support for strongly typed enums. See: [https://msdn.microsoft.com/en-us/library/hh567368%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396](https://msdn.microsoft.com/en-us/library/hh567368%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396)

The solution is to modify the #ifdef to skip it if you're using VS2010:

```
#if defined(CRYPTOPP_DOXYGEN_PROCESSING)
	static const size_type ELEMS_MAX = ...;
#elif defined(CRYPTOPP_CXX11) && (!defined(_MSC_VER) || (defined(_MSC_VER) && (_MSC_VER >= 1700)))
	enum : size_type {ELEMS_MAX = A::ELEMS_MAX};
#else
	static const size_type ELEMS_MAX = SIZE_MAX/sizeof(T);
#endif

```

**Comment by noloader** [comment]
Thanks @wyattoday.

Sorry about that. My read was the [explicit underlying type (`enum : size_type { ... } `) was supported](https://msdn.microsoft.com/en-us/library/hh567368.aspx):

> Strongly typed enums were partially supported in Visual C++ in Visual Studio 2010 (specifically, the part about explicitly specified underlying types). 

It would not be the first time Microsoft misstated their feature support. I think the Microsoft marketing department filled out the matrix to sell more products. Based on bug reports like these they are not technically correct.

We have a few options. We can (1) add a `CRYPTOPP_CXX11_ENUM` in `config.h`. We can (2) avoid Microsoft products altogether and have Visual Studio just use the `static size_type`. Or (3), we can modify the define like shown above.

I've been favoring enums since they don't take up space in the class. Other than that, there's not much difference between them in our use cases because we only use them as constants. In the past `static int` was favored because some very early compilers had trouble treating enums as constants. (Doxygen still has problems with them, so we have to treat constants as `static int` when generating the manual).

Which do you want to do?

Do you feel like making a PR? If not, then I can cut it in for you.

**Comment by wyattoday** [comment]
I don't have a strong opinion either way. I'm using the code I posted in production (compiles and works fine on VS2010 which uses the `static const`, and VS2012, 2015, 2017 which all support CXX11, and thus use `enum : size_type. `).

I can do a pull request of that change if you want.

**Comment by noloader** [comment]
> I don't have a strong opinion either way....

Ack. Let me add a `CRYPTOPP_CXX11_ENUM` to `config.h`. `CRYPTOPP_CXX11_ENUM` should keep things cleaner.

Then, make a PR against it. 

Give me an hour or so to cut it in and test it.

**Comment by noloader** [comment]
@wyattoday,

Sorry about the delay. I got side tracked on a few other issues. `CRYPTOPP_CXX11_ENUM` was cut-in at [Commit a3b035b6a8b1](https://github.com/weidai11/cryptopp/commit/a3b035b6a8b19874d8897d10bbfaf2e3436eb285). The change to `secblock.h` was tested on my testing fork, but it was ***not*** cut-in on Master.

Would you make the PR please?

Thanks in advance.

**Comment by wyattoday** [comment]
Sure, I'll do it in a few hours and update this issue once I've done it.

**Comment by wyattoday** [comment]
Closing issue because fix merged to master here: https://github.com/weidai11/cryptopp/commit/5149237a5d0cb4a13fe98cbd95115c0957bc748a

**Comment by noloader** [comment]
@wyattoday,

Forgive my ignorance... What was the actual error message?

Would you mind adding it to the report so we have a record of it.

**Comment by wyattoday** [comment]
Sure, here's a snippet of the build output (there are a whole bunch of warnings too, but I'm excluding them here):

```
1>c:\cryptopp\secblock.h(530): warning C4480: nonstandard extension used: specifying underlying type for enum ''
1>        c:\cryptopp\secblock.h(857) : see reference to class template instantiation 'CryptoPP::SecBlock<T,A>' being compiled
1>c:\cryptopp\secblock.h(530): error C3168: 'A::size_type' : illegal underlying type for enum
```
