### ISSUE TITLE
setenv-android.sh -> Wrong path for llvm AOSP_STL_INC

### ISSUE THREAD

**Issue by Deadpikle** [weidai11/cryptopp#490]
For llvm with NDK r15c, the path needs to change from
```
AOSP_STL_INC="$ANDROID_NDK_ROOT/sources/cxx-stl/llvm-libc++/libcxx/include"
```
to
```
AOSP_STL_INC="$ANDROID_NDK_ROOT/sources/cxx-stl/llvm-libc++/include"
```

I haven't opened a pull request for this since at this instant I'm not sure what version of the NDK you are meaning to support.

**Comment by noloader** [comment]
> I haven't opened a pull request for this since at this instant I'm not sure what version of the NDK you are meaning to support.

As many as possible. The idea is an unsuspecting user comes along and `./setenv-android.sh` "just works". We don't want them wasting time like you are suffering.

Can you add some logic to intelligently use the new LLVM path?

**Comment by Deadpikle** [comment]
@noloader I'd be happy to. I'll do that and send in a PR when it's ready.

**Comment by noloader** [comment]
@Deadpikle, thanks again.

Yeah, make the latest NDK the default case. Make the old NDK the exceptional case. Do your best to make them both "just work".

The "it just works" part is very important to me. I don't like it when users suffer because the devs are too lazy to fix a problem once it is identified. God knows I've been on the other end of that too many times.

**Comment by Deadpikle** [comment]
@noloader See #492.

We all have been there way too many times...but at least this lib is open source so people can do something about it! 😀
