### ISSUE TITLE
Android CMake Cross-compilation

### ISSUE THREAD

**Issue by wildbiotiger** [weidai11/cryptopp#493]
Looking for the ability to cross-compile crypto++ using the given CMakeLists.txt file, but it doesn't seem to set all of the same options and provide all of the same features as the setenv-android.sh + GNUMakefile-cross options does.
Expanding the CMake build system to include options like target STL and android version would be nice.

If there's a better way to accomplish this than what I'm suggesting, please let me know.

**Comment by noloader** [comment]
Thanks @wildbiotiger,

CMake is a failed experiment. We are preparing to remove CMake from our sources. Its causes users too many problems like this and other reports like [Issue 486](https://github.com/weidai11/cryptopp/issues/486).

If you have a patch to contribute, then it is welcomed. I'll merge it before the removal.

Also see [Remove CMake from GitHub; add it to Patch Page on wiki?](https://groups.google.com/forum/#!topic/cryptopp-users/PKlz8-ClXOU) on the user mailing list.

My apologies to you and our other users who have endured the problems this program causes. I regret the day I checked-in CMake. My gut told me to put it on the [Patch Page](https://www.cryptopp.com/wiki/Category:Patch) and keep it out of the library, but I did not follow my instincts.

**Comment by wildbiotiger** [comment]
@noloader,

Thanks for the quick response. Cross-compilation is no easy task under any build system. The project I am working with currently uses cmake for the build system, so I unfortunately have to deal with it. Do you have any suggestions for how best to incorporate an android build of crypto++ using cmake? Hooking it in via ExternalProject_Add seemed the best way at the time.

**Comment by noloader** [comment]
> Do you have any suggestions for how best to incorporate an android build of crypto++ using cmake? Hooking it in via ExternalProject_Add seemed the best way at the time.

Sorry, I don't know.

Maybe you can ask the CMake folks how to select an Android profile. If you can find a way, then let us know. We will be happy to check it in for you before we move CMake to the Patch Page.

**Comment by noloader** [comment]
@wildbiotiger, @Deadpikle,

Deadpickle and I just updated the Android procedure due to [Android compiling doesn't seem to work with NDK r15c](https://github.com/weidai11/cryptopp/issues/491). The wiki article covering the procedure is located at [Android (Command Line)](https://www.cryptopp.com/wiki/Android_(Command_Line)).

Maybe you can build the Crypto++ library with the architectures of interest, install them into `/usr/local/`, and then tell CMake to use the libraries that already exist locally rather than building them from sources.

There's a heck of a lot to building for Android. We keep most of it hidden away from users through `setenv-android.sh`. It would be non-trivial to get CMake to do the things the script and makefile does. It would likely take one to two weeks to add it to CMake.

**Comment by wildbiotiger** [comment]
@noloader Thanks for the info. I think we were able to get most of it working using the ExternalProject_Add() function and calling setenv-android.sh and the GNUmakefile-cross from the compilation steps.
I'm good with closing out this issue now.

**Comment by noloader** [comment]
Last call for CMake patches before removing it from the library and adding it to the patch page. If you have something to add, then now is the time to do it.

Also see [Remove CMake from GitHub; add it to Patch Page on wiki?](https://groups.google.com/forum/#!topic/cryptopp-users/PKlz8-ClXOU) and [Commit 1c740b0a097aecaa](https://github.com/weidai11/cryptopp/commit/1c740b0a097aecaa66044036c0d2c54220eda5d5).
