### ISSUE TITLE
Mac OS X 10.6 (g++) link failures

### ISSUE THREAD

**Issue by wyattoday** [weidai11/cryptopp#530]
When building crypto++ with the default GNUmakefile and these parameters:

```
CXXFLAGS = -DNDEBUG -Os -s -fvisibility=hidden -ffunction-sections -fdata-sections -fPIC -arch ppc -arch i386 -arch x86_64 -isysroot/Developer/SDKs/MacOSX10.5.sdk -DMACOSX_DEPLOYMENT_TARGET=10.5 -mmacosx-version-min=10.5

LDFLAGS += -Wl,-dead_strip
```

Everything compiles fine. However, when linking with the statically compiled library you get the following error:

```
Undefined symbols:
  "CryptoPP::AlignedDeallocate(void*)", referenced from:
      CryptoPP::AllocatorWithCleanup<unsigned int, true>::deallocate(void*, unsigned long)in YourObj1.o
      CryptoPP::AllocatorWithCleanup<unsigned char, true>::deallocate(void*, unsigned long)in YourObj2.o
  "CryptoPP::AlignedAllocate(unsigned long)", referenced from:
      CryptoPP::AllocatorWithCleanup<unsigned char, true>::allocate(unsigned long, void const*)in YourObj2.o
```

The fix is to the `config.h` file. Namely, change this:

```
#if (CRYPTOPP_BOOL_X86 || CRYPTOPP_BOOL_X32 || CRYPTOPP_BOOL_X64 || CRYPTOPP_BOOL_PPC32 || CRYPTOPP_BOOL_PPC64) && !defined(CRYPTOPP_DISABLE_ASM)
	#define CRYPTOPP_BOOL_ALIGN16 1
#else
	#define CRYPTOPP_BOOL_ALIGN16 0
#endif
```

To this:

```
#if (CRYPTOPP_BOOL_X86 || CRYPTOPP_BOOL_X32 || CRYPTOPP_BOOL_X64 || CRYPTOPP_BOOL_PPC32 || CRYPTOPP_BOOL_PPC64) && (!defined(CRYPTOPP_DISABLE_ASM) || (CRYPTOPP_GCC_VERSION == 40201 && defined(__APPLE__) && !defined(__clang__)))
	#define CRYPTOPP_BOOL_ALIGN16 1
#else
	#define CRYPTOPP_BOOL_ALIGN16 0
#endif
```

**Comment by noloader** [comment]
Thanks @wyattoday,

I can't duplicate it because I lack 10.6. Sorry about that. What does `nm` have to say about the symbol?

I can switch to ` CXXFLAGS="-DNDEBUG -Os -fvisibility=hidden -ffunction-sections -fdata-sections -fPIC -arch i386 -arch x86_64"`, but I am seeing the symbol in the file.

I don't think the change is a good one for the library as a whole because the underlying problem seems to be mixing distinct architectures, like PPC and i386. I think you should build regular libraries and combine them at the end with `lipo`.

For Crypto++ 6.0 you will need to build non-fat libraries and combine them with `lipo` because we changed to `base+simd`, where `base` is a  C++ implementation, like `aes.cpp`; and `simd` is an accelerated implementation, like `aes-simd.cpp` that requires `-msse4.1 -maes`. We cannot build fat libraries with `-msse4.1 -maes`.

Or, patch the library locally to avoid the upstream change.

**Comment by noloader** [comment]
Closing. I think this is a patch that is better applied locally.
