### ISSUE TITLE
Compile-Error under MacOS

### ISSUE THREAD

**Issue by Skyy93** [weidai11/cryptopp#592]
I'm using MacOS 10.13.3 and getting this error when compiling with `g++ main.ccp -lcryptopp`:

```
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation
```

I found the issue in the GNUmakefile in line 86:

```
# Sun Studio 12.0 provides SunCC 0x0510; and Sun Studio 12.3 provides SunCC 0x0512
SUNCC_VERSION := $(subst `,',$(shell $(CXX) -V 2>&1))
```

This comment the rest of the `GNUmakefile` out. Without `'` in

    (subst `, ,$(shell $(CXX) -V 2>&1))

the compiling works after a new `make && make install`.

**Comment by noloader** [comment]
@mouse07410,

Can you duplicate the issue described above?

**Comment by mouse07410** [comment]
I do not concur. 

But I use Macports-installed GCC 7.3.0, rather than Xcode-provided GCC. And I build a separate copy of Crypto++ library with g++, as in general you cannot link together C++ code compiled by clang++ and g++. So if I compile my app with (Macports) g++, I link it with libcryptopo-gcc.a; and when compiled with Xcode or Macports clang++ - link with libcryptopp.a.

I never tried (and am not planning to) Xcode-provided GCC because it's mostly useless.

MacOS 10.13.3, Xcode 9.2, g++ 7.3.0.

**Comment by noloader** [comment]
@Skyy93,

How about giving this a try:

```
ifeq ($(IS_SUN),1)
# Sun Studio 12.0 provides SunCC 0x0510; and Sun Studio 12.3 provides SunCC 0x0512
SUNCC_VERSION := $(subst `,',$(shell $(CXX) -V 2>&1))
SUNCC_510_OR_LATER := $(shell echo "$(SUNCC_VERSION)" | $(GREP) -i -c -E "CC: (Sun|Studio) .* (5\.1[0-9]|5\.[2-9]|6\.)")
SUNCC_511_OR_LATER := $(shell echo "$(SUNCC_VERSION)" | $(GREP) -i -c -E "CC: (Sun|Studio) .* (5\.1[1-9]|5\.[2-9]|6\.)")
SUNCC_512_OR_LATER := $(shell echo "$(SUNCC_VERSION)" | $(GREP) -i -c -E "CC: (Sun|Studio) .* (5\.1[2-9]|5\.[2-9]|6\.)")
SUNCC_513_OR_LATER := $(shell echo "$(SUNCC_VERSION)" | $(GREP) -i -c -E "CC: (Sun|Studio) .* (5\.1[3-9]|5\.[2-9]|6\.)")
endif
```

**Comment by Skyy93** [comment]
@noloader Hey sorry this still comment it out here i have two screenshots from ATOM
![comment out](https://user-images.githubusercontent.com/20758301/36666171-17f37112-1aea-11e8-9698-e7a494de15bc.png)
![no comment](https://user-images.githubusercontent.com/20758301/36666177-1c71a5f6-1aea-11e8-84d8-9670fe719aff.png)

**Comment by noloader** [comment]
@Skyy93,

I'm still not clear what the problem is with your setup, and what the exact error is. I cannot duplicate it on my OS X machines, but I don't have OS X 10.13. My apologies for that. 

Please perform the following.

```
# Reset the terminal
<CMD>+<K>
<CMD>+<L>

# Undo changes
git checkout master -f

# Build the artifacts
/usr/bin/make static dynamic cryptest.exe
```

Once `make` completes copy all the output from the terminal and paste it into a text file. ZIP the text file. Add the zip file to your issue.

**Comment by noloader** [comment]
Now open on Stack Overflow: [Text substitution with single apostrophe](https://stackoverflow.com/q/48991835/608639).

**Comment by noloader** [comment]
Closing. It looks like a local problem, and not a problem with the library.
