### ISSUE TITLE
qt build

### ISSUE THREAD

**Issue by tasifacuj** [weidai11/cryptopp#659]
Hi, cryptopp devels,

Could you please consider cryptopp.pro for qmake build in attach?
Highly appreciate for any comments or help.
[cryptopp.pro.txt](https://github.com/weidai11/cryptopp/files/2005719/cryptopp.pro.txt)

**Comment by noloader** [comment]
Thanks @tasifacuj,

We usually provide the alternate build systems in my GitHub at [Noloader GitHub](https://github.com/noloader). We then add a wiki page that points to it. The reason it is mine rather than Wei's is, we can't create repo's in Wei's GitHub. I also give all the other maintainers collaborator access to my repo.

A quick comment on your `*.pro` file... You can run `make sources` and it tells you what goes into the library and what goes into the test suite.

**Comment by noloader** [comment]
> can I expect, that this .pro file will be included into master?

No, it is definitely not ready for master.

**Comment by noloader** [comment]
Closing request. We can revisit it in the future if needed.
