### ISSUE TITLE
Android x86 build failed due to _mm_crc32_u8 requires sse4.1

### ISSUE THREAD

**Issue by chongchaoyu** [weidai11/cryptopp#711]
### Crypto++ Issue Report

I use ndkbuild to build Crypto++ 6.1.0 and Crypto++ 7.0.0 to a static lib, but both of them failed, the error is '_mm_crc32_u8' requires target feature 'sse4.1', but would be inlined into  function 'CRC32C_Update_SSE42' that is compiled without support for 'sse4.1', and I have uploaded Android.mk and Application.mk.[mks.zip](https://github.com/weidai11/cryptopp/files/2320429/mks.zip), the detail build log is 
[ndkbuild.txt](https://github.com/weidai11/cryptopp/files/2320435/ndkbuild.txt)

**The detail information is:**
* macOS High Sierra, 10.13.2(71c88)
* cpu: 
   machdep.cpu.brand_string: Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
   machdep.cpu.features: FPU VME DE PSE TSC MSR PAE MCE CX8 APIC SEP MTRR PGE MCA CMOV PAT PSE36 CLFSH DS ACPI MMX FXSR SSE SSE2 SS HTT TM PBE SSE3 PCLMULQDQ DTES64 MON DSCPL VMX EST TM2 SSSE3 CX16 TPR PDCM SSE4.1 SSE4.2 x2APIC POPCNT AES PCID XSAVE OSXSAVE TSCTMR AVX1.0 RDRAND F16C

* Crypto++ 6.1.0 and Crypto++ 7.0.0
* Use ndkbuild, Android.mk and Application.mk
* ndk version is r16b, GNU Make 3.81
* Error message is:
/Users/mikeyu/work/projects/vega/source/yecha/client/frameworks/runtime-src/Classes/thirdparty/pre/jni/cryptopp700/crc-simd.cpp:148:13: error: always_inline function '_mm_crc32_u8' requires target feature 'sse4.1', but would be inlined into
      function 'CRC32C_Update_SSE42' that is compiled without support for 'sse4.1'
        c = _mm_crc32_u8(c, *s);
            ^
/Users/mikeyu/work/projects/vega/source/yecha/client/frameworks/runtime-src/Classes/thirdparty/pre/jni/cryptopp700/crc-simd.cpp:151:13: error: always_inline function '_mm_crc32_u32' requires target feature 'sse4.1', but would be inlined
      into function 'CRC32C_Update_SSE42' that is compiled without support for 'sse4.1'
        c = _mm_crc32_u32(c, *(const word32 *)(void*)s);
            ^
/Users/mikeyu/work/projects/vega/source/yecha/client/frameworks/runtime-src/Classes/thirdparty/pre/jni/cryptopp700/crc-simd.cpp:154:13: error: always_inline function '_mm_crc32_u8' requires target feature 'sse4.1', but would be inlined into
      function 'CRC32C_Update_SSE42' that is compiled without support for 'sse4.1'
        c = _mm_crc32_u8(c, *s);
            ^
3 errors generated.
make: *** [/Users/mikeyu/work/projects/vega/source/yecha/client/frameworks/runtime-src/Classes/thirdparty/pre/obj/local/x86/objs/cryptopp_static/cryptopp700/crc-simd.o] Error 1

**Comment by noloader** [comment]
Thanks @chongchaoyu.

Yeah, that sounds about right. Here are some additional resources that may help you with `Android.mk`.

1. [PR #3, Add Android.mk to build using android NDK](https://github.com/weidai11/cryptopp/pull/3) by @cawka. It is a little dated now. We held off on the PR because of the unusal directory structure required by Android. I would have merged it years ago if `Android.mk` could reside in root with the makefile.

2. Running `make sources` will list the files needed by the library proper (`libcryptopp.a`) and the test suite (`cryptest.exe`)

3. [BASE+SIMD](https://www.cryptopp.com/wiki/BASE+SIMD) wiki page list the files that need arch flags and the arch flags

4. [Android (Command Line)](https://www.cryptopp.com/wiki/Android_(Command_Line)) wiki page which provides make-based instructions. The procedures use `GNUmakefile-cross` because we need extra flags for the platforms. We use this to test Android builds on Travis CI.

**Comment by chongchaoyu** [comment]
@noloader Thank you for your response, I will try it later with your resources. 
BTW, I have downgraded to 5.6.5, and it works well.

**Comment by noloader** [comment]
@chongchaoyu 

One other thing... The current [`config.h`](https://github.com/weidai11/cryptopp/blob/master/config.h#L563) has the following. It will part of the upcoming 7.1 release.

```
// Fixup Android and SSE, Crypto. It may be enabled based on compiler version.
#if (defined(__ANDROID__) || defined(ANDROID))
# if (CRYPTOPP_BOOL_X86)
#  undef CRYPTOPP_SSE41_AVAILABLE
#  undef CRYPTOPP_SSE42_AVAILABLE
#  undef CRYPTOPP_CLMUL_AVAILABLE
#  undef CRYPTOPP_AESNI_AVAILABLE
#  undef CRYPTOPP_SHANI_AVAILABLE
# endif
# if (CRYPTOPP_BOOL_X64)
#  undef CRYPTOPP_CLMUL_AVAILABLE
#  undef CRYPTOPP_AESNI_AVAILABLE
#  undef CRYPTOPP_SHANI_AVAILABLE
# endif
#endif
```

Older versions of the library don't have the block above. Older versions required a user add the define on the command line. That's a pain in the butt. Since Android has a stable hardware requirements list, we now do it for users.

**Comment by noloader** [comment]
@chongchaoyu, @cawka, @Deadpikle,

What do you guys think about setting up `cryptoppp-android` on my GitHub like `cryptoppp-autotools` and `cryptoppp-cmake`? The GitHub will include the `Android,mk` file. , and we can run it like `cryptoppp-autotools` and `cryptoppp-cmake`.

We will help maintain it like when we add `crc-simd.cpp` with special flags. Folks like you will be made collaborators so you can check-in changes as you see fit. We won't be in your way.

**Comment by chongchaoyu** [comment]
@noloader @cawka @Deadpikle I think it is a good idea, and it can benefit users a lot and save much time. I am not a skillful c++ programmer, I spent almost two days to compile sources to static lib, suffering many problems, such as version, c++_static/gnustl_static, so painful:(

**Comment by noloader** [comment]
We added a repo to independently provide Android.mk support at [Noloader | cryptopp-android](https://github.com/noloader/cryptopp-android). The initial check-in is complete. Now we have to fix it and tune it.

**Comment by noloader** [comment]
@chongchaoyu,

I believe the [cryptopp-android](https://github.com/noloader/cryptopp-android) project files are ready for consumption. I also added a wiki page at [Android.mk (Command Line)](https://www.cryptopp.com/wiki/Android.mk_(Command_Line)).
