### ISSUE TITLE
patch for the google native client (NaCl) target 

### ISSUE THREAD

**Issue by asbai** [weidai11/cryptopp#719]
All versions of nacl sdk use the same buggy gcc 4.4.3 toolchain. When compiling C++ code, the compiler even crashes itself (SEGFAULT). But it still the only way to produce the nacl program (.nexe).

Fortunately, crypto++ does not encounter this problem. But there are some inline assembly code in x64 environment cannot be assembled correctly.

To compile the nacl_x64 target, we need some small changes:

1. vmac.cpp
from:
```
#if defined(CRYPTOPP_DISABLE_VMAC_ASM)
# undef CRYPTOPP_X86_ASM_AVAILABLE
# undef CRYPTOPP_X32_ASM_AVAILABLE
# undef CRYPTOPP_X64_ASM_AVAILABLE
# undef CRYPTOPP_SSE2_ASM_AVAILABLE
#endif
```

to:
```
#if defined(CRYPTOPP_DISABLE_VMAC_ASM) \
	|| (defined(__native_client__) && CRYPTOPP_BOOL_X64) // NaCl x64 workaround 
# undef CRYPTOPP_X86_ASM_AVAILABLE
# undef CRYPTOPP_X32_ASM_AVAILABLE
# undef CRYPTOPP_X64_ASM_AVAILABLE
# undef CRYPTOPP_SSE2_ASM_AVAILABLE
#endif
```

2. whrlpool.cpp:
from:
```
#if defined(CRYPTOPP_DISABLE_INTEL_ASM)
# undef CRYPTOPP_SSE2_ASM_AVAILABLE
# undef CRYPTOPP_SSSE3_ASM_AVAILABLE
#endif
```

to:
```
#if defined(CRYPTOPP_DISABLE_INTEL_ASM) \
	|| (defined(__native_client__) && CRYPTOPP_BOOL_X64) // NaCl x64 workaround 
# undef CRYPTOPP_SSE2_ASM_AVAILABLE
# undef CRYPTOPP_SSSE3_ASM_AVAILABLE
#endif
```

That's all.

**Comment by noloader** [comment]
Thanks @asbai,

I'm not familiar with the Google Native Client so I'm not sure how to evaluate things.

A quick read of [Google Native Client](https://en.wikipedia.org/wiki/Google_Native_Client) says:

> To run an application portably under PNaCl, it must be compiled to an architecture-agnostic and stable subset of the LLVM intermediate representation bytecode. The executables are called PNaCl executables (pexes). The PNaCl Toolchain makes .pexe files; NaCl Toolchain .nexe files...

I'm not a fan of byte code that gets re-written on the fly for the case of high integrity software. It is non-deterministic from our perspective, and we can't audit the output artifacts to ensure they meet security goals. I'm also not a fan of working someone else's bugs.

I'm thinking we should leave the use case officially unsupported, but ensure it is doable for someone who wants it. We use this strategy for Clang in several cases, like LLVM bytecode on ARM and Clang pretending to be the MSVC compiler.

The "ensure it is doable" may be as easy as the following in `config.h`:

```
#if defined(__native_client__)
#  define CRYPTOPP_DISABLE_ASM
#endif
```

I can only say "maybe" because I have not tested anything. As you know a lot of testing is required to say something like "enable ASM for exeverything except VMAC and Whirlpool on x86_64".

Ping @mouse07410, @MarcelRaad, @denisbider. What do you guys think?

**Comment by mouse07410** [comment]
I don't like NaCl, and am not crazy about Google crazy ideas (PNaCl, Bazel, and a few other things).

In short: I'm ok if somebody would support this as a separate patch. I'd rather not have it in the main trunk.

**Comment by asbai** [comment]
@noloader I'm not using the PNaCl, Just the native nacl (x64 target). So we don't need to disable asm globally. Instead, we want to keep as much assembly optimization as possible :-)

@mouse07410 Yes, I don't like it too. But it's the most suitable solution for some cases.

**Comment by noloader** [comment]
@asbai,

Thanks.

> I'm not using the PNaCl, Just the native nacl (x64 target). So we don't need to disable asm globally. Instead, we want to keep as much assembly optimization as possible :-)

How do I setup a test rig for this?

**Comment by asbai** [comment]
@noloader
> How do I setup a test rig for this?
Just follow these instructions: https://developer.chrome.com/native-client/sdk/download

**Comment by asbai** [comment]
Your intuition is correct @noloader 

Even if we can compile and link the nacl target, it will still crashed at runtime if we enable the inline asm of libcryptopp. So we need to disable it at the global stage like:
```
#ifdef __native_client__
#	define CRYPTOPP_DISABLE_ASM 1
#endif
```

Even more, the "rep stos..." insturctions are also not support by nacl. So in misc.h we need change:
```
#if (_MSC_VER >= 1400 || defined(__GNUC__)) && (CRYPTOPP_BOOL_X64 || CRYPTOPP_BOOL_X86)
```

to:
```
#if (_MSC_VER >= 1400 || defined(__GNUC__)) && (CRYPTOPP_BOOL_X64 || CRYPTOPP_BOOL_X86) \
	&& !defined(__native_client__) // NaCl not support rep stos... insturctions
```

**Comment by noloader** [comment]
Cleared at Commits 180b39f and 1de4f39.
