### ISSUE TITLE
XChaCha20 support

### ISSUE THREAD

**Issue by fxha** [weidai11/cryptopp#727]
Do you plan to add the `XChaCha20` cipher because the default cipher has only a 64-bit nonce? It should be a similar initialization as `XSalsa20` with the `HSalsa20` construction. A problem may be that it isn't standardized yet but it's implemented in other libraries such as `libsodium` and `go crypto`.

**References:**

[draft arciszewski xchacha](https://tools.ietf.org/html/draft-arciszewski-xchacha-02)

**Comment by noloader** [comment]
Yes, we'll support this eventually.

Also note TLS uses a variation on ChaCha that's not compatible with Bernstein's ChaCha. TLS's ChaCha looks more like XChaCha. And as far as I know the kernel provides TLS's ChaCha, not Bernstein's ChaCha due to VPN over TLS.

It is really unfortunate the IETF hijacked the ChaCha name and did not distinguish it like with XChaCha. They were warned of the interop problems they were causing in advance.

**Comment by noloader** [comment]
@fxha,

We cut-in ChaChaTLS, which is the IETF's bastardized algorithm. Documentation is at [ChaChaTLS](https://www.cryptopp.com/wiki/ChaChaTLS) on the wiki.

Poly1305 was hijacked too. I've done some initial tests and I need to refactor the scalar multiplications and then have Bernstein's Poly1305 and the IETF's Poly130 use the refactored code. That is going to take a couple of days.

Once Poly1305 is complete I can move onto XChaCha.

**Comment by noloader** [comment]
Done and done.
