### ISSUE TITLE
Provide CMake build system

### ISSUE THREAD

**Issue by GamePad64** [weidai11/cryptopp#73]
Well, the idea is to move away from traditional Makefile to a Makefile generator. CMake is the most robust, stable and reliable cross-platform build system.

Advantages:
- Much, MUCH easier to maintain:
Now we have to mantain Visual Studio project, Borlang C++ Builder project, GNUmakefile, GNUmakefile-cross, and (bonus!) Debian maintainers also have to maintain autoconf/automake builds. Using CMake you just have to maintain a single file: CMakeLists.txt
- Uniform across all platforms
We don't need to remember, how to build Crypto++ on Windows or Android (and it is really hard without something like msys2, if using MinGW).  
Building process is the same on every single platform:
```shell
mkdir build
cd build
cmake ../build
cmake --build .
```
- Cross-platform out of the box:
CMake uses [toolchain files](https://cmake.org/cmake/help/v3.0/manual/cmake-toolchains.7.html) to be really crossplatform. If you want to cross-compile Crypto++ for Android or Raspberry PI, for example, you just create CMake toolchain file for each platform, and it works like magic.
- Great documentation and community
CMake is becoming *de facto* standard in building C and C++ applications, gaining popularity every day.
- Many IDE's start to support it out of the box:  
Visual Studio (using generator)  
Code::Blocks (using generator)  
Eclipse CDT (using generator)  
CLion (natively!)

Disadvantages:
- It would be necessary to rewrite building process in various Linux distros.

If you are agree with this idea, I can start writing the CMakeLists.txt file right now, so we could complete it until version 5.7. Also, we can roll out both Makefile+CMake builds simultaneously in 5.7, and remove Makefile in 6.0 (as it is a major release).

**Comment by noloader** [comment]
> If you are agree with this idea, I can start writing the CMakeLists.txt 

Yes, I've been looking for a `CmakeList.txt` for some time. See, for example, [Add Android.mk to build using android NDK](https://github.com/weidai11/cryptopp/pull/3).

When you build your file list, you can perform the following to ensure you get the list the makefile uses:

    cd cryptopp-git
    git pull # recent check-in
    make sources
    Library sources: cryptlib.cpp cpu.cpp 3way.cpp adler32.cpp algebra.cpp...
    Test sources: bench.cpp bench2.cpp test.cpp validat1.cpp validat2.cpp...

***Note well***: ordering of the source files and subsequently the object files matters. That's because we have the [Static Initialization Order Fiasco](https://cryptopp.com/wiki/Static_Initialization_Order_Fiasco) to contend with.

***Note well***: there will be minor issues to contend with, like when to add `-fPIC` or when to define `MACPORTS_GCC_COMPILER`. Please review the `GNUmakefile` for the conditions.

Myself and the other folks who maintain Crypto++ do not use Cmake, so we probably won't maintain it to a high degree. That means folks like you will have to own it.

Please provide it as a pull request so we can ensure you get credit at [Contributors](https://github.com/weidai11/cryptopp/graphs/contributors). If you don't care about credit, then make it available for download or email it to me (noloader, gmail account).

**Comment by GamePad64** [comment]
Okay, many projects use both Makefile+CMake builders, and everyone is free to use whatever is more suitable in each situation. I will do it.

**Comment by noloader** [comment]
> I will do it.

Thanks. I'll be looking forward to it.

I'll also add you to my packager/maintainer list so you will be looped in for changes like new source files added or new defines to work around issues we encounter int he field. Please email me with your preferred contact info (noloader, gmail account).

**Comment by noloader** [comment]
Merged at a2c1e49a01b5f28624eae .
