### ISSUE TITLE
32-bits GCC/Linux debug build self test failures

### ISSUE THREAD

**Issue by dvetutnev** [weidai11/cryptopp#782]
https://travis-ci.org/odant/conan-cryptopp/builds/480116204

Passed if add CXXFLAGS -DCRYPTOPP_DISABLE_ASM

**Comment by noloader** [comment]
Thanks @dvetutnev,

I am busy at the moment but I should be able to look at it later tonight or tomorrow.

In the meantime we found some bugs in GCC, Clang and XLC where the compiler described SSE and PowerPC intrinsics incorrectly. The definitions incorrectly required aligned buffers, and the compiler removed code it could prove was not using aligned data. The problem was, the intrinsics we used did not have alignment requirements. It also hit use on other platforms like PowerPC.

Also see [UBsan and runtime error: signed integer overflow using unsigned vector](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=88234) and [Clang 7.0 claims unaligned load with POWER7 vec_xl](https://bugs.llvm.org/show_bug.cgi?id=39704). I believe I have one for GCC from a couple of years ago that covers early GCC.

**Comment by noloader** [comment]
@dvetutnev,

I setup a Ubuntu 14.05 32-bit/i686 VM. I ran `apt-get update && apt-get upgrade` (not *not* `dist-upgrade`).

I see the compilers are GCC 4.8.4 on both your test rig and my VM.

My build using default flags is OK. My build flags include `-DCRYPTOPP_DISABLE_SHANI`, which was detected by the makefile. However, it does not use PIC.

***Conan***:

```
Using testing flags: -std=c++11 -fPIC -m32 -DNDEBUG -g2 -O3
g++ -std=c++11 -fPIC -m32 -DNDEBUG -g2 -O3 -pthread -pipe -c cryptlib.cpp
g++ -std=c++11 -fPIC -m32 -DNDEBUG -g2 -O3 -pthread -pipe -c cpu.cpp
...
```

***My VM, your flags***:

```
$ CXXFLAGS="-std=c++11 -fPIC -m32 -DNDEBUG -g2 -O3 -pthread" make -j 4
g++ -std=c++11 -fPIC -m32 -DNDEBUG -g2 -O3 -pthread -DCRYPTOPP_DISABLE_SHANI -pipe -c cryptlib.cpp
g++ -std=c++11 -fPIC -m32 -DNDEBUG -g2 -O3 -pthread -DCRYPTOPP_DISABLE_SHANI -pipe -c cpu.cpp
...
```

My build tests OK here, too.

Here's what I am seeing for the toolchain:

```
jwalton@ubuntu14-x86:~$ gcc --version
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.4) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
...

jwalton@ubuntu14-x86:~$ ld -v
GNU ld (GNU Binutils for Ubuntu) 2.24
...

jwalton@ubuntu14-x86:~$ ldd --version
ldd (Ubuntu EGLIBC 2.19-0ubuntu6.14) 2.19
Copyright (C) 2014 Free Software Foundation, Inc.
...
```

Would you happen to know how Conan is different than a straight Ubuntu VM with an update/upgrade?

**Comment by dvetutnev** [comment]
> Would you happen to know how Conan is different than a straight Ubuntu VM with an update/upgrade?
Conan use Docker for build with different compilers. Images here: https://github.com/conan-io/conan-docker-tools

**Comment by noloader** [comment]
> Images here: https://github.com/conan-io/conan-docker-tools ...

Looking at the one called [conan-docker-tools/gcc_4.8-x86/Dockerfile](https://github.com/conan-io/conan-docker-tools/blob/master/gcc_4.8-x86/Dockerfile) (I assume this is the correct one):

```
...
RUN dpkg --add-architecture i386 \
    && apt-get -qq update \
    && apt-get -qq install -y --no-install-recommends \
sudo=1.8.* \
...
<no Binutils in the list>
```

So they are *not* performing an update yet they have an updated Binutils. I perform an update but I *don't* have an updated Binutils.

Something fishy is going on.

**Comment by noloader** [comment]
@dvetutnev,

Would it be possible to perform the following on your Conan rig and post the results somewhere (or attach it to the report):

```
CXXFLAGS="-std=c++11 -fPIC -m32 -DCRYPTOPP_DEBUG -g2 -O3 -pthread" make -j 4
...
./cryptest.exe v
...
```

The special sauce for this recipe is `CRYPTOPP_DEBUG`. It provides extra debug checks. However, when an assert fires, a `SIG_TRAP` is sent instead of `SIG_ABRT`. We install a `SIG_TRAP` handler if one is not present, so the program should complete with diagnostics written to stderr when something goes wrong.

Some diagnostics are expected, like the negative self tests that attempt to break the ASN.1 parser or the Integer divide by 0 tests.

**Comment by noloader** [comment]
@dvetutnev,

I'd still like the `CRYPTOPP_DEBUG` results if you have the time. It will help me diagnose things further since I cannot reproduce locally.

In the meantime, [Commit e86a6b32eb56](https://github.com/weidai11/cryptopp/commit/e86a6b32eb56) added a define for the case I suspect. The case is compilers are too strict with alignment requirements for some loads and stores, and the compiler silently removes good code. It usually mucks with LEA, SIMON, and SPECK. Those algorithms load a 32-bit or 64-bit subkey into a SIMD word, like a __m128i` (or more correctly, load multiple subkeys at once).

Based on your recent change to Conan at [Commit 9ebc06134d0f](https://github.com/odant/conan-cryptopp/commit/9ebc06134d0f), I believe you should do this instead. The Conan commit uses the `CRYPTOPP_DISABLE_ASM` sledge hammer, which disables all ASM and SIMD code. I think you can be a little more surgical, and leave ASM or SIMD code for algorithms like AES and SHA.

```
$ git diff
diff --git a/config.h b/config.h
index 17271630..6c3c8c3b 100644
--- a/config.h
+++ b/config.h
@@ -303,7 +303,7 @@ const lword LWORD_MAX = W64LIT(0xffffffffffffffff);
 // of GCC and Clang require 16-byte aligned arrays when using the builtin
 // function. It is not limited to SSE and PowerPC code. Define this to disable
 // Crypto++ code that uses potentially problematic builtins or intrinsics.
-// #define CRYPTOPP_BUGGY_SIMD_LOAD_AND_STORE 1
+#define CRYPTOPP_BUGGY_SIMD_LOAD_AND_STORE 1

 // This list will probably grow over time as more compilers are identified.
 #if defined(CRYPTOPP_BUGGY_SIMD_LOAD_AND_STORE)
```

**Comment by noloader** [comment]
Closing. Unable to duplicate.
