### ISSUE TITLE
Including Crypto++ headers disables warnings

### ISSUE THREAD

**Issue by espindola** [weidai11/cryptopp#793]
Given a test file with just

    static void foo() {}

`gcc -Wall` will print

    warning: ‘void foo()’ defined but not used [-Wunused-function]

But if I add

    #define CRYPTOPP_ENABLE_NAMESPACE_WEAK 1
    #include <cryptopp/md5.h>

No waning is printed. This is because of the following in `cryptopp/config.h`.

    #pragma GCC diagnostic ignored "-Wunused-function"

**Comment by noloader** [comment]
@espindola,

For the library, it is a "pick your poison". If we don't use `-Wno-unused-function` then we catch multiple warnings due to unused functions like `StringNarrow` (if I recall correctly). That generates multiple user bug reports.

If we silence the warning, then we get your bug reports.

In this case I think the best thing to do is for you to remove the pragma from `config.h`. Then you can catch them.

You might also consider asking GCC to move `-Wunused-function` to `-Wextra`. Unused functions in C++ header files does not seem like the kind of warning that needs to be flagged. It is expected in C++ project files.

**Comment by noloader** [comment]
[Commit b29faeab58e7](https://github.com/weidai11/cryptopp/commit/b29faeab58e7) should help you remove `-Wunused-function` from `config.h`. But I don't want to go down this rabbit hole too far.

**Comment by noloader** [comment]
I'm closing this out. This is about as far as I want to go.

I suggest a GCC bug report that asks GCC to stop flagging C++ functions in headers as unused. They are expected.
