### ISSUE TITLE
donna_64.cpp failed to compile under VC2005 with x64 target

### ISSUE THREAD

**Issue by asbai** [weidai11/cryptopp#802]
### Crypto++ 8.0 Issue Report

The type uint8_t and int64_t not defined under old VC. So we need add following workaround to the head of this cpp file:
```C++
#if defined(_MSC_VER) && _MSC_VER < 1700
	typedef unsigned char   uint8_t;
	typedef signed __int64  int64_t;
#endif
```

**Comment by noloader** [comment]
Thanks @asbai,

We should not be using `uint8_t` or `int64_t` because of problems like this.

Instead, we should be using `byte` and `sword64`. I believe this problem slipped into the Crypto++ 8.0 release. It was fixed after the release at [Commit 9c58ba8f2bae](https://github.com/weidai11/cryptopp/commit/9c58ba8f2bae).
