### ISSUE TITLE
Add std::byte overloads

### ISSUE THREAD

**Issue by Lyberta** [weidai11/cryptopp#816]
This has been mentioned in the wiki as a possible solution. Since I've upgraded my code to C++17 and `std::byte`, I have to `reinterpret_cast` my buffers to `CryptoPP::byte`. I think this is a usability issue.

Can you add overloads that take `std::byte*` to functions that take `CryptoPP::byte*`?

**Comment by noloader** [comment]
`std::byte` is not compatible with the library's `byte`. The library's `byte` is closer to an `uint8_t`.

**Comment by Lyberta** [comment]
You can do `reinterpret_cast` inside the library. Why are you making your users suffer?

**Comment by anonimal** [comment]
I hardly consider using fully qualified types, like a responsible developer, to be suffering.

**Comment by noloader** [comment]
Plus it breaks down-level clients. Someone building for C++03 won't be able to compile code with `std::byte`, and we can't add the `byte` symbol to the `std` namespace because the C++ language forbids it.

Not to mention adding a `std::byte` interface means we need to duplicate every class method and free standing function.

**Comment by Lyberta** [comment]
You add it when the code is built in C++17 or newer mode, it's been suggested to have `CRYPTOPP_CXX17` on the wiki.
