### ISSUE TITLE
zdeflate error 

### ISSUE THREAD

**Issue by srwinohio** [weidai11/cryptopp#83]
When I compress a plain
[atom.txt](https://github.com/weidai11/cryptopp/files/61198/atom.txt)

 text buffer, I get an assert from zdeflate in MatchFound, line 
assert(length >= 3 && length < COUNTOF(lengthCodes));

Code snippet that I am using to compress......

	CryptoPP::Gzip zipper;

         //is -  is an ifstream passed in

	//read the source file
	if (!is.is_open() || !os.is_open() )
	{
		return(-1);
	}

	// get its size:
	long fileSize = getFileSize(is);

	//allocate a buffer big enough to read the entire file
	byte *buffer = new byte[(long)fileSize+1024];

	if (buffer != NULL)
	{
		//read the entire file into the buffer
		is.read((char *)buffer, fileSize);

		//compress it
		zipper.Put((byte*)buffer, (int)fileSize);
		zipper.MessageEnd();
      }

**Comment by noloader** [comment]
@srwinohio - ACK. I'm going to need some time to look at it.

Can you add the code for `getFileSize`?

**Comment by srwinohio** [comment]
unsigned long CCactCompression::getFileSize(ifstream *ifs)
{
	// get its size:
	streampos fileSize;

	ifs->seekg(0, ios::end);
	fileSize = ifs->tellg();
	ifs->seekg(0, ios::beg);

	return((unsigned long)fileSize);
}

This appears to have something to do with the source data. The file I test with is a repeated string. If I use a more "random" type file, for instance a log file from an application, it works just file.

Steve

**Comment by noloader** [comment]
> This appears to have something to do with the source data. 

Thanks Steve.

I'm actually somewhat familiar with this issue. I've seen it show up on occasion under Valgrind. I was chasing it for months. I added the asserts in an attempt to locate the issue.

I had a hard time duplicating it in the past. I *thought* we cleared the actual memory issue based on a Coverity finding/CID 148082 (https://scan.coverity.com/projects/cryptopp). Though its not readily apparent, the `SecBlock` is really an array of [`CodeInfo`](https://www.cryptopp.com/docs/ref/zinflate_8h_source.html#l00053) objects.

If you can, would you build the library with `g2` and `-O0` or `-O1`, and then run the test case under Valgrind? Valgrind requires [`-O0` or `-O1` for accurate results](http://valgrind.org/docs/manual/quick-start.html). You can do so with:

    make distclean
    export CXXFLAGS=`-DNDEBUG -g2 -O1`
    make static dynamic test

Then, build your program with the same flags and options, and then run it under Valgrind:

    valgrind ./myprog

The `-DNDEBUG` will keep the `assert` from crashing the program since its not desired at this point. We have a fix for the unwanted crash via [trap.h](https://www.cryptopp.com/docs/ref/trap_8h_source.html), we just need to cut it in.

Thanks in advance.

Jeff

**Comment by srwinohio** [comment]
OK, I'll do that today
Steve

**Comment by noloader** [comment]
@Steve, here are my results with `CXXFLAGS="-DNDEBUG -g3 -O1"`.

First, the test program:
```
$ cat gzip-test.cxx
#include <string>
using namespace std;

#include "gzip.h"
#include "files.h"
#include "filters.h"
using namespace CryptoPP;

int main(int argc, char* argv[])
{
  string result;
  FileSource fs("atom.txt", true, new Gzip(new StringSink(result)));
  return 0;
}
```

Next, the result on OS X (the leak is expected due to OS X's dyld):

```
$ c++ $CXXFLAGS -I. ./libcryptopp.a gzip-test.cxx -o gzip-test.exe
riemann:cryptopp-mobile$ valgrind ./gzip-test.exe
==1516== Memcheck, a memory error detector
==1516== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==1516== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
==1516== Command: ./gzip-test.exe
==1516== 
==1516== 
==1516== HEAP SUMMARY:
==1516==     in use at exit: 58,603 bytes in 351 blocks
==1516==   total heap usage: 567 allocs, 216 frees, 337,897 bytes allocated
==1516== 
==1516== LEAK SUMMARY:
==1516==    definitely lost: 16 bytes in 1 blocks
==1516==    indirectly lost: 0 bytes in 0 blocks
==1516==      possibly lost: 0 bytes in 0 blocks
==1516==    still reachable: 0 bytes in 0 blocks
==1516==         suppressed: 58,587 bytes in 350 blocks
==1516== Rerun with --leak-check=full to see details of leaked memory
==1516== 
==1516== For counts of detected and suppressed errors, rerun with: -v
==1516== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

At this point, I don't believe there's an underlying memory issue.

I think the assert is a bit too aggressive. Next, I'm going to tune the assert.

**Comment by noloader** [comment]
@Steve - the assert in `zdeflate.cpp:591` was bad. It should have been `length-3 < COUNTOF(lengthCodes)`.

Do you want to submit a patch via a pull request? If you do, then you will receive credit and be listed at [Contributors](https://github.com/weidai11/cryptopp/graphs/contributors). I prefer folks helping the project receive credit for their work.

If not, then I can check-in the following:

```
$ cat zdeflate.diff
diff --git a/zdeflate.cpp b/zdeflate.cpp
index fea6025..9643d5d 100644
--- a/zdeflate.cpp
+++ b/zdeflate.cpp
@@ -588,7 +588,7 @@ void Deflator::MatchFound(unsigned int distance, unsigned int length)
 
 	assert(m_matchBufferEnd < m_matchBuffer.size());
 	EncodedMatch &m = m_matchBuffer[m_matchBufferEnd++];
-	assert(length >= 3 && length < COUNTOF(lengthCodes));
+	assert((length >= 3) && (length-3 < COUNTOF(lengthCodes)));
 	unsigned int lengthCode = lengthCodes[length-3];
 	m.literalCode = lengthCode;
 	m.literalExtra = length - lengthBases[lengthCode-257];
```

**Comment by srwinohio** [comment]
I can do that, I think :)

Sent from Yahoo Mail on Android 
 
  On Tue, Dec 15, 2015 at 17:47, Jeffrey Walton<notifications@github.com> wrote:   
@Steve - the assert in zdeflate.cpp:591 was too aggressive. It should have been length-3 < COUNTOF(lengthCodes).

Do you want to submit a patch via a pull request? If you do, then you will receive credit and be listed at Contributors. I prefer folks helping the project receive credit for their work.

If not, then I can check-in the following:
$ cat zdeflate.diff
diff --git a/zdeflate.cpp b/zdeflate.cpp
index fea6025..9643d5d 100644
--- a/zdeflate.cpp
+++ b/zdeflate.cpp
@@ -588,7 +588,7 @@ void Deflator::MatchFound(unsigned int distance, unsigned int length)

    assert(m_matchBufferEnd < m_matchBuffer.size());
    EncodedMatch &m = m_matchBuffer[m_matchBufferEnd++];
-   assert(length >= 3 && length < COUNTOF(lengthCodes));
+   assert((length >= 3) && (length-3 < COUNTOF(lengthCodes)));
    unsigned int lengthCode = lengthCodes[length-3];
    m.literalCode = lengthCode;
    m.literalExtra = length - lengthBases[lengthCode-257];

**Comment by noloader** [comment]
@Steve - If you fork Crypto++, then you can create a pull request by following [Using pull requests](https://help.github.com/articles/using-pull-requests/)

**Comment by srwinohio** [comment]
OK

**Comment by noloader** [comment]
Fixed at https://github.com/weidai11/cryptopp/commit/28a5fead3b25d9a00871d6fe8ffe970116956300.
