### ISSUE TITLE
Program stuck on MUL_16 (line 1411 in integer.cpp)

### ISSUE THREAD

**Issue by MislavJuric** [weidai11/cryptopp#849]
Hello there,

I am using Debian 9.8 (Stretch). I am using Crypto++ version 8.2.0. downloaded from the Crypto++ website. I built the library using Make and the instructions on the [Wiki page](https://www.cryptopp.com/wiki/Linux#Build_and_Install_the_Library). I built my one-file program using:

    g++ myfile.cpp -o myfile.o -DNDEBUG -g3 -O2 -Wall -Wextra -l:libcryptopp.a

My compiler gives me some warnings, but only about implicit type conversions (unrelated to the bug at hand; it is related to some other parts of my program which do not produce the bug).

**My program gets stuck on the Mul_16 line (line 1411) of integer.cpp file.** 

Here is the code that causes this:

```
CryptoPP::AutoSeededRandomPool rnd;

CryptoPP::InvertibleRSAFunction params;
params.GenerateRandomWithKeySize(rnd, 12000); 
```

I ran the program 3 times and it always gets stuck on the line I gave you above. I found that out by running my program in gdb and pressing CTRL + C and seeing where it was at the time it received SIGINT. The 12000 magic number was chosen just cause - it could have been any other number (I tried).

The desired behavior is for the program not to get stuck on that line.

I am using this library for a college assignment; just wanted to let you know what happened.

Best regards!

**Comment by noloader** [comment]
> `params.GenerateRandomWithKeySize(rnd, 12000);`

I seem to recall it takes either 45 minutes or two days to generate a 10,000-bit RSA key. I thought I had a wiki page on it, but I cannot find it at the moment. The program is called `rsa_kgen_prof.zip`, it is located at [RSA Cryptography](https://cryptopp.com/wiki/RSA_Cryptography), but it is missing the table of timings.

You are probably being impatient.

Run your experiment again with a 256-bit modulus. The function should return immediately.

Otherwise, we need more information to investigate further. We need the library version, the source of the library, and the platform.

**Comment by noloader** [comment]
> I seem to recall it takes either 45 minutes or two days to generate a 10,000-bit RSA key. I thought I had a wiki page on it, but I cannot find it at the moment. The program is called rsa_kgen_prof.zip, it is located at RSA Cryptography, but it is missing the table of timings.

I found the page with the timing information. I moved it to [RSA Cryptography | Profiling Key Generation](https://www.cryptopp.com/wiki/Rsa_cryptography#Profiling_Key_Generation).

The 10,000 bit keygen time is between 2 and 4 minutes on a semi-modern Intel processor.

**Comment by noloader** [comment]
@MislavJuric, do you have anything else? If not I'm going to close this report.
