### ISSUE TITLE
Issues with post build event with newer msvc

### ISSUE THREAD

**Issue by cstamatopoulos** [weidai11/cryptopp#87]
Post build event should be changed to `Win32\output\debug\cryptest mac_dll $(TargetDir)\cryptopp.dll
echo mac done > "$(OutDir)"\cryptopp.mac.done`. The reason is that there is a mismatch between the `${TargetName}` which cryptdll and the actual output dll which is `cryptopp.dll`.

Ideally the fix should be the other way around so that the `${TargetName}` is correct so the above is just a workaround. Also the hardcoded values of vc80 should be changed to probably `${TargetName}.pdb` so that they are OK in case users update the VS solution file to a newer version.

**Comment by noloader** [comment]
> Also the hardocded values of vc80 should be changed to probably ${TargetName}.pdb

I seem to recall there was an issue with this. The issue was VS2005 did not use a macro (i.e., a hard code value), while VS2010 and above uses a macro (I can't find the name at the moment).

**Comment by noloader** [comment]
> Issues with post build event with newer msvc

What version of Visual Studio are you using? And what solution and project files are you using?

**Comment by cstamatopoulos** [comment]
I am using MSVC 2015 and the solution file that you provide.
All these problems were fixed once I used the solution from the .zip file.

But if that is the one that is working fine why is it in the zip file ?

**Comment by noloader** [comment]
> All these problems were fixed once I used the solution from the .zip file.

Yeah, what we found was [`VCUpgrade`](https://www.google.com/search?q=visual+studio+vcupgrade) really sucks. Its poorly documented, and it does a poor job of upgrading the Visual Studio 2005 project files to VS2010 or above.

-----

> But if that is the one that is working fine why is it in the zip file ?

Visual Studio 2010 is a cross-over point due to changes in the underlying MSBuild. Once converted, folks cannot go back to a previous version of the library. We did not want to force folks into using something they may not have. Also see [Visual Studio | Visual Studio 2005](https://www.cryptopp.com/wiki/Visual_Studio#Visual_Studio_2005) on the wiki.

**Comment by noloader** [comment]
We might be making Visual Studio 2010 the default sometime after the first of the year. See [Make VS2010 default sometime in 2016?](https://groups.google.com/d/msg/cryptopp-users/vCYAEj3OI8g/BPxFrKedDgAJ)

**Comment by noloader** [comment]
@cstamatopoulos - you made some suggestions.... Would you be able to provide a ***`diff`*** of what you propose? I'm currently looking at the Visual Studio gear due to routine testing of recent check-ins.

**Comment by cstamatopoulos** [comment]
Well the main thing is to fix the x64 compilation that is pointing to the wrong static libs. The patch file below does that. Then upgrading and building with msvc 2015 works without any issues, you can just built the dll and that will built all the necessary dependencies. I have not tested it with 2010 though.

[patch.txt](https://github.com/weidai11/cryptopp/files/73367/patch.txt)

If you want to go one step further it would be good instead of $(ProjectName) for cryptest and cryptdll to have the actual name, same as what has been done for cryptdll already.

**Comment by noloader** [comment]
> Well the main thing is to fix the x64 compilation that is pointing to the wrong static libs. The patch file below does that. 

Ah, OK, thanks.

We can't do that because the process is basically written in stone. That is, the Crypto++ [FIPS Security Policy](http://csrc.nist.gov/groups/STM/cmvp/documents/140-1/140sp/140sp819.pdf) dictates that the 32-bit version of `cryptest.exe` writes the fingerprint. We can't change it.

This in one of the instances of the problem I was talking about earlier: we cannot express the dependencies we need in the Visual Studio project files. Or I have not been able to figure out how to do it.

**Comment by cstamatopoulos** [comment]
I think it is possible, let me have a look prior to closing this.

**Comment by noloader** [comment]
> I think it is possible, let me have a look prior to closing this.

OK, thanks. *If* the fix is to use x64's `cryptest.exe`, then we won't be able to make the change. In this case, I would recommend adding the patch to the [Patch Category](https://www.cryptopp.com/wiki/Category:Patch) on the Crypto++ wiki. I suggest offering the patch because I think it could be useful.

If the fix is to correctly express the dependencies, then yes, please. I also have an open question at Stack Overflow: [How to control order of Batch Build → Build All](http://stackoverflow.com/q/33191432).

**Comment by cstamatopoulos** [comment]
Well the easiest solution that I can think of and tested is
1) in the configuration change the cryptest to be win32 (probably delete x64 completely to avoid confusion)
2) Of course that will require linking with the win32 cryptlib.lib so we need to make a copy of the .vcxproj and duplicate that so we can add a dependency for it that is win32

DLL-import configs for cryptest.exe can also be setup but that will also require duplicating the dll project. 

Is this easier than running 2 times I dont know, but I definitely was not aware that the win32 exe should be used which is why I got confused.
