### ISSUE TITLE
error caused by cpu-features.c getting compiled with CXX

### ISSUE THREAD

**Issue by pagdot** [weidai11/cryptopp#926]
### Crypto++ Issue Report

* OS:
  + Host: Xubuntu: Linux 5.3.0-26-generic #28~18.04.1-Ubuntu SMP Wed Dec 18 16:40:14 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
  + Target: Android 24, NDK 21.0.6113669
* Crypto++ 8.2.0
* Build script based on setenv-android.sh: [build_crypto++_android.sh](https://github.com/weidai11/cryptopp/files/4122880/build_crypto%2B%2B_android.sh.txt)
* Error:
```
armv7a-linux-androideabi24-clang++ -DNDEBUG -g2 -O3 -fPIC -pipe -Wall -march=armv7-a -mthumb -mfloat-abi=softfp -funwind-tables -fexceptions -frtti -DANDROID --sysroot=/home/paul/Android/Sdk/ndk/21.0.6113669//toolchains/llvm/prebuilt/linux-x86_64//sysroot -Wa,--noexecstack -I -I -fpermissive -c cpu-features.c
clang++: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]
cpu-features.c:222:13: error: assigning to 'const char *' from incompatible type 'void *'
        p = memmem(p, bufend-p, field, fieldlen);
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cpu-features.c:234:10: error: assigning to 'const char *' from incompatible type 'const void *'
    p  = memchr(p, ':', bufend-p);
         ^~~~~~~~~~~~~~~~~~~~~~~~
cpu-features.c:240:9: error: assigning to 'const char *' from incompatible type 'const void *'
    q = memchr(p, '\n', bufend-p);
        ^~~~~~~~~~~~~~~~~~~~~~~~~
cpu-features.c:246:14: error: assigning to 'char *' from incompatible type 'void *'
    result = malloc(len+1);
             ^~~~~~~~~~~~~
cpu-features.c:399:13: error: assigning to 'const char *' from incompatible type 'const void *'
        q = memchr(p, ',', end-p);
            ^~~~~~~~~~~~~~~~~~~~~
cpu-features.c:693:15: error: assigning to 'char *' from incompatible type 'void *'
    cpuinfo = malloc(cpuinfo_len);
```

* Fix: Changing compiler in GNUmakefile-cross from CXX to CC

**Comment by noloader** [comment]
Thanks @pagdot.

I think the problem here is, we do very little with `CC` and we don't set `CFLAGS` since we are a C++ project. I don't want to maintain C projects settings for a C++ project. Also, the compiler fols say to compile everything with the same compiler, so I want to continue to use the C++ compiler.

We need Android to fix their bug. The bug was reported 4 years ago at Android Issue 65641866, [Dirty compile when compiling cpu-feature.c with C++ compiler](https://issuetracker.google.com/issues/65641866).
