### ISSUE TITLE
Illegal instruction in CryptoPP::CPU_ProbeARMv7() under armv5tel architecture

### ISSUE THREAD

**Issue by greyltc** [weidai11/cryptopp#931]
Details here:
https://github.com/Entware/Entware/issues/412
Any help would be welcome!

**Comment by noloader** [comment]
@greyltc,

This is normal:

```
Program received signal SIGILL, Illegal instruction.
0x0032535c in CryptoPP::CPU_ProbeARMv7() ()
```

`CPU_ProbeARMv7` sets up a `SIGILL` handler, and then tries a ARMv7 `movw` and `movt` instructions. See [`neon_simd.cpp`](https://github.com/weidai11/cryptopp/blob/master/neon_simd.cpp).

But in your case, since you are building for ARMv5, your should set `CRYPTOPP_DSIABLE_ASM`. We don't provide anything that targets less then ARMv7-a. Open [`config_asm.h`](https://github.com/weidai11/cryptopp/blob/master/config_asm.h) and set `#define CRYPTOPP_DISABLE_ASM 1`.

**Comment by greyltc** [comment]
Thank you! Hopefully the entware folks can add this to the build
