### ISSUE TITLE
std::uncaught_exceptions is only available for macOS >=10.12

### ISSUE THREAD

**Issue by TheSlowGrowth** [weidai11/cryptopp#980]
* macOS Deployment Target: 10.11
* Crypto++ commit 7ea79f1, 2019-08-10 (== 8.2.0 + various additional commits that we needed due to  #872 )
* Built with Xcode12, clang

There is a compiler error in algparam.h:313
```
312: #if defined(CRYPTOPP_CXX17_EXCEPTIONS)
313: 		if (std::uncaught_exceptions() == 0) // here
314: #elif defined(CRYPTOPP_UNCAUGHT_EXCEPTION_AVAILABLE)
315: 		if (std::uncaught_exception() == false)
316: #else
317: 	 	try
318: #endif
```
> 'uncaught_exceptions' is unavailable: introduced in macOS 10.12

This compiles fine with Xcode 11, but probably would cause a runtime error because the function is not actually part of the runtime in macOS 10.11 and lower. Xcode 12 adds this compiler error.

This could maybe be handled by evaluating the Macros from "AvailabilityMacros.h"

**Comment by noloader** [comment]
Thanks @TheSlowGrowth,

`CRYPTOPP_CXX17_EXCEPTIONS` should be set in [`config_cxx.h`](https://github.com/weidai11/cryptopp/blob/master/config_cxx.h), but I am not seeing it. I think we changed it to `CRYPTOPP_CXX17_UNCAUGHT_EXCEPTIONS` to differentiate between `CRYPTOPP_CXX98_UNCAUGHT_EXCEPTION`.

`CRYPTOPP_CXX17_UNCAUGHT_EXCEPTIONS` is set thusly:

```
// C++17 uncaught_exceptions: MS at VS2015 (19.00); GCC at 6.0; Clang at 3.5; Intel 18.0.
// Clang and __EXCEPTIONS see http://releases.llvm.org/3.6.0/tools/clang/docs/ReleaseNotes.html
#if defined(__clang__)
# if __EXCEPTIONS && __has_feature(cxx_exceptions)
#  if __cpp_lib_uncaught_exceptions
#   define CRYPTOPP_CXX17_UNCAUGHT_EXCEPTIONS 1
#  endif
# endif
#elif (CRYPTOPP_MSC_VERSION >= 1900) || (__INTEL_COMPILER >= 1800) || \
      (CRYPTOPP_GCC_VERSION >= 60000) || (__cpp_lib_uncaught_exceptions)
# define CRYPTOPP_CXX17_UNCAUGHT_EXCEPTIONS 1
#endif // uncaught_exceptions compiler
```

What change do you suggest?

**Comment by noloader** [comment]
@TheSlowGrowth,

Yeah, so this is an Apple and/or Clang bug. Apple must provide an implementation for `std::uncaught_exceptions`, and Clang must not define `__cpp_lib_uncaught_exceptions` unless `std::uncaught_exceptions` are available.

The workaround is to run the `configure.sh` program to detect the bogus configuration. Or, manually edit `config_cxx.h` and remove the define `CRYPTOPP_CXX17_UNCAUGHT_EXCEPTIONS` since we are being lied to.

Also see [Error: 'uncaught_exceptions' is unavailable: introduced in macOS 10.12](https://stackoverflow.com/a/53259955) and LLVM bug 39631, [__has_feature(cxx_exceptions) returns true but fails to compile std::uncaught_exceptions()](https://bugs.llvm.org/show_bug.cgi?id=39631).
